### ISSUE TITLE
CABPK manifest is missing metadata

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes-sigs/cluster-api#10165]
### What steps did you take and what happened?

I updated from 1.4.9 to 1.5.5

In `capi-kubeadm-bootstrap-controller-manager-59984b8784-q78pk`, there is only this Info/warn/error:
```
I0216 09:59:20.071707       1 cluster_cache_tracker.go:161] "remote/ClusterCacheTracker: Couldn't find controller pod metadata, the ClusterCacheTracker will always access clusters using the regular apiserver endpoint"
```

In other controller, I don't see errors.

But on `capi-controller-manager-58fbc78955-g4njq`, there is this error:
```
E0216 10:00:13.382563       1 machineset_controller.go:883] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="prod/prod-md-0-sm6mt" namespace="prod" name="prod-md-0-sm6mt" reconcileID=xxx MachineDeployment="prod/prod-md-0" Cluster="prod/prod" Machine="prod/prod-md-0-sm6mt-2mz62" node=""
```

I see this error 2 times for each worker, and I have 3 workers.

If I downgrade to 1.4.9, it goes away. I have the same error in 1.5.5 nad on 1.6.1.

### What did you expect to happen?

no errors in the logs

### Cluster API version

1.5.5

### Kubernetes version

1.27.9

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by chrischdi** [comment]
Potentially related / improved / fixed already on main:

- #9810

It was not cherry-picked back (only for CRS to fix CI related flakes) because we were not able to reproduce it for the other controllers in real.

**Comment by chrischdi** [comment]
Question: is the issue for you persistent or resolves itself after ~17 mins?

**Comment by fabriziopandini** [comment]
/triage accepted

> remote/ClusterCacheTracker: Couldn't find controller pod metadata, the ClusterCacheTracker will always access clusters using the regular apiserver endpoint

Is because we are missing https://github.com/fabriziopandini/cluster-api/blob/0f47a19e038ee6b0d3b1e7675a62cdaf84face8c/controlplane/kubeadm/config/manager/manager.yaml#L28-L40 on the CABPK manifest (probably a leftover of a PR that started using ClusterCacheTracker on a manifest)

This should be fixed in main and backported as far as possible

> Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already

Is not an issue
It is a transient condition that happens when two threads/reconcile loops running in parallel are trying to get a client from ClusterCacheTracker, and the client does not exist yet.
This error can appear many times if the underlying connection is not stable, and the reconcile loops/ClusterCacheTracker continuously tries to recreate connections, and each operation takes 10s before timing out (during those 10s other reconcile loops/ClusterCacheTracker gets the lock error).
