### ISSUE TITLE
Should we keep the provider implementers office hours meetings?

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1027]
As discussed at this week's Cluster API meeting - should we keep the provider implementers office hours meetings? Are they serving your needs?

cc @dlipovetsky

**Comment by dlipovetsky** [comment]
The attendance has decreased during the v1alpha2 design period. However, people new to the project frequently join with questions about the implementation, roadmap, etc. These kinds of questions are typically not asked or answered during the "main" meeting.

**Comment by dlipovetsky** [comment]
Some providers (CAPA, CAPV, CAPZ, to name some) have their own meetings. But this meeting is an opportunity project newcomers to ask questions, contributors to bikeshed on issues, and it's a place to do demos and code walkthroughs. The "main" CAPI meeting isn't a great place for these, because its time is taken up by provider status updates, decision making, and issue triage.

**Comment by vincepri** [comment]
@ncdc Any thoughts about @dlipovetsky reply?

**Comment by ncdc** [comment]
Perhaps we could suggest people who attend the meetings could add their feedback here?

**Comment by dlipovetsky** [comment]
At the 03/18/2020 meeting, we decided to cancel the separate office hours and create dedicated Q&A time in the main meeting.
