### ISSUE TITLE
Consider if IntOrString fields should really be pointers

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#10750]
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/10712#discussion_r1634964694

We have plenty of fields in our API which are `*instr.IntOrString`, e.g.

```go
	// +optional
	MaxUnhealthy *intstr.IntOrString `json:"maxUnhealthy,omitempty"`
```

Usually fields like this should only be pointers if there is a semantic difference between "empty" and nil. I'm not sure if that is the case here and they should really be pointers.

Comment from @vincepri from the linked PR

> IntOrString is a pointer almost anywhere else, looking at the functions in the intstr package, it seems nil is almost everywhere used as a base value, and strings are treated as percentage or a number; empty string isn't really handled so we'd have to check outside like we do today for the pointer

I was looking into k8s.io/api. I found 23 occurences of `*intstr.IntOrString` and 5 occurences of `intstr.IntOrString`.
<img width="1933" alt="image" src="https://github.com/kubernetes-sigs/cluster-api/assets/4662360/a44b3e55-cae8-4a42-809c-85fe51c373b3">

**Comment by sbueringer** [comment]
cc @JoelSpeed

**Comment by JoelSpeed** [comment]
I believe that `intstr.IntOrString` should normally be a pointer, if it is optional, and not a pointer, when required. Looking at the list you found, that pretty much tallies up there as well.

Looking at this [playground](https://go.dev/play/p/tDI0yA_uuAM) shows that the optional field, when not a pointer, does not behave as expected. The `omitempty` does not work.

Why is that? Well, JSON marshalling, and particular the `omitempty` flag only actually works for types that it can determine are empty. Struct references are not in that list, but struct pointers are.

Since `IntOrString` is actually represented by a struct underneath, it needs to be a pointer so that the marshalling can work correctly for the optional field.

**Comment by sbueringer** [comment]
Thank you. Makes sense!

/close
