### ISSUE TITLE
Setting a standard for VM images to be used by CAPI

### ISSUE THREAD

**Issue by rajaskakodkar** [kubernetes-sigs/cluster-api#10900]
### What would you like to be added (User Story)?

As a developer I would like a list of components and standards that make a VM image to be used by CAPI

### Detailed Description

Currently, cluster-api uses VM images from https://github.com/kubernetes-sigs/image-builder as Kubernetes disk images for various infrastructure providers. There is no standard set for what makes an image compatible to be used by CAPI. The boundaries between OS layers and Kubernetes requirements aren't defined.

There is a need to set this standard to make it flexible for the community to come up with a VM image, not necessarily from image-builder and yet have enough confidence to make it CAPI conformant.

### Anything else you would like to add?

This requires more details on gathering what are the requirements from CAPI to make a VM image usable as a Kubernetes disk image and I will update this issue with the investigations I make

### Label(s) to be applied

/kind feature

**Comment by rajaskakodkar** [comment]
cc @fabriziopandini @sbueringer @chrischdi @randomvariable @vincepri

**Comment by randomvariable** [comment]
cc @neolit123 , as we're mostly talking about kubeadm 'readiness'

**Comment by fabriziopandini** [comment]
I think requirements from core CAPI are pretty thin, because it ultimately it expects the image to be able to run a Kubernetes node (which what machine controller requires to determine machine provisioning is completed).
Notably, in projects like the Cluster API provider kubemark, kubemark (a fake K8s Node) is all we need to get a working "machine".

As pointed how above, additional requirements should be considered when using KCP / CAPBK, where I think at high level what is mandatory to have is
- a machine bootstrapper (cloud-init or ignition)
- all the requirements from kubeadm (see https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)

**Comment by randomvariable** [comment]
> we should not document them in such an image builder document because they need to be updated in kubeadm first.

Yeah, I agree with that. When we did the first round of image builder, we mostly used the K8s website instructions for deploying a cluster with kubeadm to figure out what went where.

**Comment by fabriziopandini** [comment]
@rajaskakodkar is that ok for what you are looking for?
can we convert this to some document in our book?

**Comment by sbueringer** [comment]
/close

As per comments above kubeadm documentation is the best source of info available for this. Regarding undocumented k8s component dependencies Cluster API would be the wrong place to document them.
