### ISSUE TITLE
Timed out after 1200.000s. Timed out waiting for all control-plane machines in Cluster k8s-upgrade-and-conformance

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#11296]
### Which jobs are flaking?

- periodic-cluster-api-e2e-mink8s-main
- periodic-cluster-api-e2e-main

### Which tests are flaking?

capi-e2e [It] When upgrading a workload  cluster using ClusterClass with a HA control plane [ClusterClass] Should  create and upgrade a workload cluster and eventually run kubetest

ref: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1845590172469563392 

### Since when has it been flaking?

More flaky after 11-10-2024

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20waiting%20for%20all%20control-plane%20machines%20in%20Cluster%20k8s-upgrade-and-conformance&job=.*-cluster-api-.*&xjob=.*-provider-.*%7C.*-operator-.* 

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1845590172469563392

### Reason for failure (if possible)
Network plugin returns error: cni plugin not initialized, expected the Ready condition

### Label(s) to be applied

/kind flake
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by adilGhaffarDev** [comment]
/assign
I am looking into this one

**Comment by sbueringer** [comment]
Just adding it here as well for future-us.

This issue is caused by the following chain of events:
* Test is failing because kube-proxy on worker Machine is not working
* kube-proxy on worker Machine is not working because kubelet is not working
* kubelet is not working because kubelet 1.31 communicates with kube-apiserver 1.30
* worker has been upgraded to 1.31 while there were still 1.30 apiservers around
* Cluster topology controller thought the control plane upgrade was already done (but we still had a 1.30 CP Machine)
* KCP reported .spec.version == .status.version == v1.31
* KCP calculates .status.version based on min_version (Machines with healthy apiserver)  and the 1.30 CP Machine reported * APIServerHealthy false (even though it was still reachable)

**Comment by sbueringer** [comment]
Perfect! Thx for checking / confirming

/close
