### ISSUE TITLE
[0.1] MachineDeployments, MachineSets, and Machines should always have a Cluster owner reference if a Cluster exists

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1190]
/kind bug

**What steps did you take and what happened:**
- Create a Cluster
- Create a MachineDeployment, MachineSet, or Machine and manually specify an ownerReference to some arbitrary resource that is not a Cluster
- The created resource does not end up with an ownerReference pointing at the Cluster

**What did you expect to happen:**
- There should be an ownerReference pointing at the Cluster

**Anything else you would like to add:**
The MachineDeployment, MachineSet, and Machine controllers only add an ownerReference to the Cluster if there are 0 ownerReferences. If there is at least 1, the controllers do not create the Cluster ownerReference.

The reason I'd like to always have a Cluster ownerReference is so we can identify all of a Cluster's dependent objects and issue delete requests for each dependent object when a Cluster is deleted. This helps address #985 along with #1180

**Environment:**

- Cluster-api version: v0.1.8 and earlier
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
+1 to always ensuring a reference to a Cluster. However do we expect that reference to always be a direct reference, or should we also allow indirect references?

For example, do we expect all Machines to have a Cluster reference, or only Machines that do not belong to a MachineSet? Similar for MachineSets, do we expect all MachineSets to have a Cluster reference or only MachineSets that do not belong to a MachineDeployment?

If we are using these Owner references to force the right deletion order, I would argue that we should prefer indirect references, so that a Cluster would always attempt to delete starting with the top level parent objects rather than the lower level child objects.

**Comment by liztio** [comment]
I think we should replace "check length of list" with "check if list currently references a machineset or machinedeployment." We want to keep the tree hierarchy

**Comment by vincepri** [comment]
+1 to this, the behavior described is what happens today in v1alpha2. The util functions to work with ownerRefs could be backported for simplicity.

**Comment by ncdc** [comment]
The deletion logic coming in #1180 will delete MachineDeployments, then MachineSets, then Machines as part of the cluster deletion/finalizer logic. I think we'd be fine either with direct or indirect references.

**Comment by ncdc** [comment]
This was fixed in #1207
/close
