### ISSUE TITLE
RFE: Single cluster spanning AZs / Failure domains

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1269]
As a kubernetes operator, I'd like to deploy a cluster whose machines are evenly spread across a label (zone/region). 

/kind feature

**Comment by vincepri** [comment]
@timothysc This is a duplicate of #46, which one should we close?

**Comment by alexeldeib** [comment]
FWIW, I still think you need an explicit mechanism to tell a provider to do this. 

zone/region are common labels, but are after infrastructure bootstrapping so can't be used here. Someone/thing/data has to bootstrap this process, and it should be consistent across providers. It can either anything from binary "spread me" to a CRD describing the hierarchy of each providers topology. Maybe I'm sticking my head in the sand, but I pondered how to do this with affinities/tolerations as suggested by Tim and Justin and came up pretty empty. 

I ended up implementing spreading by default on top of VMSS because I needed it.

**Comment by timothysc** [comment]
Closing this one in favor of https://github.com/kubernetes-sigs/cluster-api/issues/46
