### ISSUE TITLE
docs/book: Figure out which tool to use for diagrams

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1368]
/kind documentation

**Describe the solution you'd like**
The tool we use for proposals is very technical and doesn't allow for customization. We should pick a single tool that we can use as a community to draw diagrams for the book.

**Comment by detiber** [comment]
I'd rather not re-litigate diagramming tools again and think we should stick with the existing tool for now.

**Comment by vincepri** [comment]
I was wondering which tool was used for the README's diagram, because it's a nice visualization but it's not really doable with PlantUML. I like PlantUML, but it's very technical and raw for newcomers

**Comment by detiber** [comment]
I believe it depends on what use we are talking about for diagrams...  The graphic in the README is an svg, which could have been created/edited with any SVG editor (such as Inkscape or Adobe Illustrator). I don't think we need to restrict SVGs to a tool such as PlantUML, since it is able to be edited and modified using other tooling.

For the more technical diagrams (such as flowcharts, state diagrams, etc) a tool like PlantUML would be easier for modifying and editing and would be better than the web-based tools we've used for those in the past.

**Comment by vincepri** [comment]
draw.io is great for that

/close
