### ISSUE TITLE
kubectl edit machine fails validations

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#137]
> 
> machines "karangoel-test1" was not valid:
> * : Invalid value: "The edited file failed validation": [ValidationError(Machine.spec.providerConfig.value): unknown field "apiVersion" in io.k8s.            apimachinery.pkg.runtime.RawExtension, ValidationError(Machine.spec.providerConfig.value): unknown field "kind" in io.k8s.apimachinery.pkg.runtime.             RawExtension, ValidationError(Machine.spec.providerConfig.value): unknown field "terraformMachine" in io.k8s.apimachinery.pkg.runtime.RawExtension,             ValidationError(Machine.spec.providerConfig.value): unknown field "terraformVariables" in io.k8s.apimachinery.pkg.runtime.RawExtension,                         ValidationError(Machine.spec.providerConfig.value): missing required field "Raw" in io.k8s.apimachinery.pkg.runtime.RawExtension]

To repro:

1. Deploy cluster
2. kubectl edit machine machineName
3. Edit something other than providerConfig (eg controlPlane version)

/cc sig-cluster-lifecycle

**Comment by krousey** [comment]
This is kubectl validation failing for some reason. I am able to successfully edit when I do `kubectl edit machine <machine name> --validate=false` and everything works as expected.

**Comment by karan** [comment]
Yes if I disable validation it works. We should look into why the validation is failing though.

**Comment by karan** [comment]
This seems to be an issue with newer kubectl. v1.9 and newer have this problem.

**Comment by rsdcastro** [comment]
Does this impact only Terraform or also GCP?

**Comment by karan** [comment]
It should impact gce as well.

I think @k4leung4 did some testing for this bug as well.

**Comment by roberthbailey** [comment]
@pwittrock - is there a tracking bug for kubectl 1.9 not working properly with custom types?

**Comment by nikhita** [comment]
Noticed something similar with kubectl validation. It seems to have grown stricter since 1.9. For example,

If my deployment yaml contains `spec.replicAs: 3`:

- earlier kubectl versions do not complain, the deployment configuration is accepted and the json decoder unmarshals it as `spec.replicas: 3` (unmarshalling is always case-insensitive).
- the newer kubectl versions check if the literal `replicAs` exists for the Deployment type, sees that it doesn't and complains that no such field `replicAs` exists. If `--validate=false` is used, the deployment configuration is accepted and the json decoder unmarshals normally as  `spec.replicas: 3`.

Of course, this is true for all resources, not just deployments.

In this case, `Machine.spec.providerConfig.value` is of type `*runtime.RawExtension`:

https://github.com/kubernetes-sigs/cluster-api/blob/a9f06b0f4871bebd8a3f3fb555dccef676605cbb/pkg/apis/cluster/v1alpha1/common_types.go#L31

`RawExtension` by itself does not have any field called `apiVersion`, etc:

https://github.com/kubernetes/kubernetes/blob/0ea07c40305afa845bc34eb6a73da960552c39b1/staging/src/k8s.io/apimachinery/pkg/runtime/types.go#L92-L100

Looks like kubectl notices that it does not have any field called `apiVersion` and complains at validation. When `--validate=false` is used, we skip this validation and the json decoder decodes correctly.

Afaik the only change to kubectl validation was moving to open api validation -- I'll check that further to see what could be going wrong and comment here if I find anything.

**Comment by pwittrock** [comment]
@seans3 Can you take a look?

**Comment by seans3** [comment]
Talked to @apelisse. Work in kube-openapi is already beginning to address this.

**Comment by seans3** [comment]
https://github.com/kubernetes/kube-openapi/pull/25

**Comment by roberthbailey** [comment]
Since this is not a cluster api issues I'm going to bump it out of the alpha milestone.

**Comment by timothysc** [comment]
@detiber - please verify and, or document.

**Comment by ncdc** [comment]
This is most likely an issue that will be resolved with a change in kubernetes/kubernetes. I propose we move this out of v1alpha1. cc @detiber

**Comment by ncdc** [comment]
The referenced kube-openapi PR has been merged. I'm wondering if this is possibly fixed. Would someone have some time to test this issue and report back?

**Comment by detiber** [comment]
I just tested this with `kubeadm` version 1.13.1 and I am no longer able to replicate the issue. Closing.

/close
