### ISSUE TITLE
bootstrap/kubeadm: Release story

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1508]
After merging CABPK under this repository, we need to figure out what our release story is going to look like and how to automate the process

/milestone v0.3.0
/priority important-longterm
/help
/kind feature

**Comment by chuckha** [comment]
Related to this #1686 

Do we want to publish this as a stand alone module? I think not because CABPK is published with CAPI. Either users are going to use CAPI+CABPK or just CAPI and some other bootstrap provider. I don't think there is any need for a standalone CABPK release, we just have to figure out #1686.

/close
