### ISSUE TITLE
Follow consistent api-grouping standards 

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1521]
**What steps did you take and what happened:**
Currently we miss-use api-groups in cluster api which don't make sense from a consumption model.  API-groups are a unit of consumption that are versioned together and who concepts and dependencies are self contained where possible. 

We should not have multiple api-groups per concept b/c the concepts are co-dependent and are not consumable in their own form, nor are they group versioned independently.  

/kind bug

**Comment by ncdc** [comment]
Could you please be specific with the changes you'd like to see? Thanks!

**Comment by timothysc** [comment]
infrastructure.cluster.x-k8s.io + bootstrap.cluster.x-k8s.io => cluster.x-k8s.io

**Comment by ncdc** [comment]
Thank you 😄 

Although if we change the api group, we can't do conversion webhooks

**Comment by detiber** [comment]
Do we expect that provider implementations would always be versioned in lockstep with core cluster-api?

**Comment by vincepri** [comment]
In v1alpha2 we decided to use multiple API groups for a number of reasons:

- Permissions: Cluster API grants itself RBAC permissions for all resources in those API groups, without the need for a provider to grant additional RBAC for each of their types, which happened in v1alpha1.
- Extensibility: Folks can add to these groups without touching Cluster API, or following CAPI versions.
- Responsibilities: Differentiate "core" types from others, set expectations around guarantees.
- Communication: It's easier to distinguish and context switch between groups when we talk about it.

That said, I can see why you might want to fold everything in one group. This proposed change could impact how easy it's going to be to upgrade from v1alpha2 to v1alpha3, as @ncdc mentioned. 

Is this something we might want tackle in the future instead of next iteration?

**Comment by ncdc** [comment]
I think this is worth considering when we decide it's time to graduate from alpha to beta maybe?

**Comment by vincepri** [comment]
closing this for now given that we'll revisit during api-review / when graduating to beta

/close
