### ISSUE TITLE
[cabpk] Rename kubeadm package because `kubeadm/kubeadm/` is redundant 

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1544]
/kind bug

If you have feelings about what to name a package containing copy/pasted kubeadm types please write them here.

**Comment by wfernandes** [comment]
/assign

I was thinking of `types` as the replacement name of the package. 

So for example the import in `kubeadmnbootstrapconfig_controller.go` would look like
`kubeadmv1beta1 "sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/v1beta1"`
instead of 
`kubeadmv1beta1 "sigs.k8s.io/cluster-api/bootstrap/kubeadm/kubeadm/v1beta1"`

**Comment by chuckha** [comment]
in my wildest of dreams i want to use the upstream types.

But barring that, I think `types` is a good name to replace kubeadm
