### ISSUE TITLE
States, transitions, and conditions

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#1658]
Opening this issue as a placeholder, to be filled as time goes by. We know that the current model has gaps in terms of `Status.Phase` field, its use and shortcomings. We'll be tracking progress towards a proposal and better model within this issue. Feel free to add more information, comments, concerns.

/kind proposal
/milestone Next
/priority important-longterm
/assign @timothysc

**Comment by detiber** [comment]
Some controversy over [lists of named subobjects](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps) vs use of [maps](https://github.com/kubernetes/kubernetes/issues/8190#issuecomment-538605819)

**Comment by jayunit100** [comment]
Just getting into CAPI internals so could be off - but - as an interim solution with long term dashboard value ---  Maybe for now just putting the right metrics for API calls in place will be a good enough workaround ---  
- labels for the providers based on `infrastructureRef` will give you provider specific states
- labels such as `still_awaiting_cloud_controller`

**Comment by evankanderson** [comment]
Some drive-by comments (feel free to ping me at evana at vmware.com if I don't notice updates here):

We spent a long time (about 4 weeks) working on Condition design with UX designers and tooling engineers. The end result is specified here, but I'll also give some useful summaries and a link to the library we wrote:

https://knative.dev/docs/serving/spec/knative-api-specification-1.0/#error-signalling

Some of the lessons we learned:

* Having a consistent polarity for Conditions (i.e. "True = good" or "False = good") is really helpful for tooling, particularly if you want the server side to be able to add or change conditions without needing to go through and coordinate with every single tool that works with the API.
   * It's important to name the conditions so that it's clear what "True" and "False" means. Sometimes this means you need to be creative, i.e. "ResourcesAvailebl" even if you're really thinking of it as "QuotaExhausted" (and definitely don't call it "Quota").
* It's really useful to have an agreed-on top-level condition that summarizes all the other conditions (again, it simplifies work for tool authors). In Knative, we defined two top-level conditions. Each resource should have one or the other of these conditions (and not both):
    * `Ready`, for resources which represent an ongoing status, like a Deployment
    * `Succeeded`, for resources which run-to-completion, like a Job
* Every resource except data-only objects which aren't reconciled (like ConfigMap) must have conditions. This avoids situations like NetworkPolicy, where you can't tell if the cluster is actually able to support the NetworkPolicy based on the CNI plugin used.
* Our experience with actual users suggested that the "True = good" polarity was read more naturally than "False = good". In particular, "FooFailed = False" tended to be read as a problem or a negative situation, rather than a successful state. This is particularly an issue for users in stressful situations (new users, live demos, handling production outages, etc).
* Knative also added a "severity" field to conditions to handle providing warnings. Note that the default severity was "Error", which we ended up spelling as "" (empty string). See the previous point for the rationale. (Multiple senior PMs and engineers were thrown off by:
   ```yaml
   conditions:
   - type=Ready
     severity=Error
     status=True
   ```
   Severity may be overkill for your needs; we found some cases where it was helpful to be able to pass back information in conditions that didn't indicate an error.


Library implementing consistent ("True = good") polarity, condition aggregation to common top-level: https://godoc.org/github.com/knative/pkg/apis#ConditionSet.Manage

**Comment by vincepri** [comment]
Thank you so much @evankanderson for sharing your experience with conditions! After v1alpha3 is wrapped up, we'll start working on a proposal, the context you provided is going to be super helpful.

**Comment by vincepri** [comment]
As per April 27th 2020 community guidelines, this project follows the process outlined in https://github.com/kubernetes-sigs/cluster-api/blob/master/CONTRIBUTING.md#proposal-process-caep for large features or changes.

Following those guidelines, I'll go ahead and close this issue for now and defer to contributors interested in pushing the proposal forward to open a collaborative document proposal instead, and follow the process as described.

/close

**Comment by benmoss** [comment]
A proposal was made here https://docs.google.com/document/d/1eWTDcNp8p-m-RheaX4WJmmb0YGDSm_Ruj1GjtVZ_9Jk/edit

**Comment by enxebre** [comment]
@vincepri @ncdc This is linked in the roadmap under "Improved status conditions" https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/roadmap.md

Based on https://github.com/kubernetes-sigs/cluster-api/issues/1658#issuecomment-620118757
is there a doc related to this? if so is there a place where I can find the link to that doc? I'd expect this ticket to be that place so the roadmap does not lead us to a dead end.

My intention was to add a relevant ref https://github.com/kubernetes/enhancements/pull/1624 to this topic.

**Comment by fabriziopandini** [comment]
new tracking issue for the CAEP is https://github.com/kubernetes-sigs/cluster-api/issues/3005
@enxebre the Kuberenetes KEP is already in the radar
