### ISSUE TITLE
Project roadmap?

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1863]
Would y'all be interested in creating a project roadmap for Cluster API? I'm thinking this could be a way to keep track of the features we'd like to deliver in the next ~2 releases, plus a list of things that are farther out. If yes, any suggestions on where to put it, and how to keep it up to date?

@CecileRobertMichon @rudoi @juan-lee @michaelgugino @akutz @andrewsykim @detiber @vincepri @joonas @noamran @randomvariable @chuckha @rsmitty @hardikdr @timothysc @pablochacin @dlipovetsky @samba + please tag anyone else who you think would be interested in chatting here

**Comment by detiber** [comment]
@ncdc we could leverage GitHub projects to do this and/or just issues filed against milestones.

**Comment by detiber** [comment]
> Actually, putting on an end-user/consumer hat, would it be worth having roadmap information in the published book?

If we do, I think it should be something that is auto-generated and updated from a canonical source regularly (issues w/ a certain label against a milestone, GitHub project, etc) otherwise it's likely to get stale quick and not reflect reality.

**Comment by wfernandes** [comment]
A project roadmap would be great to have! +1 this.

As @ncdc suggested, it would be nice to have a concept like epics or feature tracks where issues could we tagged with so we can see how much progress has been accomplished for each epic.

A simplistic approach would be having a set of labels like `epic/cool-feature-1` and add that label to corresponding issues. Github projects allows filtering based on labels so we can use that to "track" how much work needs to get done in order to complete a feature (based on whatever columns we choose).

The cluster api book can point to whatever project tool we decide to use because having information regarding roadmap in the published book would also seem to fall into the trap of becoming stale and outdated. 

Also, who is the audience for this project roadmap. Developers? Product Managers? 
For developers, I think it would be nice to not stray too far away from the Github ecosystem.
Not sure about PMs.

**Comment by nader-ziada** [comment]
+1 for a simple md file with milestones and listing of features, maybe with one line descriptions, to indicate areas of interest for developers to work on

**Comment by wfernandes** [comment]
Also labels have a description field, so we could use that to add more detail about the feature for added clarification.

**Comment by michaelgugino** [comment]
Maybe create a github project board?

Having a high-level list of features and some links to some things that are todo or in progress would be helpful too.

I'm not very opinionated on the process, but whatever helps new contributors easily find and pickup issues is my suggestion.

**Comment by ncdc** [comment]
> whatever helps new contributors easily find and pickup issues is my suggestion.

I 100% agree that we need a healthy backlog of easy/medium/hard tasks, but I view that as a separate concern from having a feature roadmap.

**Comment by wfernandes** [comment]
> whatever helps new contributors easily find and pickup issues

I think the project roadmap can help getting contributors partly there. As a new contributor it would've been nice to know where to dedicate my efforts to help add value towards a project epic instead of working on random things that might get re-vamped/refactored anyways.

**Comment by pires** [comment]
+1 for clear roadmap through github project.

**Comment by vincepri** [comment]
Project boards are hard to manage without a person dedicated to putting things in place, and automation setup to follow the project's patterns.

A markdown document is easy to manage, can be placed in the book for easy find, and anyone can look at it or open PR to modify things.

**Comment by ncdc** [comment]
It sounds like the answer to my original question is "yes". As we discussed in the office hours meeting today, here is a rough draft of some possible roadmap items: https://docs.google.com/document/d/1vHsqlz7TPnxglA-1f-G-JXAeCJ1Rkji4FDyy8Hf3JFQ/edit#. Please take a look! After folks have had a chance to review and edit/comment, we can turn this into a markdown file and maintain it in the repo.
