### ISSUE TITLE
RFE: Post create apply thunk of YAML

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/cluster-api#1910]
**User Story**

As a user/operator I would like to apply the same set CNI/StorageClasses/etc to a cluster after it has been created.  

**Detailed Description**

Because this is such a common operation, I would like to use a simple facility that gives me a mechanism but doesn't force a change to the data model and would allow us to change over time if we find a better way.  

One pattern we could use: 

- Admins determine the a set of post creation YAML that they would like to apply to clusters, and upload that to a configmap. 
- When an admins create a new cluster object they add a POSTCREATEAPPLY=locationtoconfigmap LABEL.  
- Once the cluster has been created a controller simply applies the thunk in a fire-and-forget manner.  
- By default this is an opt in feature so it's a NO-OP if the label doesn't exist. 

**Anything else you would like to add:**
Any failures that occur are the admins shoulders and not a responsibility of clusterapi.  The only responsibility on clusterapi would be to surface errors that may occur on apply.  e.g.- badly formatted YAML. 

/kind feature

**Comment by vincepri** [comment]
How about having a ConfigMap or Secret with files in it attached to a cluster?

**Comment by akutz** [comment]
Hey @timothysc, did you mean to assign me to this issue? Unless this is related to the no-op annotation I've socialized, I've not been involved in this conversation up till this point.

**Comment by timothysc** [comment]
> How about having a ConfigMap or Secret reference in Cluster.Spec instead of a label/annotation? 

I'm ok with a ConfigMap reference.  

>  I've not been involved in this conversation up till this point. 

Consider yourself involved now ;-)

**Comment by ncdc** [comment]
Long term, I can see Cluster API having direct support (in the API) for the work the addons WG is doing.

**Comment by timothysc** [comment]
This is super generic, not necessarily addon specific.  It could be blanket thunk folks want to apply.

**Comment by akutz** [comment]
>  The only responsibility on clusterapi would be to surface errors that may occur on apply. e.g.- badly formatted YAML.

Any bad data could be rejected in an admissions webhook anyway.

**Comment by akutz** [comment]
Hi @timothysc / @vincepri / @ncdc / @fabriziopandini,

I spoke with a new member of my team, @sedefsavas, and she's interested in working on this. I think this may be a good first issue for an experienced engineer to become acquainted with CAPI and Kubernetes. Sedef and I walked through some psuedo-implementations of what this might look like:

```golang
// Reconcile ensures the back-end state reflects the Kubernetes resource state intent.
func (r machineReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr error) {

	// Get the Cluster resource for this request.
	obj := &infrav1.Cluster{}
	if err := r.Client.Get(r, req.NamespacedName, vsphereMachine); err != nil {
		if apierrors.IsNotFound(err) {
			r.Logger.Info("Cluster not found, won't reconcile", "key", req.NamespacedName)
			return reconcile.Result{}, nil
		}
		return reconcile.Result{}, err
	}

	// 1. Does Cluster have annotation "cluster.x-k8s.io/addons-config-map"? 
	// This label points to a config map of add-ons to be applied to
	// the target cluster.
	// 
	// 2. Get the config map. If it exists, proceed with step three.
	//
	// 3. Get a controller-runtime client for the target cluster.
	//
	// 4. Range over the config map's key/value pairs, applying each value
	//    as YAML to the target cluster.

	// Step 2
	addonsConfigMap := &corev1.ConfigMap{}
	addonsConfigMapKey := apitypes.NamespacedName{
		Namespace: addonsConfigMapNamespace,
		Name:      addonsConfigMapName,
	}
	if err := ctx.Client.Get(ctx, addonsConfigMapKey, addonsConfigMap); err != nil {
		if apierrors.IsNotFound(err) {
			return reconcile.Result{}, nil
		}
		return reconcile.Result{}, err
	}

	// Step 3 - Get client for target cluster.
	targetClusterClient := GetClusterClient(cluster)
	
	// Step 4 - Apply add-ons to target cluster.
	for addonName, addonYAML := range labelConfigMap.Data {
		// Apply each add-on to the target cluster.
	}
}
```

I wanted to make sure everyone is fine with Sedef working on this as a first-issue in CAPI. I told her if there are any reservations that I would spend time pair-programming it with her so she could still use this as a learning opportunity.

Thanks!

**Comment by ncdc** [comment]
👍

**Comment by vincepri** [comment]
The pseudo-code looks reasonable, few notes:

- Let's add a new field to `Cluster.Spec` instead of the annotation/label, something like `Cluster.Spec.AddonsSecretName`, which can be a simple string.
- The secret should be patched with a label back to the cluster, if it doesn't have it.
- The secret should be patched with an OwnerReference back to the cluster, if it doesn't have it.
- We need to define an annotation for the secret so we know when it has already been applied, maybe a timestamp?

**Comment by akutz** [comment]
> We need to define an annotation for the secret so we know when it has already been applied, maybe a timestamp?

Do we? If the resource has already been applied then it's a no-op. I'm fine with the apply occurring during each reconcile.

> Let's add a new field to Cluster.Spec instead of the annotation/label, something like Cluster.Spec.AddonsSecretName, which can be a simple string.

Sure, this was pseudo-code.

Also, was there a decision on using a secret? I don't know that one is required, and I almost think it's worth having different data sources for when data may be privileged enough to warrant a secret.

**Comment by akutz** [comment]
> The secret should be patched with an OwnerReference back to the cluster, if it doesn't have it.

Should it? Delete semantics would catch it if this occurs, wouldn't they? Perhaps operators want the data object to be long-lived, beyond the lifetime of one or more `Cluster` resources? I'm thinking of cases where people seed the management server in advance and not want the data resource to be deleted if all `Cluster` resources that make use of it are also deleted.

**Comment by vincepri** [comment]
> Also, was there a decision on using a secret? I don't know that one is required, and I almost think it's worth having different data sources for when data may be privileged enough to warrant a secret.

Either a Secret or a ConfigMap, either one is fine. Given the precedent with bootstrap data moving to a secret, I'd make this a secret as well given that folks might want to install sensitive data.

> Should it? Delete semantics would catch it if this occurs, wouldn't they? Perhaps operators want the data object to be long-lived, beyond the lifetime of one or more Cluster resources? I'm thinking of cases where people seed the management server in advance and not want the data resource to be deleted if all Cluster resources that make use of it are also deleted.

You can add more than one OwnerReference pointing to a Cluster, the trick here is that when doing pivoting we need to list all the resources mapped to a cluster. This wouldn't work with a single label, but we can have multiple ownerRefs.

> Do we? If the resource has already been applied then it's a no-op. I'm fine with the apply occurring during each reconcile.

Depending on the use case, we might either want to re-apply on each reconcile, or do a one-shot. @timothysc, any preferences?

**Comment by akutz** [comment]
> Let's add a new field to Cluster.Spec instead of the annotation/label, something like Cluster.Spec.AddonsSecretName, which can be a simple string.

If people are okay with updating the `ClusterSpec`, then I'd propose something like this:

```golang
type ClusterSpec struct {
	// Addons is a list of object references that point to ConfigMaps
	// with YAML to be applied to guest clusters.
	Addons []corev1.ObjectReference

	// Addons is a list of object references that point to Secrets
	// with YAML to be applied to guest clusters.
	PrivilegedAddons []corev1.ObjectReference
}
```

**Comment by timothysc** [comment]
Addons is really overloaded, we may want to choose a different name.

**Comment by akutz** [comment]
> Either a Secret or a ConfigMap, either one is fine. Given the precedent with bootstrap data moving to a secret, I'd make this a secret as well given that folks might want to install sensitive data.

This is because the very first iteration of the bootstrap data included certificate keys. If it wasn't for that, I doubt the change would have occurred.

> You can add more than one OwnerReference pointing to a Cluster, the trick here is that when doing pivoting we need to list all the resources mapped to a cluster. This wouldn't work with a single label, but we can have multiple ownerRefs.

That puts the onus on the operator to create an anchor owner ref for the original resource to keep the GC from removing the resource when all cluster resources are deleted.

> Depending on the use case, we might either want to re-apply on each reconcile, or do a one-shot. @timothysc, any preferences?

FWIW, this approach is used heavily elsewhere and is more in-line with reconciliation logic IMO. I don't like fields that indicate state as such fields can grow stale. Unless we reconcile the status of the applied YAML with the actual state, isn't it easier to apply each time to avoid that issue?

**Comment by akutz** [comment]
> Addons is really overloaded, we may want to choose a different name.

**Comment by vijaykatam** [comment]
My thinking is label approach makes the post config loosely coupled with cluster spec and the desired config can be realized by potentially controllers outside cluster-api if that is what we trying to introduce here.

**Comment by akutz** [comment]
Hi @vincepri / @timothysc,

I also want to keep Sedef from having to be **too** concerned with the more pedantic aspects of changes like this (at least for a first issue), so I hope no one minds if I try to guide her to a first iteration (WiP) PR and then let a lot of the discussion occur there.

**Comment by vincepri** [comment]
> My thinking is label approach makes the post config loosely coupled with cluster spec and the desired config can be realized by potentially controllers outside cluster-api if that is what we trying to introduce here.

Controllers watching clusters should be able to do the same with a mapping function.

> I also want to keep Sedef from having to be too concerned with the more pedantic aspects of changes like this (at least for a first issue), so I hope no one minds if I try to guide her to a first iteration (WiP) PR and then let a lot of the discussion occur there.

:+1:

**Comment by akutz** [comment]
Hi @vijaykatam,

> My thinking is label approach makes the post config loosely coupled with cluster spec and the desired config can be realized by potentially controllers outside cluster-api if that is what we trying to introduce here.

That's fair, but it's also the case that it's easy to PoC this outside of CAPI as well, such as in an infra-provider or a new repo altogether. I've also wanted to use CAPI as the starting point for ideas that may have Kuberentes-wide appeal, but I've found it's not always the best place to do these proofs of concept because of the desire (and a correct one) to keep things tied to CAPI when possible.

**Comment by akutz** [comment]
Hi @sedefsavas,

I forgot, I cannot assign you because you're not yet a member of the K8s or K8s SIG org. After time and contributions we'll be able to sponsor you. And by the way, contributions aren't limited to just code. It can mean community involvement, answering questions on Slack/in GitHub/mailing list. Or just moderating issues. There is a lot one can do to help support Kubernetes.

**Comment by akutz** [comment]
@timothysc, since you changed the title, I'm totally going to request the `Apply` method be called `ChunkAThunk` as in "chunk this thunk over and hope it lands" :)

**Comment by akutz** [comment]
@vincepri pinged me about whether to support a single or multiple data sources. Vince likes a single data source for simplicity's sake. I agree with the simplicity, but I'm also thinking of associated multiple, disparate services with a `Cluster`. Services that may be managed or owned by different sets of operators (people, not controllers). Imagine the following workflow:

1. Deploy management cluster

2. Three different business units have IT staff apply resources that contain YAML to chunk onto deployed guest clusters, ex:
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: authentication-service-roles
      namespace: default
    type: Opaque
    ```

    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: logging-service-config
      namespace: default
    type: Opaque
    ```

    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: platform-credentials
      namespace: default
    type: Opaque
    ```

3. A guest cluster is deployed with the following YAML:
    ```yaml
    apiVersion: cluster.x-k8s.io/v1alpha3
    kind: Cluster
    metadata:
    name: my-cluster
    namespace: default
    spec:
      thunksToChunk: # copyright TSCorp, 2019
      - apiVersion: v1
        kind: Secret
        namespace: default
        name: authentication-service-roles
      - apiVersion: v1
        kind: Secret
        namespace: default
        name: logging-service-config
      - apiVersion: v1
        kind: Secret
        namespace: default
        name: platform-credentials
    ```

While a single data source would be simpler, due to the likelihood of the real-world use case of multiple groups owning different services, I would rather support multiple data sources to align with this use case.

Thoughts?

**Comment by ncdc** [comment]
There is also a 1.5MB limit per item in etcd to keep in mind. +1 to multiple

**Comment by vincepri** [comment]
As mentioned, I'm fine with a list as long we deal with a single object type, this reduced the likelihood of issues down the line.

**Comment by akutz** [comment]
Thanks Vince. That’s why I used Secret in the most recent example. We could simplify that example then by making it a list of NamespacedName instead of an ObjectRef. The implied Kind would be Secret.

**Comment by zjs** [comment]
What behavior would be expected when a cluster is upgraded? (Does post-creation YAML get re-applied? Is there a separate post-upgrade YAML? Is there no ability to apply similar YAML after an upgrade?)

**Comment by timothysc** [comment]
> What behavior would be expected when a cluster is upgraded? (Does post-creation YAML get re-applied? Is there a separate post-upgrade YAML? Is there no ability to apply similar YAML after an upgrade?) 

I would expect not, b/c it's only applied post creation.  Async mgmt of policy(CNI, etc) doesn't not need to be tied to a cluster lifecycle events, and could be updated via a one-liner b/c.

**Comment by timothysc** [comment]
It's possible we might want to declare specific thunks to certain operations. 

- creation 
- upgrade 

I think I'd call it `PostApply`

**Comment by joonas** [comment]
Just checked in with @sedefsavas, she'll be working on this

**Comment by sedefsavas** [comment]
There are a couple of ways of getting the yaml data from the secret: 
1. Defining a particular key to place the yaml content.
2. Concatenating the secret's data content and create the yaml.
Which makes more sense?

Also, applying the same yaml at each reconcile may overwrite the resources that already being changed in the cluster. Instead of applying each time, how about applying only if the objects in the yaml do not exist? If this is overcomplicated, we can go with adding a timestamp label after applying.

**Comment by fabriziopandini** [comment]
I'm looping back on the Secret vs ConfigMap discussion.
If we are going to use Secrets that means that the addons yaml will be an encoded string, and this makes it difficult to customize it eg. the variables substitution pattern (`cat template.yaml | envsubst | kubectl apply -f -`).
Also clusterctl adopts the same pattern, and even if this can be managed in golang, it adds more complexity. Can we reconsider using ConfigMaps instead of secrets?

**Comment by ncdc** [comment]
@fabriziopandini if you have a secret in yaml format, you can use the `stringData` field and `envsubst` should work with that, shouldn't it?

**Comment by fabriziopandini** [comment]
@ncdc I guess this can work! Somehow I forgot about string data 😊

**Comment by jdef** [comment]
There's seemingly related addons work being proposed for kubeadm: https://github.com/kubernetes/kubernetes/pull/85224

**Comment by dlipovetsky** [comment]
I think the use case is not controversial.

I see the proposal changes the `Cluster` type. That's a major data model change, and I think it's contrary to what the original request asks:

> I would like to use a simple facility that gives me a mechanism but _doesn't force a change to the data model_ and would allow us to change over time if we find a better way.

Is there an alternative to changing the `Cluster` type?

**Comment by detiber** [comment]
> Is there an alternative to changing the Cluster type?

The solution was steered towards data model changes, because the proposed changes (labels/annotations/etc) where creating an informal API. Using these as an informal API is fine for prototypes and experiments, but as we fold those prototypes and experiments into the project proper, we should make sure to formalize the API semantics with real fields vs the informal API.

**Comment by dlipovetsky** [comment]
> we should make sure to formalize the API semantics with real fields vs the informal API.

Agreed.

Is there a reason not to define a new type, e.g. `ThunksToThunk`:tm:, that references a Cluster by name, and write a controller that applies the thunks once the referenced Cluster's control plane is ready?

That gives us a real CAPI type to experiment with, but avoids the cost of changing the `Cluster` type now, and potentially a second time if the experiment doesn't work out well.

**Comment by ncdc** [comment]
@dlipovetsky as discussed in today's office hours meeting: add a "contrib" or "experimental" package in the repo, define API type(s) + controller(s) in there (i.e. don't modify `Cluster`), and expose enabling it with a flag. This enables experimentation and we can promote experiments to proper `api` types over time, assuming consensus.

**Comment by dlipovetsky** [comment]
I want to add that, whatever comments I have about the design, I'm grateful that we're doing this experiment, and to @sedefsavas for her implementation!

**Comment by sedefsavas** [comment]
@timothysc Can you please close this issue? I summarized whatever we have here in the this [RFE](https://github.com/kubernetes-sigs/cluster-api/issues/2395)
