### ISSUE TITLE
[e2eframework] allow generators to set manager flags

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2041]
**User Story**
We don't need to test leader election on every test and disabling leader election and metrics endpoint removes (at least on my machine) about 10 seconds of time from the whole run.

**Detailed Description**
I would like the [generators](https://github.com/kubernetes-sigs/cluster-api/tree/master/test/framework/generators) to somehow modify the kustomize they generate to do things like disable leader election, set the metrics port to 0 and modify concurrency of the manger.

**Anything else you would like to add:**

/kind feature
/help
/good-first-issue

I am happy to help guide anyone willing to take this on.

**Comment by chuckha** [comment]
I think the API I want is to be able to customize this struct: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/generators/capi.go#L35. It is used by providers, here is one such example: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/e2e/docker_suite_test.go#L95

I think it makes sense to add a field to this struct that disables leader election. Eventually I'd want to be able to customize more of the manager flags, but until we really need to customize them, I don't think we should add that functionality yet. That is why I suggest adding a field specifically for disabling leader election.

The code does some manipulation of the YAML already: https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/generators/capi.go#L67

But basically we need to delete https://github.com/kubernetes-sigs/cluster-api/blob/master/config/core/manager_auth_proxy_patch.yaml#L25 this flag if it's found in on the manager's pod. Alternatively we could set `--enable-leader-election=false` which should have the same effect. I don't really care which way we do it, so long as it's managed by a field in the ClusterAPI generator struct.

This should be extended to all the generators, save the cert-manager, found in this directory: https://github.com/kubernetes-sigs/cluster-api/tree/master/test/framework/generators

**Comment by chuckha** [comment]
@hypnoglow will be working on this!

/active

**Comment by chuckha** [comment]
whoops

/lifecycle active

**Comment by hypnoglow** [comment]
> @hypnoglow will be working on this!

/assign

**Comment by akutz** [comment]
Hi @chuckha / @hypnoglow,

I would be careful on how this is implemented. Rather how the information is transported from input to execution. 

I originally configured CAPV's tests to use a series of flags. After you did the split-up of the controller managers, I quickly realized how much overhead there is to configure e2e with flags or env vars. That's why https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/727 switched things to a config file. 

I made a note in that PR that I did not intend to reproduce Kustomize, but given that it recently created a distinct API library and CLI, I wonder if it's worth implementing a post-process step to the YAML via Kustomize's API library. Still, it's a lot of overhead to do this.

And it's also very prescriptive. If done for the Kubeadm Bootsrapper, it does nothing to assist, for example, Talos. I think it's important to make the e2e framework work across all pluggable parts of CAPI, not just the default pieces.

**Comment by chuckha** [comment]
@akutz are you planning to PR the e2e config work you've done in the linked PR? I think that would be a great starting place for the framework to manage services

**Comment by akutz** [comment]
Sí. I’ll try and get the PR open by EOD. It’s been open in VSCode since Tuesday. Things keep getting in the way.

**Comment by akutz** [comment]
Hi @chuckha,

https://github.com/kubernetes-sigs/cluster-api/issues/2041 is now open and ready for review. Thank you for your patience.

**Comment by vincepri** [comment]
@chuckha @hypnoglow what's the status of this issue? can it be closed?

**Comment by hypnoglow** [comment]
Probably this is obsolete, as I think https://github.com/kubernetes-sigs/cluster-api/pull/2144 resolved the issue.

**Comment by fabriziopandini** [comment]
+1 to close. 
every change to manifest should go through clusterctl, otherwise, we are introducing skew between UX and E2E test.

**Comment by vincepri** [comment]
Closing, thank you!

/close
