### ISSUE TITLE
Fix state diagram for control plane controller

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api#2143]
**What steps did you take and what happened:**
In the state diagram for the control plane controller (https://master.cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html) we have **Control plane is contactable** and both the arrows have **no**. 

One of them should be a **yes**

/kind bug
/kind documentation

**Comment by wfernandes** [comment]
I also noticed a couple of things as well. 
1. In our code we only update `Status.ReadyReplicas` and not `Status.Ready`. I deployed KubeadmControlPlane and noticed the following
    ```
    $ kubectl describe kubeadmcontrolplanes
    ...
    Status:
      Initialized:     true
      Ready Replicas:  1
      Replicas:        1
      Selector:        cluster.x-k8s.io/cluster-name=test-cluster,cluster.x-k8s.io/control-plane=
    ...
    ```
1. Also in the above, I noticed that `Status.Selector` has an empty value for `cluster.x-k8s.io/control-plane=`

If these are valid, I can open separate issues.

**Comment by detiber** [comment]
@wfernandes for your first question, I opted not to set `Status.Ready` yet, since we do not have health checks in place to make that determination, yet. It is something that we will need for release, though.

For the second question, the empty value should be fine for the `cluster.x-k8s.io/control-plane` label, We only care about the existence of the key rather than any particular value.
