### ISSUE TITLE
Unable to provision inception cluster following Quick-Start guide

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/cluster-api#2341]
**What steps did you take and what happened:**
* Attempted to bring up a cluster using the Docker CAPI provider as documented here https://master.cluster-api.sigs.k8s.io/user/quick-start.html. 
* I eventually got to the step where I was creating a single-node inception cluster here https://master.cluster-api.sigs.k8s.io/user/quick-start.html#usage.  The machine never got created and got stuck:
```
NAME                             PROVIDERID   PHASE
capi-quickstart-controlplane-0                provisioning
```

Looking in the Docker CAPD controller pod log, I saw:

```
E0214 15:28:48.929749       1 machine.go:145] controllers/DockerMachine/DockerMachine-controller "msg"="capd@docker$ mkdir -p /etc/kubernetes/pki\n" "error"="failed to create directory: exit status 1" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-controlplane-0"} "machine"="capi-quickstart-controlplane-0"
```

Here is a snapshot of all deployed pods:

```
NAMESPACE            NAME                                               READY   STATUS    RESTARTS   AGE
cabpk-system         cabpk-controller-manager-c58d8596f-cwszc           2/2     Running   13         23h
capd-system          capd-controller-manager-7cd8c765c-gpf8f            2/2     Running   29         23h
capi-system          capi-controller-manager-6c64c695bb-6xbm5           1/1     Running   23         23h
cert-manager         cert-manager-69b4f77ffc-kz6j2                      1/1     Running   4          23h
cert-manager         cert-manager-cainjector-576978ffc8-x6m45           1/1     Running   30         23h
cert-manager         cert-manager-webhook-c67fbc858-jkgk7               1/1     Running   0          23h
kube-system          coredns-6955765f44-l4d2d                           1/1     Running   0          23h
kube-system          coredns-6955765f44-sgfnr                           1/1     Running   0          23h
kube-system          etcd-clusterapi-control-plane                      1/1     Running   0          23h
kube-system          kindnet-xxcxh                                      1/1     Running   20         23h
kube-system          kube-apiserver-clusterapi-control-plane            1/1     Running   17         23h
kube-system          kube-controller-manager-clusterapi-control-plane   1/1     Running   12         23h
kube-system          kube-proxy-hcwmk                                   1/1     Running   0          23h
kube-system          kube-scheduler-clusterapi-control-plane            1/1     Running   12         23h
local-path-storage   local-path-provisioner-7745554f7f-5hxv6            1/1     Running   22         23h
```
**What did you expect to happen:**
A deployed work-load cluster deployed using the Docker provider.

**Environment:**

- Cluster-api version: `v0.2.9`
- Minikube/KIND version: kind version `v0.7.0`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): `darwin/amd64` `OSX 10.15.3`

/kind bug

**Comment by prankul88** [comment]
@vladimirvivien Hi, that's probably due to the fact that the [#usage](https://master.cluster-api.sigs.k8s.io/user/quick-start.html#usage) section has objects corresponding to v1Alpha3 and the management cluster runs v1Alpha2 controllers.

The book for master has not been updated for v1Alpha3 controllers. I too got confused earlier #2028

**Comment by prankul88** [comment]
@vladimirvivien I see that [Management cluster setup](https://master.cluster-api.sigs.k8s.io/user/quick-start.html#setup-management-cluster) guide has been updated to v1Alpha3. You can probably check now. Thanks

**Comment by vladimirvivien** [comment]
@prankul88 thanks.

**Comment by vincepri** [comment]
/priority awaiting-more-evidence

@vladimirvivien Was the issue fixed?

**Comment by vladimirvivien** [comment]
@vincepri haven't had time to check again, I have been using CAPv.  If I have time this week, I will try with v1a3.

**Comment by ginobiliwang** [comment]
Hi guys, i have encountered the same issue.

`I0504 04:58:52.650093       1 loadbalancer.go:120] controllers/DockerMachine/DockerMachine-controller "level"=0 "msg"="Updating load balancer configuration" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-controlplane-0"} "machine"="capi-quickstart-controlplane-0"
I0504 04:58:53.717248       1 machine.go:142] controllers/DockerMachine/DockerMachine-controller "level"=0 "msg"="Running machine bootstrap scripts" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-controlplane-0"} "machine"="capi-quickstart-controlplane-0"
E0504 04:58:53.765240       1 machine.go:145] controllers/DockerMachine/DockerMachine-controller "msg"="capd@docker$ mkdir -p /etc/kubernetes/pki\n" "error"="failed to create directory: exit status 1" "cluster"="capi-quickstart" "docker-cluster"="capi-quickstart" "docker-machine"={"Namespace":"default","Name":"capi-quickstart-controlplane-0"} "machine"="capi-quickstart-controlplane-0"
E0504 04:58:53.765460       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to exec DockerMachine bootstrap: failed to join a control plane node with kubeadm: failed to create directory: exit status 1"  "controller"="dockermachine" "request"={"Namespace":"default","Name":"capi-quickstart-controlplane-0"}`

wondering how to fix it.

**Comment by fabriziopandini** [comment]
@ginobiliwang it will be great if you can help us to reproduce this error because I'm not able to do so locally nor I can see similar errors in  the CI jobs that are using CAPD 😓

**Comment by vincepri** [comment]
> "failed to create directory: exit status 1"

@ginobiliwang This error is a little suspect, it seems that when running CAPD on your machine, the bootstrap data generated isn't able to run properly, this might be an issue with your local development environment

**Comment by fabriziopandini** [comment]
I managed to reproduce 

> "msg"="capd@docker$ mkdir -p /etc/kubernetes/pki\n" "error"="failed to create directory: exit status 1"

Fix in flight

**Comment by ginobiliwang** [comment]
thanks @fabriziopandini @vincepri for comments. 
I deleted accordingly deployments and tried again, the issue is gone. 
But i have met further issues as below. The issue prevents me from correctly deploying master node and worker node, could you please shed some light on it, thanks.

`[root@sdw1 config]# kubectl get machine
NAME                             PROVIDERID                                                  PHASE
capi-quickstart-controlplane-0   docker:////capi-quickstart-capi-quickstart-controlplane-0   provisioned`

`Status:
  Bootstrap Ready:       true
  Infrastructure Ready:  true
  Phase:                 provisioned
Events:
  Type     Reason            Age                  From                Message
  ----     ------            ----                 ----                -------
  Warning  FailedSetNodeRef  12s (x8 over 3m49s)  machine-controller  Get https://172.17.0.2:6443/api/v1/nodes: dial tcp 172.17.0.2:6443: i/o timeout
[root@sdw1 config]#`


Also, if i continue to deploy worker node, worker node will stop at "pending"  phase.
With log information from 
`kubectl logs -f capi-controller-manager-74895dbbb8-9g6ts  -c manager -n capi-system`
 showed this error as well.

`E0505 14:19:59.996239       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="Get https://172.17.0.2:6443/api/v1/nodes: dial tcp 172.17.0.2:6443: i/o timeout"  "controller"="machine" "request"={"Namespace":"default","Name":"capi-quickstart-controlplane-0"}`



i could reproduce this issue with version cluster-api version 0.3.0 and some early versions.

**Comment by fabriziopandini** [comment]
@ginobiliwang 
Is it possible to move the new problem on a different issue, so we can properly track the original problem and its fix

**Comment by vladimirvivien** [comment]
I am closing this issue.  I was able to get CAPD following documentation update here -https://notes.elmiko.dev/2020/04/17/exploring-cluster-api.html

**Comment by ginobiliwang** [comment]
> @ginobiliwang
> Is it possible to move the new problem on a different issue, so we can properly track the original problem and its fix

no problem
