### ISSUE TITLE
[kubeadm control plane] something is weird when upgrading from 1.16 to 1.17

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2427]
Using #2334 as a base, when I upgrade from 1.16 to 1.17 there is something going on in either: the load balancer is not behaving properly and causing the kubelet to fail or the kubelet is failing for some other reason. Right now I have a few error messages about CSI that's putting the kubelet in a crash loop. I need to debug further to pinpoint what's going on. But the general code in #2334 is one-by-one replacing my nodes and having them join successfully.

/kind bug

**Comment by detiber** [comment]
I encountered a similar issue when testing a 1.16 -> 1.17 upgrade using the aws provider. However, since we no longer deploy a bastion by default and the IAM role assigned to the host does not yet allow Session Manager, I was not able to verify the same error in the kubelet logs. However all kubelets where tainted with `node.kubernetes.io/unreachable:NoExecute` following the upgrade.
