### ISSUE TITLE
Update clusterctl create when machines objects have a provisioning indication

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes-sigs/cluster-api#253]
Seeing a node in the machine status cannot be purely relied upon because the provisioned master may not be registering with the stack that provisions it.

**Comment by davidewatson** [comment]
I originally thought it would be possible to reuse the `Node` condition `KubeletReady` to indicate a `Machine` had been created, but now I am not so sure. One problem is this coupling is not trivial when the corresponding `Machine` is in a different cluster than the `Node`.

When we were working on our ssh provisioner, we had to ssh from the manager cluster (where our controllers run) to the managed master in order to generate the `kubeadm` token. This was only necessary when we did not pivot. I think individual providers will have to do something similar if they choose to allow Cluster API resources to exist outside of the cluster they manage.

Will have to think more about this.

**Comment by davidewatson** [comment]
Propose we leave this as is for v1alpha1.

**Comment by ncdc** [comment]
I'm not entirely clear on what this issue is about. Could someone please clarify? Thank you!

**Comment by davidewatson** [comment]
A `Ready` "status" is only one of the states we need to expose for Bootstrapping. Therefore we'll close this and handle this there.

/close
