### ISSUE TITLE
KCP: validate version changes are no further than one minor version

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api#2578]
**User Story**

As an operator, I would like to get immediate feedback when I try to ask the KCP to perform a multi-version upgrade.

**Detailed Description**

Pulling this out of #2489: if a KCP is pointing to version 1.16.x, it should reject updates that ask to upgrade the control plane directly to 1.18.x.

**Anything else you would like to add:**

I'm not sure what the semantics should be around downgrades – do we deny those outright?

/kind feature

**Comment by detiber** [comment]
> I'm not sure what the semantics should be around downgrades – do we deny those outright?

I think blocking downgrades outright is the safe bet. That said, we probably need to look into providing a rollback path for partially completed upgrades.

**Comment by nwoodmsft** [comment]
I was also trying a similar scenario (1.16->1.18) without realizing that it is not supported to skip a minor version in the current upgrade flow. Any plans to support skipping minor versions or is this intentional and something that is likely to remain for the foreseeable future?

Also, Is there a section of the book or similar where I can read about CAPI requirements such as this? It would be great for new comers to have this documented along with any other gotchas (e.g. I also just learned that k8s 1.16 is a min requirement for v1alpha3).

**Comment by detiber** [comment]
> I was also trying a similar scenario (1.16->1.18) without realizing that it is not supported to skip a minor version in the current upgrade flow. Any plans to support skipping minor versions or is this intentional and something that is likely to remain for the foreseeable future?

It's likely to remain for as long as it's a limitation of Kubernetes/kubeadm.
