### ISSUE TITLE
[clusterctl] log when using overrides for clusterctl

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#2713]
When using overrides, clusterctl should log a warning/info message. Right now it's very easy for someone switching back and forth between dev and user to forget to remove overrides and deploy a cluster the wrong controller-manager image.

**Comment by CecileRobertMichon** [comment]
current log https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/repository/components_client.go#L74

Maybe it should be a warning?

**Comment by prankul88** [comment]
@camilamacedo86 We can just remove the Verbosity part and just log the info rather than setting `-v 0` right?

**Comment by camilamacedo86** [comment]
HI @prankul88, 

It shows correct, however, I never contribute with this project.

**Comment by prankul88** [comment]
@camilamacedo86 Sorry I tagged you by mistake.

**Comment by CecileRobertMichon** [comment]
@prankul88 correct, I think just removing the `v(1)` should work since it's v 0 by default

**Comment by fabriziopandini** [comment]
Unfortunately, this can cause problems to ./bin/clusterctl config provider --infrastructure aws -o yaml, because this is going to prepend logs to the yaml (same for other commands ruturning yaml)

```
Using Override="infrastructure-components.yaml" Provider="infrastructure-aws" Version="v0.5.0"
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
...
```

So as per https://github.com/kubernetes-sigs/cluster-api/pull/2717#issuecomment-607518818, before implementing this, we should explore different solutions like log to stderr in case of commands generating yaml output (this is what kubectl does)

**Comment by prankul88** [comment]
@CecileRobertMichon Can we close this?

**Comment by CecileRobertMichon** [comment]
@prankul88 was it fixed? It looks like your PR got closed
