### ISSUE TITLE
KCP etcd client robustness

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2789]
In the current codebase, the etcd client is created from a single node https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/etcd_client_generator.go#L35. 

To improve robustness, and always make sure to have a client to the current etcd leader, we should instead take the whole list of control plane machines and make sure to always return a client to the current leader instead.

/kind cleanup
/area control-plane
/milestone v0.3.x

**Comment by detiber** [comment]
@vincepri if robustness is the goal, would it be better to generate the client with all known endpoints and set a short `AutoSyncInterval` on the Config?

We should also be able to use the [WithRequireLeader](https://godoc.org/go.etcd.io/etcd/clientv3#WithRequireLeader) context to ensure that requests go through to the leader regardless of the original endpoints as well.

**Comment by vincepri** [comment]
That sounds good to me as well, was trying to do it in smaller steps

**Comment by benmoss** [comment]
Usages of `forNode`:

- https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L172
This code is when we are removing a node from the cluster, and is called immediately after `ForwardEtcdLeadership`, so seems safe to switch it to use the master rather than talking to just a random "other" node as it is right now
- https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L240
This code is when we are testing etcd cluster health, we loop through each node and test that it can call the `Members` API, so it seems like we want to keep this as is
- https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L528
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L545
This is where we're moving etcd leadership, we connect to the candidate and test that it can call `Members` and then connect to the current leader and call `MoveLeader`

So it seems like only one usage can be replaced here, unless you had larger changes in mind

**Comment by detiber** [comment]
> - https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L172
This code is when we are removing a node from the cluster, and is called immediately after ForwardEtcdLeadership, so seems safe to switch it to use the master rather than talking to just a random "other" node as it is right now
> - https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L240
This code is when we are testing etcd cluster health, we loop through each node and test that it can call the Members API, so it seems like we want to keep this as is

Agree that we should not change this to avoid testing member health against the wrong target.

> - https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L528
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster.go#L545
This is where we're moving etcd leadership, we connect to the candidate and test that it can call Members and then connect to the current leader and call MoveLeader

Looking at the [code](https://github.com/etcd-io/etcd/blob/3ac7a1151519af0816647d5f0757119c3f4a24ac/etcdserver/server.go#L1261-L1292) that does the leader moving, I think etcd already has quite a few different checks in place that we could likely avoid switching clients in favor of using `WithRequireLeader` for doing the leadership move.
