### ISSUE TITLE
Update coredns in kubeadm-config configmap from clusterconfiguration before Scaling Control plane

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#2885]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Steps I took
Tried upgrading control plane using custom AMI with baked etcd and coredns container images
1. Create AWSMachineTemplate with new AMI
2. Edited Kubeadcontrolplane spec with new machinetemplate under infrastructureTemplate
    and updated cluster configuration with new coredns and etcd image details.
3. Updated kuberentes version under kubeadmconfigspec

What happened:
new control plane failed in cloudinit kubeadm pre flight step, when kubeadm tried downloading images. This is because coredns in kubeadm-config was not updated before control plane scaling.

**What did you expect to happen:*
I expected the a new control plane to be created. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I think we should update the coredns version when updating configmap.
https://github.com/kubernetes-sigs/cluster-api/blob/867b2afed0e6a4509a74bb123b7c6f2ab0f7ffd7/controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go#L356

We can update the coredns deployment at the end the way we do it now.
**Environment:**

- Cluster-api version: kubeadm-control-plane-controller:v0.3.2
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug

**Comment by ncdc** [comment]
@vincepri @detiber @benmoss

**Comment by detiber** [comment]
I'm not necessarily sure we should update CoreDNS in the kubeadm ConfigMap prior to adding a new control plane Machine, since the Deployment is still pointing at the old image at that point.

**Comment by ncdc** [comment]
After `kubeadm init`, the value in the ConfigMap is only used during the ImagePull preflight check when new control plane nodes join the cluster. (It would be used during `kubeadm upgrade`, but we're not using that.)

The change proposed in this issue allows upgrades to succeed if the original CoreDNS used during `kubeadm init` was baked into the OS image but **is not pullable**. If both the original and new CoreDNS images are pullable, this change is not strictly necessary.

Do you think there is any specific harm in making this change?

**Comment by detiber** [comment]
I don't necessarily know that there is specific harm in making the change, but it does result in drift between the state of things. That in itself is probably fine as long as we don't currently (or accidentally in the future) rely on the value of the configmap rather than the Deployment. Another potential gotcha would be if Kubeadm ever introduces a change to Join that would be affected by the drift in the configmap vs the deployed Deployment.

**Comment by vincepri** [comment]
/milestone v0.3.x
/priority awaiting-more-evidence

@fabriziopandini do you have any thoughts around this issue?

**Comment by neolit123** [comment]
i see a question here related to who's responsibility it is to pull the container images for a new node?
the user building the VM image or kubeadm running `join` on the node?
if it's kubeadm's responsibility then this feels like chopping away from the whole "immutability" concept for a machine.

for immutable upgrades it makes sense to me to skip kubeadm prepull completely and assume the VM was prepared with the required container images even if both version Y and Y-1 of addon X have to be baked-in.

@DheerajSShetty 

> new control plane failed in cloudinit kubeadm pre flight step, when kubeadm tried downloading images.

it fails because it tries to pull image that does not exist or fails because the node is air-gapped?

**Comment by ncdc** [comment]
@neolit123 it fails to pull because the original node used an OS image that had all the images baked in **AND** those images are **NOT** pullable

**Comment by DheerajSShetty** [comment]
@neolit123 
It tries to pull coredns Y-1 in AMI with version Y.

**Comment by fabriziopandini** [comment]
@DheerajSShetty @vincepri @ncdc 
Might be I'm wrong, but I think that the problem is a little bit more complex.

Assuming we change the version in the kubeadm config map before upgrades, we can the new control-plane to join the cluster. That's fine (and I don't see particular problems in doing this).

But if the images are not pullable, there could be another problem, because the new image will be available only on the new AMIs, while all the old AMIs have the old core DNS version.

CoreDNS Addons is a Deployment with 2 replicas and with the following tolerations:
```
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```

That means that whenever one replica should be replaced, AFAIK there are no guarantees that the new pod is created on the new AMI vs Being created on old AMIs - both control plane or workers -.
If both the 2 replicas with the new versions gets moved to old AMIs, the DNS in the cluster is busted.

Long term, a possible solution for environments without a local image repository is the introduction of "versioned" CoreDNS deployments (and a versioned kube-proxy daemon set). But this requires some design.

**Comment by DheerajSShetty** [comment]
I have been working around this issue by changing repository field of CoreDNS Deployment before upgrade to someplace where it can be downloaded from.
But in v1alpha3, KCP changes the deployment image and repo to value in kubeadm-config, and hence the approach I used in v1alpha2 did not work.
Hence for now I have stopped using baked container images in AMI.

As you mentioned using air-gapped coredns needs a design change

**Comment by DheerajSShetty** [comment]
@fabriziopandini 
Based on the existing workflow in KCP, any old cluster which has used baked AMI cannot be upgraded using KCP. We have made the changes to use container images that are pullable. But old clusters still need the kubeadm config map to be changed in upgradeControlPlane() along with UpdateImageRepositoryInKubeadmConfigMap() and UpdateEtcdVersionInKubeadmConfigMap()

**Comment by ncdc** [comment]
@DheerajSShetty would it be feasible for you to manually modify the kubeadm-config ConfigMap to set the images to pullable specs before starting the KCP upgrade? This would be a one-time operation to allow the first upgrade to succeed.

**Comment by DheerajSShetty** [comment]
Wont it be better if image changes happen in a single controller, so that an Upgrade logic is straightforward for CAPI users. With existing v1alpha3 the only ask would be making sure new k8s version container images are pullable.

But if you feel it is unnecessary we can make changes on our side.

**Comment by ncdc** [comment]
I am proposing that you do the manual modifications because this is only a problem for air-gapped environments where the container images baked into the operating system images have bogus pull specs / are not pullable. WDYT @detiber?

**Comment by detiber** [comment]
I think there are rough edge cases no matter how we try to approach this, and if we have a known workaround that can be used for the migration we should probably try to stick to that rather than try and make this work in the more generalized use case.

For example, which image urls are we expecting to configure in the kubeadm config map, it seems like we'd need to feed in the urls for the versions needed prior to the upgrade rather than the versions needed post-upgrade. Unless we are talking about also upgrading the coredns first, which *might* be okay, but is definitely not a scenario that is being tested upstream.

**Comment by DheerajSShetty** [comment]
Ok. We will make changes on our side.
