### ISSUE TITLE
MachineSet is looking at the wrong annotation for Machine deletion

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#2912]
**What steps did you take and what happened:**
Apply the documented annotation to a Machine that belongs to a MachineSet to select it for deletion (`cluster.x-k8s.io/delete-machine`) and then scale down the MachineSet. The MachineSet will not honor the documented annotation.

**What did you expect to happen:**
The MachineSet honor the documented annotation

**Anything else you would like to add:**
The MachineSet code is looking for [cluster.k8s.io/delete-machine](https://github.com/kubernetes-sigs/cluster-api/blob/48729fd1380e982d840ebfd08accdaa3e2193bb6/controllers/machineset_delete_policy.go#L36) for the annotation instead of the documented [cluster.x-k8s.io/delete-machine](https://github.com/kubernetes-sigs/cluster-api/blob/b814473efb54448a9eff22051f3b4e3416c83834/api/v1alpha3/machineset_types.go#L89)

It looks like at a minimum, the [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/150bf34748496eb0ae70a2951e540f1556e81650/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go#L28-L29) is relying on the current behavior as well, so we might need to fix this with backwards compatibility in mind.

/kind bug

**Comment by ncdc** [comment]
Let's add code in 0.3.x to support both versions, and in 0.4.x only respect the x-k8s version?

**Comment by vincepri** [comment]
/milestone v0.3.4
/priority important-soon

@wfernandes did you want to try to tackle this issue?

**Comment by wfernandes** [comment]
So posing one of [the hardest problems in CS](https://martinfowler.com/bliki/TwoHardThings.html). 

If the existing annotation `cluster.k8s.io/delete-machine` is called `DeleteNodeAnnotation` what do we call the other one `cluster.x-k8s.io/delete-machine`?

Suggestions:
- `DeleteNodexAnnotation`
- `DeleteNodeAnnotationv2`
- This might not be API compatible, but change the value of `DeleteNodeAnnotation=cluster.x-k8s.io/delete-machine` and put the older one in a variable called `DeprecatedDeleteNodeAnnotation=cluster.k8s.io/delete-machine` or something we don't care since we are planning on removing it in v0.4.x.
