### ISSUE TITLE
KCP should shut down kube-apiserver gracefully

### ISSUE THREAD

**Issue by benmoss** [kubernetes-sigs/cluster-api#2937]
**User Story**

As an operator I would like to my Kubernetes cluster not to become unavailable as nodes are being removed from my cluster.

**Detailed Description**

When a node is being removed right now, whether due to scale down or upgrade, users can potentially see errors while trying to reach the cluster. At least in my testing using CAPA I believe this is because the load balancer for control plane nodes cannot react quickly enough to one of the nodes being shut down, and so will still send traffic to that machine until its health check fails.

There is a feature on the apiserver that can help solve this problem, `--shutdown-delay-duration`. It means that when SIGINT/SIGTERM are received by the apiserver process, it will start returning non-200 response codes on the `/readyz` endpoint while still accepting connections. This can let the LB's healthcheck have enough time to respond to the imminent shutdown to remove that node while ideally not interrupting any existing connections.

This will require us to signal the apiserver process, which is made more difficult by the fact that it's running as a static pod. It will automatically be restarted if it exits. One solution could be to remove the static pod from `/etc/kubernetes/manifests`, which will stop the kubelet from managing the apiserver pod. Another solution could just be to give a very large `--shutdown-delay-duration`, such that shutting down the whole machine is more-or-less guaranteed to happen before the pod actually exits and restarts.

**Anything else you would like to add:**

`--shutdown-delay-duration` had a bug such that it didn't actually do what it was intended to do until v1.18.0 https://github.com/kubernetes/kubernetes/pull/88911

We currently have a similar issue with the etcd static pod going into a crash loop after we remove the node's etcd membership. Building the ability to stop these static pods might be a nice feature for etcd as well.

Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1689

/kind feature

**Comment by vincepri** [comment]
cc @sethp-nr

**Comment by sethp-nr** [comment]
Thanks for writing this up, Ben! 

> I believe this is because the load balancer for control plane nodes cannot react quickly enough to one of the nodes being shut down, and so will still send traffic to that machine until its health check fails.

That certainly doesn't help, though what we saw in https://github.com/kubernetes-sigs/cluster-api/issues/2652 was that the api-server seemed "healthy" in that it never got taken out of the load balancer, even when the KCP got stuck between the remove member and shut down node steps. It appeared to be accepting requests & hanging on to them, waiting for its local etcd server (the only one it knew about) to come back. The "connection failure" or EOF errors were actually better for us, because clients retried more or less immediately instead of drastically changing the latency distribution.

> This will require us to signal the apiserver process, which is made more difficult by the fact that it's running as a static pod. It will automatically be restarted if it exits.

I haven't dug into whether this would work with the static pods yet, but something we've done prior with non-static pods is an optional configmap volume coupled with an init container as a durable signaling mechanism. Something like `grep stopping /etc/configmap-volume/signal-file && exit 1` might allow a useful best-effort channel. That said, as it is best-effort, a long timeout and some controller requeue logic to re-TERM the apiserver at approximately the right time would improve matters too.

> --shutdown-delay-duration had a bug such that it didn't actually do what it was intended to do until v1.18.0 kubernetes/kubernetes#88911

Oof. Still, changing the unavailability characteristic from fail-slow to fail-stop by terminating the API server in versions prior to v1.18.0 has value too, I think.

**Comment by detiber** [comment]
I worry a bit about how implementation of this would work. Would we need some changes in Kubeadm to support this, or if we tried to implement outside of kubeadm, would we have to worry about compatibility of our solution with specific versions of kubeadm/kubernetes?

Another potential option that we have is to change the order of operations for scaling down/deletion of a Machine with KubeadmControlPlane. Instead of deleting the etcd membership before Machine deletion, we could do it afterwards. This should mean that the health checks will fail for the apiserver (from being shutdown) prior to etcd membership changing on the host. With the changes we have to health checking to reconcile etcd membership, this should theoretically have the same convergence behavior. We might need to requeue operations until the Machine (or at least the provider-specific *Machine) resource has been deleted successfully prior to doing the health check again to ensure that the shutdown is successful prior to modifying the etcd membership, though.

I do like the idea of using the /healthz endpoint for health checks. It's definitely something that we should try to do, however not all load balancer implementations support http checks against a TCP load balancer, which is the main reason that we do not use it for cluster-api-provider-aws currently. We could switch to using an NLB rather than an ELB classic to gain that support, however we would have to solve an issue related to hairpinning in order to adopt it.

**Comment by ncdc** [comment]
Another thing related to this area: if we were to add the proposed MachineLoadBalancer types, we presumably could have KCP orchestrate removing control plane machines from the load balancer, wait for quiescence, and then delete the machine. That would help, wouldn't it?

**Comment by sethp-nr** [comment]
Ah, that would be a nice alternative to the `--shutdown-delay-duration` & timeouts & signaling long road to the same destination 😆

**Comment by vincepri** [comment]
Just throwing an idea out there, could we make this an optional improvement in each infrastructure provider that's currently managing ELBs directly?

As in, let's say a Machine is unhealthy or is being deleted, the InfraCluster controllers today should be able to detect that and quickly remove the Machine from the load balancer list of Machines available.

**Comment by ncdc** [comment]
Yes, that is a good idea. Looking at CAPA as an example, I don't believe we're currently doing that.

**Comment by sethp-nr** [comment]
I wonder what the signaling mechanism should be. The health-check-and-timeout-based interface seems both hard to implement and hard to consume (e.g. ELBs not supporting HTTP-based health checks on TCP load balancers).

That said, either "deleting" or ill health is a bit late if we're going for graceful, as removing the target will race with the shutdown on the api-server side. The health-check-and-timeout interface provides at least `timeout` seconds of advance notice, which is a property that would be nice to preserve IMO.

**Comment by vincepri** [comment]
> I wonder what the signaling mechanism should be

We could soon use MachineHealthCheck ability to annotate unhealthy machines to detect failures early. CAPA for example can get this notification as well, and when reconciling the load balancer endpoints, could detach the unhealthy instance from the ELB.

**Comment by sethp-nr** [comment]
Right, and I think that's probably a good idea (it can potentially make cascading failures much more fun, but such is the healthy / not healthy dance). It's a solution to a slightly different problem than "how do we give advance notice that we are about to intentionally make an unhealthy control plane node?"

Maybe the answer is we don't, but that's the question I think this issue is asking.

**Comment by vincepri** [comment]
That makes sense, I was more proposing these as an additional solution to improve the situation in v0.3.x — I'll open issues in the infrastructure providers when we have the bits though and not hijack this discussion.

**Comment by vincepri** [comment]
If/when we'll be able to pursue #1250, we should be able to remove a control plane member from the load balancer

**Comment by vincepri** [comment]
Closing this in favor of #1250
