### ISSUE TITLE
DockerMachineTemplate is not immutable.

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2949]
**What steps did you take and what happened:**
In [KubeadmControlPlane section](https://cluster-api.sigs.k8s.io/tasks/kubeadm-control-plane.html?highlight=rolling#upgrading-the-control-plane-machines) in the book, it is stated that recreating machine template is required for upgrade:
```
Since MachineTemplate resources are immutable, the recommended approach is to

```

I can update DockerMachineTemplate.

/kind bug

**Comment by vincepri** [comment]
This is definitely strange, let's fix that up!

/milestone v0.3.4
/help

**Comment by detiber** [comment]
Is this an issue against KubeadmControlPlane or against cluster-api-provider-vsphere, which isn't enforcing that VSphereMachineTemplate is immutable?

It seems to me that KubeadmControlPlane is operating as expected here by detecting the `Spec.Version` change, but not the change to the VSphereMachineTemplate.

**Comment by sethp-nr** [comment]
What Jason's describing matches my understanding: providers SHOULD make their templates immutable, because CAPI will treat them as such by not inspecting them to see if they've changed.

We have gotten ourselves out of a pickle at least once by temporarily turning off immutability (by deleting the webhook config), making a change, and then causing the KCP into doing an upgrade, as you describe, but that certainly felt like an "at our own risk" activity to us and not something CAPI supported.

**Comment by yastij** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/636 should solve this for CAPV

**Comment by yastij** [comment]
closing this as dupe

/close

**Comment by sedefsavas** [comment]
Reopening this for CAPD. There is not much to change in a DockerMachineTemplate as only docker.sock is in the template.

**Comment by fabriziopandini** [comment]
This requires getting web-hooks in places for CAPD...

**Comment by sedefsavas** [comment]
Will Docker provider webhook be a separate deployment as the rest of the providers? Or can we bundle it together with manager?

cc @fabriziopandini 

/assign

**Comment by sedefsavas** [comment]
Since docker provider does not have conversion webhooks, no need to have a separate deployment for the webhook. So will add the webhook to the docker controller manager.

**Comment by fabriziopandini** [comment]
@sedefsavas 
Is there a problem to get docker provider similar to other providers?

Then i'm not sure that the choice to manage web-hooks in a specific way for the docker provider will simplify your task, because e.g. clusterctl assumes all the provider to follow the same contract for yaml files (see https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#refactor-kustomize-config-folder-to-support-multi-tenancy-when-using-webhooks).
Having the docker provider not compliant might lead to some problem when using clusterctl from command lines or in the e2e test.

Also, having a different setup in the config folder is something we should take care specifically during every future change...

**Comment by vincepri** [comment]
@fabriziopandini CAPD doesn't need multi-tenancy or conversion webhooks, I'm fine having the validation/defaulting webhooks live in the same controller for now, it doesn't really matter where they live and they could always be moved later on.
