### ISSUE TITLE
[e2e] test framework helpers should return error (and not panic)

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2955]
**User Story**

As a developer I would like to compose test framework helpers for defining new higher level-helpers

**Detailed Description**

As of today test framework helpers are designed following the pattern2 defined [here](http://onsi.github.io/ginkgo/#global-shared-behaviors), which assumes any helper should implement assertions inside its code.

This is ok for simple helpers, like `CreateCluster` or `WaitForClusterProvisined`, but considering that now we are starting to combine simple helpers into higher level-helpers like `CreateClusterAndWait` this approach is showing some limits because if there is an error after creating the cluster, the helper panics without returning the reference to the newly created cluster object.

This can lead to an incomplete cleanup of the resources created during the test (or generalizing, you can't implement your own error management in higher level-helpers).

Please note that this issue is not a problem in CI, where the final cleanup is ensured by other means (e.g. boskos in test infra), but it can be annoying when running tests locally.

**Anything else you would like to add:**
As per comment https://github.com/kubernetes-sigs/cluster-api/issues/2306#issuecomment-617002275, by removing asserting from the helpers, we can easily support also usage of the test framework outside of ginkgo/gomega based tests.

/kind feature
/area testing

**Comment by fabriziopandini** [comment]
I'm going to implement a workaround in test/e2e to force delete all the clusters at the end of tests, but this should be removed as soon as a proper solution is in place

**Comment by detiber** [comment]
+1 for this, I think the assertions in the common helpers also makes the errors in resulting tests more difficult to decipher as well, since the assertion calls out helper code that is not under your control (in the case of out-of-tree providers) requiring a user to dig deeper into the stack trace to figure out where in their test code the error occurred.

**Comment by detiber** [comment]
Even when used within ginkgo and outside of cleanup, there are some issues being hit with the current approach where helpers are making assertions.

For example: https://github.com/kubernetes-sigs/cluster-api/blob/cdf2905db3c60cbc3fa6bd3b8d92877f64b3b164/test/framework/machinehealthcheck_helpers.go#L155, it states that is avoiding Expect() because it may return an error during machine deletion, however, one of the calls in the chain (GetClient()), does have an Expect statement in there, that can cause an assertion error to occur.

I hit this with cluster-api-provider-packet, because we currently implement HA control planes using an EIP, which can take a short amount of time to migrate. So, if the control plane machine that is being remediated happens to be the one with the EIP attached, then the GetClient() call can fail, which causes the entire test to fail.

I've found a way to work around this, by basically creating a wrapper around the ClusterProxy implementation provided by the framework, but it would be nice if there was a cleaner way to handle this using the upstream ClusterProxy.

**Comment by sbueringer** [comment]
@detiber @fabriziopandini I think we could fix Jason's concrete issue by adding an eventually around: https://github.com/kubernetes-sigs/cluster-api/blob/cdf2905db3c60cbc3fa6bd3b8d92877f64b3b164/test/framework/cluster_proxy.go#L170-L171

I'm not sure if we still want to do the overall refactoring as those would be breaking changes across the board.

I think a refactoring of the entire test framework currently doesn't have enough priority and based on the comments on the current issue it doesn't seem to be a very pressing issue for consumers of the test framework.

@fabriziopandini @detiber WDYT?

**Comment by fabriziopandini** [comment]
When I originally played around this problem I was thinking to move current implementation in framework/v1 and then add framework/v2 returning errors, but I agree this is a lot of work (even if kind of mechanical)
However, if adding some small changes helps, I'm not opposed to it.

**Comment by vincepri** [comment]
/close

During the Feb 11th backlog grooming meeting we've discussed about this issue a bit more, folks have outlined pros/cons of the approach and in general it seems that it'd require refactoring the entire framework for little benefit for most users. If there are specific errors or assertions that we should return through the call stack, we can consider them on a case by case basis.
