### ISSUE TITLE
cert-manager should probably tolerate masters

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api#3033]
**What steps did you take and what happened:**
Control planes consisting of only masters cannot deploy cert-manager because cert-manager does not tolerate masters.

**What did you expect to happen:**
cert-manager deployed properly

**Anything else you would like to add:**
Probably need to add 
```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```
to the cert-manager stuff.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/kind area/cert-manager

**Comment by fabriziopandini** [comment]
@voor are you referring to single-node clusters?
(because single node control plane usually has some workers, so this should not be a problem)

In kubeadm, we are documenting to remove node-role.kubernetes.io/master from single-node clusters, and this why e.g. a single-node kind cluster can be used a temporary management cluster 

Is it possible to do the same in your use case (single-node cluster are not really a master, and also they are intrinsically temporary due to lack of HA). If not, could you provide some more details about your use case?

**Comment by voor** [comment]
Yes, single node cluster not single control plane.

**Comment by kfox1111** [comment]
I could totally see using the cluster api on a 3 node raspberry pi cluster with only 3 masters. In this configuration, cert-manager should tolerate being on masters?

**Comment by wfernandes** [comment]
I think I understand the use case.

So you have a management cluster with just a single node that is the master node (that is, it has the label `node-role.kubernetes.io/master: ""`) and it has a taint `NoSchedule`. 
And the ask is to be able to install CAPI management components onto that single master node.

I see that the other CAPI components have the toleration specified in their manifests.
https://github.com/kubernetes-sigs/cluster-api/blob/bfa499083ba3c316b647d9c211baf4453a2cc1db/config/manager/manager.yaml#L39-L41

I guess we didn't run into this because by default the single node kind cluster created from `kind create cluster` doesn't have that taint. 
I was able to reproduce the fact that on a single node kind cluster with the taint, we are **unable** to do `clusterctl init` since the cert-manager pods aren't being scheduled on it.

@fabriziopandini Until we decide to remove the `node-role.kubernetes.io/master` from a single node master, we should probably be consistent with the tolerations in cert-manager and CAPI components.

**Comment by fabriziopandini** [comment]
@wfernandes I'm interested in understanding the use case because IMO he Idaa of having a single node management cluster supported by Cluster API goes far and behind the cert manager toleration.
E.g. when kcp does upgrades AFAIK we are not doing drain. Should we implement this?
E.g should we have test coverage for single node control plane?

**Comment by voor** [comment]
Yes, my use case actually aligns with the 3 node master cluster mentioned earlier, since if I scale all of my CAPI components to 3 and only run master nodes, I effectively have a very small footprint health check capability for my clusters that is itself highly available.

**Comment by wfernandes** [comment]
Makes sense. I guess the stuff I mentioned above also holds true for a multi-master cluster with no worker nodes.

**Comment by vincepri** [comment]
Do we allow CAPI controllers to run on control plane nodes? If not, we should document the worker node as a minimum requirement

**Comment by voor** [comment]
> Do we allow CAPI controllers to run on control plane nodes? If not, we should document the worker node as a minimum requirement

Currently CAPA and CAPV tolerate masters, but CAPZ does not. @CecileRobertMichon maybe we should figure out some consistency there, too.

**Comment by wfernandes** [comment]
> Do we allow CAPI controllers to run on control plane nodes? If not, we should document the worker node as a minimum requirement

@vincepri I believe the CAPI components have the tolerations to be scheduled onto the master. 
https://github.com/kubernetes-sigs/cluster-api/blob/bfa499083ba3c316b647d9c211baf4453a2cc1db/config/manager/manager.yaml#L39-L41

However, they need cert-manager for the webhook components to run. Right now, if you do `clusterctl init -v5`, it will hang on `Waiting for cert-manager to be available...`.

**Comment by vincepri** [comment]
If we do, then we +1 to be consistent / make it as a requirement for providers as well & add the tolerations to cert-manager, which is a required dependency

**Comment by fabriziopandini** [comment]
ok, it seems there is consensus on the use case (3 CP without worker nodes), so I'm +1
