### ISSUE TITLE
Allow URL() method of Provider interface to return empty string

### ISSUE THREAD

**Issue by teoyaomiqui** [kubernetes-sigs/cluster-api#3067]
**User Story**

As a user of clusterctl (as a library, not as a binary). We found it to be inconvenient for us, to hold all the provider component repositories in the specified directory structure, as we have our own ways to store kubernetes resource documents, we wanted to use clusterctl on top of this our data interface, which in turn is built on top of kustomize.

So thanks to great flexibility of clusterctl, we have implemented our own repository interface, which you can find [here](https://github.com/airshipit/airshipctl/blob/master/pkg/clusterctl/implementations/repository.go) and we inject it into the clusterctl config/client without any issues.

However in our implementation we have to make up dummy URL for the provider interface in [here](https://github.com/airshipit/airshipctl/blob/master/pkg/clusterctl/client/client.go#L87).

**Detailed Description**

Provider.URL() method real use is only in [implementation of repository interfaces](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/repository/client.go#L142), that are currently present in clusterctl. However repository interface has really nothing to do with URL, it simply must return versions and components.

And in our implementation we do not need this URL at all, i think there may be many more implmentations in future that will not need URL either. So i would suggest to remove URL() validation everywhere, but where it is actually needed, like in [repositoryFactory function](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/repository/client.go#L140-L166), and in [repository implementations](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/repository/repository_local.go#L139-L143) as well.

I am not sure, that it will be a great benefit, however i thought that feedback from developer building something on top of clusterctl and cluster-api this can be theoretically valuable. 

Cheers!

Environment:

Cluster-api version: v0.3.5
Kubernetes version: (use kubectl version): v1.18.1

/kind feature
/area clusterctl
/area ux

**Comment by vincepri** [comment]
@fabriziopandini Do you have any opinions here? What could be the implications to allow this use case to be taken into account?

/milestone Next

**Comment by fabriziopandini** [comment]
@teoyaomiqui I'm happy to know you appreciate clusterctl flexibility.

I'm trying to understand your use case, however there is one thing I disagree on your analysis:

> However repository interface has really nothing to do with URL

This is not true, on the contrary, the goal of the repository data structure is to provide the location (the URL) for a provider so 

a. clusterctl can fetch and assemble all the required providers
b. the user can add new providers (not included in the default list)
c.  the user can change the location of existing providers, e.g. for air-gapped environments

And given that this is crucial for clusterctl, it is legit to validate that all the providers have a valid URL as soon as clusterctl access his own config.

> we wanted to use clusterctl on top of this our data interface

if I look at your implementation it seems to me that the same concept of provider location described above exists also for you, because your custom repository type takes in input the root path of your directory structure and then uses it to get access to your own ways to store Kubernetes resource documents.
https://github.com/airshipit/airshipctl/blob/8f75fbdb8ca448ef6aee4247a6f22454dac64d69/pkg/clusterctl/implementations/repository.go#L112 
https://github.com/airshipit/airshipctl/blob/8f75fbdb8ca448ef6aee4247a6f22454dac64d69/pkg/clusterctl/implementations/repository.go#L82

So IMO, this can be addressed by setting the URL to the above root path instead of leaving it empty. 

Please note that if using a path is not enough for you and you need more flexibility, you can eventually introduce your own schema for better expressing your own ways to store Kubernetes resource documents, e.g. airship://my-own-root..., and make your custom repository implementation to process it

**Comment by fabriziopandini** [comment]
/close
Due to lack of updates
Feel free to re-open if necessary
