### ISSUE TITLE
Use URLs for CNI definition in e2e framework

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api#3117]
**User Story**

As a developer, I would like to specify CNI manifest as a URL in order to avoid duplicating the manifest in e2e tests

**Detailed Description**
The CNI path for e2e tests is currently expected to be on disk and gets applied after [reading the file](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/framework/clusterctl/clusterctl_helpers.go#L152). Request is to support URLs to fetch CNI templates.

cc @fabriziopandini 

/kind feature
/area testing

**Comment by fabriziopandini** [comment]
I'm personally convinced we should avoid test e2e to have external dependencies for several reasons, above all reduce flakes due to network problems/availability of the source.
cert-manager/quay.io is a notable example of this.

Said that, if we want to implement this, we should rely on the same mechanism that already manages the same problem for reading provider manifests

**Comment by gab-satchi** [comment]
/close 
closing in favour of #3292
