### ISSUE TITLE
KCP upgrade is triggered by CAPI minor version update

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3170]
**What steps did you take and what happened:**

- With cluster api v0.3.2, create a cluster with single control plane machine.
- Upgrade cluster api to v0.3.5
- Rolling upgrade started for the control plane machine.

**What did you expect to happen:**
No machine upgrades are initiated by minor version CAPI upgrades.

The same behaviour is observed in an HA control plane by @rudoi 

/kind bug

**Comment by vincepri** [comment]
@sedefsavas are you working on this?

/milestone v0.3.x

**Comment by randomvariable** [comment]
0.3.3 triggers the change in https://github.com/kubernetes-sigs/cluster-api/commit/dcd3d51881552722234c3443d9d597f5e5c3db98#diff-f30ad9aecb671548155d73c5840fe19bR88

The mdutil.Hash func uses Spew to spit out a string serialisation of the object and then hashes it. The addition of `UseExperimentalRetryJoin` to the API caused the hash to change.

Number of options:

1. No additions to kubeadmconfig or KCP spec allowed within a version - pretty strong requirement.
2. Serialize the spec onto the object, and then do semantic comparisons?
3. Something else?

**Comment by wjun** [comment]
I applied the latest kubeadm-bootstrap-controller and kubeadm-control-plane-controller images to the management cluster during velero backup and restore, but still triggered KCP upgrade with logs as:
I0617 13:12:58.613527       1 controller.go:261] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="cool" "kubeadmControlPlane"="cool-control-plane" "namespace"="default" 

The new created control plane node has a different hash code(kubeadm.controlplane.cluster.x-k8s.io/hash: "2478258161") from the original one(kubeadm.controlplane.cluster.x-k8s.io/hash: "2502614424").
The upgrade should avoid during velero backup/restore, otherwise, it will create a new control plane node. Currently, it blocks the velero backup/restore management cluster test.

**Comment by vincepri** [comment]
@wjun Thanks for the report, @sedefsavas is actively working on this issue, we'll have a fix in v0.3.7 (due in a couple of weeks)
