### ISSUE TITLE
clusterctl init will force a name change of ClusterRole and ClusterRoleBinding

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#3272]
**What steps did you take and what happened:**

Specified `ClusterRoles` and `ClusterRoleBinding` were modified by clusterctl after init. 

During the installation, clusterctl adds the instance namespace prefix to  `ClusterRoles` and `ClusterRoleBinding`, and so it can rely on that for deleting only the global resources belonging the the provider instance being deleted:
https://github.com/kubernetes-sigs/cluster-api/blob/e874a89c47d4cdf9e14fda545a5765db77cf24f2/cmd/clusterctl/client/repository/components.go#L405

For high-level tools that utilize clusterctl, this forced name change can cause inconsistencies. In particular, if the high-level tool is already following the naming convention, then cluserctl will blindly prepend the taget-namespace once again. 

**What did you expect to happen:**

clusterctl could first check if the object already follows the desired naming convention (i.e. "namespace-foo"), if so, avoid renaming the object. Today, func fixRBAC blindly prepends target-namespace to the original name of the objects in question. 

**Anything else you would like to add:**
The `ClusterRole` and `ClusterRoleBinding` are part of the component config which are generated from the `config/rbac` directory in the repos of various components (core, kcp, infra, etc.). I suppose, the naming convention could also be applied at that level, but would be required across all supported providers, so isn't an ideal solution. 

- Cluster-api version: master

/kind bug
/area clusterctl

**Comment by fabriziopandini** [comment]
I'm not sure I got this right, but I don't think that we should implement the change described above/support this use case.
 
Let's assume that the author set's the ClusterRole name to `myprovider-system-foo` instead of `foo`.

If we are installing the provider to the `myprovider-system` namespace, without the change you will get `myprovider-system-myprovider-system-foo`, with the proposed change you will get `myprovider-system-foo`

But clusterctl allows the users to specify a different target namespace, e.g. `another-namespace`, and in that case your cluster role will be named `another-namespace-myprovider-system-foo` which is weird.

So, unless I'm missing something, I will simply stick to the current recommendation for the components yaml authors to name ClusterRoles and ClusterRoleBinding without a namespace prefix (`foo` in the example above), and let clusterctl to add the target namespace as a prefix

**Comment by vincepri** [comment]
Is this documented somewhere?

**Comment by fabriziopandini** [comment]
@vincepri it is documented here https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#components-yaml-transformations

**Comment by Arvinderpal** [comment]
Yes, target namespace makes this tricky. I will close. Thank you
