### ISSUE TITLE
Allow DockerMachineTemplate to be mutable

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#3338]
**User Story**

As a developer/user I would like to update the custom image (`DockerMachineSpec.CustomeImage`) in my `DockerMachineTemplate` to enable reliable upgrades in KinD. 

**Detailed Description**

KinD has very specific image requirements for its Nodes (see https://github.com/kubernetes-sigs/kind/releases). In particular, specific {images,tags,digest} must be used for a given Kubernetes version. Failing to do this results in unpredictable behavior. 

When upgrading Kubernetes, the `DockerMachineSpec.CustomeImage` must be updated prior to the upgrade. For example, here we update customImage field to the appropriate value for v1.17.0:
```		
kc get dockermachinetemplate -n=default test-control-plane -o json | jq '.spec.template.spec.customImage="kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62"' | kubectl apply -f-
```

CAPD does not currently allow mutations on `DockerMachineTemplate`.  Alternative is to create a brand new template and patch KCP/MD accordingly (see https://cluster-api.sigs.k8s.io/tasks/upgrade.html), however, this is more complicated and there has already been some consensus on loosening  the immutable requirement on infra templates: https://github.com/kubernetes-sigs/cluster-api/issues/3283

/kind feature

**Comment by vincepri** [comment]
@Arvinderpal Thanks for filing this issue, I've briefly looked at the related PR, is CAPD capable of changing any fields on the template dynamically?

#3283 should be tackled at some point to explain a little better the requirements, while Infrastructure providers can decide to make a template mutable, they have to be able to reconcile the changes on each Machine when a template gets updated. As far as I can see, there is no support for that today in CAPD.

**Comment by fabriziopandini** [comment]
Might be I'm missing something, but if you leave the custom image field empty, CAPD will pick up the official kindest image for a kubernetes version (if available on the docker hub); FYI this is the approach we are using in E2E tests.

WRT to the problem of mutability,  IMO all the possible changes to the template require a machine rollout (`CustomImage`, `PreLoadImages`, `ExtraMounts`) while IMO there are fields that should not be allowed to change (`ProviderID` and `Bootstrapped`).

However, I have some concerns about what is the expected behavior when mutability is enabled:
- currently, CAPD does not implement logic to trigger rollout in case of those changes; most important I'm not sure CAPD can technically trigger a rollout given that the machines are controlleìd by KCP/MD
- KCP/MD are already triggering rollout if the reference to the infrastructure template is changed (this implies to create a new template, so mutability is not required)
- `CustomImage` is a tricky field, because it requires to sync the changes on the infrastructure template with the changes on the Kubernetes version field on KCP/MD. 

Might be we should consider a different approach for the `CustomImage` problem, by evolving this field into in something similar to https://github.com/kubernetes-sigs/cluster-api/blob/65dc85f404ecf940d2beaa76d7a1038cb011d9db/cmd/clusterctl/client/config/imagemeta_client.go#L100 so we can keep this value immutable and delegate to CAPD the responsibility to add the right version tag

**Comment by Arvinderpal** [comment]
> #3283 should be tackled at some point to explain a little better the requirements, while Infrastructure providers can decide to make a template mutable, they have to be able to reconcile the changes on each Machine when a template gets updated. As far as I can see, there is no support for that today in CAPD.

The two providers that I'm familiar with capd and metal3 do not contain any template specific reconcile logic. The machine templates exists solely for consumption by KCP/MD when creating new control-plane/worker machines. For example, today, if we allow the above mutation to `DockerMachineTemplate`, and the user modifies `customImage`, then that change has no immediate impact; it is only when the user tries to say scale replicas or change K version, do the new Machines pickup the change to `customImage`. Machines based of the old template may continue to exist. 

I suppose your question is more along the lines of: if we allow `DockerMachineTemplate` to be mutated, shouldn't we then update all machines that were created from this template? 
One option is to not do anything and let the user decide. For example, if the user wants to update all machines, then with KCP, the `updateAfter` field can be utilized to trigger an update and perhaps there is something similar for MD as well.
However, if we make this a hard requirement (for all providers), then further investigation would be required.

**Comment by Arvinderpal** [comment]
It was mentioned during the July 15th office hours that mutations would only be supported for **in place** upgrades. Feel free to close this issue. If we ever revisit the immutable requirement, we can revisit this.
