### ISSUE TITLE
Force a regeneration of kubeconfig of a workload cluster

### ISSUE THREAD

**Issue by farodin91** [kubernetes-sigs/cluster-api#3348]
**User Story**

As an operator I would like to replace the current kubeconfig by a new one for mainly as  security concerns such as the kubeconfig got leaked.

**Detailed Description**

As I understood the code, currently kuebconfigs are regenerate after a defined lifespan. It would be help to have a command in the Clusterctl to trigger the regeneration at any point for a defined workload cluster.

/kind feature

**Comment by detiber** [comment]
I believe this should already be possible by deleting the existing kubeconfig secret.

That said, since we do not have any support today for rotating secrets and Kubernetes doesn't have support for certificate revocation, a leaked kubeconfig using a client certificate would still be valid even if it was replaced.

**Comment by vincepri** [comment]
Closing for lack of updates

/close
