### ISSUE TITLE
Deprecate RequeueAfterError, and remove its usage

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3370]
**What steps did you take and what happened:**
`RequeueAfterError` is often used in reconciliation loops to signal the reconciler that we want to requeue after a certain amount of time. This paradigm can be found throughout the Cluster API and providers codebase.

While today RequeueAfterError works fine, there is a lot of drawbacks that are unaccounted for:
- Errors are shadowed, won't be logged unless explicit.
- Callers have to check the type of the error and if it matches `RequeueAfterError`, then return the actual `reconcile.Result{}`.

In alternative, we should opt for most functions that are returning a `RequeueAfterError` to instead have `(reconcile.Result, error)` in their method/function signature. This way, when a reconciler loop calls into a function it gives complete responsibility to the other code to check.

A possible helper method is being proposed in controller-runtime to help check if the reconcile.Result is empty or not, see https://github.com/kubernetes-sigs/controller-runtime/pull/1059

/kind cleanup
/milestone v0.3.x
/priority important-soon

**Comment by benmoss** [comment]
I think there's an alternate solution to all this that I prefer, which is to use error types and then have a way of mapping error types to requeue logic. This keeps our business logic at the level of the domain, rather than letting the controller logic bleed into everything. It's the same issue as when you're writing an HTTP server you don't have your database library return HTTP status codes.

**Comment by ncdc** [comment]
@benmoss do you have some examples? I assume you're suggesting something other than a `RequeueAfterError`?

**Comment by benmoss** [comment]
I think because we have 99% of our logic in controllers this isn't as big of an issue, or rather it's a sub-issue of that issue, but yeah you can use errors as values and do something like

```go
var ErrResourcePaused error

...
if err.Is(ErrResourcedPaused) {
    return ctrl.Result{RequeueAfter: pausedRequeueAfter}, nil
}
```

**Comment by vincepri** [comment]
The above example looks fine, although it doesn't solve the issue that the caller has to always check if the error returned is of some specific kind, and that's not too far from what it was before. 

While having `(ctrl.Result, error)` everywhere might be a little verbose, the flow of operation is readable and explicit, which is the purpose of moving in this direction.

**Comment by benmoss** [comment]
Yeah, there's a trade-off of explicitness for sure, I think I'd advocate for a mapping layer that'd add some extra complexity but at the benefit having stratified layers of logic with APIs that make sense for that layer rather than every layer having the burden of "knowing" that it is causing/recommending a reconciler requeue. Like I said earlier though we mostly just have one layer (controllers) and so this isn't as valid a complaint. I think I would like to see more layers split out and then maybe this becomes more salient.

**Comment by detiber** [comment]
+1 to what @benmoss is saying. I think delegating handling of `ctrl.Result` is fine for the common use case we have today of passing logic to more targeted "reconcilation" functions/methods that are associated with the high level reconciliation of the resource.

However, if we need to add some context to a failing request deeper down into some "service" specific code (the code interacting directly with AWS resources for example) or library helpers (kubernetes-sigs/cluster-api/util for example), then it would make more sense to expose that information in a way that is less coupled to `ctrl.Result`. 

I also agree with Ben that we should likely start thinking about ways to better structure our code in more discrete layers/components that can more easily be tested and verified independently. This would allow us to better leverage unit-style tests for correctness and reduce the amount of e2e style tests needed, with the e2es able to focus more on behaviors and interactions vs correctness of implementation details. As an added benefit of this, we could more easily leverage modifications to the e2e tests to highlight potential breakage of contracts we are defining, where currently it is more difficult because they also include a lot of implementation details that are not part of the contract.

**Comment by vincepri** [comment]
> However, if we need to add some context to a failing request deeper down into some "service" specific code (the code interacting directly with AWS resources for example) or library helpers (kubernetes-sigs/cluster-api/util for example), then it would make more sense to expose that information in a way that is less coupled to ctrl.Result.

In this context it probably makes sense to have different abstractions, wouldn't the caller of those inner services be responsible to understand the error and decide if there is a need to requeue or not?

I guess we'll have to see as we go, there is a lot of good ideas here that need to be thought out and it seems mostly related to the infrastructure provider codebase, rather than the Cluster API controllers, although it might be interesting to see how to restructure CABPK or KCP this way.

For the purpose of this issue, I'd like to continue removing and deprecating `RequeueAfterError`, I'd like to see how going forward how restructuring the reconcilers in different logical components can alleviate these issues, although sounds like this can be either in a different issue or proposal, and it's separate from the effort outlined in this issue.

Thoughts?

**Comment by detiber** [comment]
> In this context it probably makes sense to have different abstractions, wouldn't the caller of those inner services be responsible to understand the error and decide if there is a need to requeue or not?

Possibly, but I think there is some level of overlap here as well (such as a generic backoff and retry), but that could also be encoded into the specific abstraction for the given purpose. I do agree that it would be up to the caller to interpret the response and determine whether it warrants a requeue or not.

> I guess we'll have to see as we go, there is a lot of good ideas here that need to be thought out and it seems mostly related to the infrastructure provider codebase, rather than the Cluster API controllers, although it might be interesting to see how to restructure CABPK or KCP this way.

While I think infrastructure providers are a common use case for this, there is already quite a bit of shared code in the core providers and libraries we expose that could likely benefit from this approach as well.

> For the purpose of this issue, I'd like to continue removing and deprecating `RequeueAfterError`, I'd like to see how going forward how restructuring the reconcilers in different logical components can alleviate these issues, although sounds like this can be either in a different issue or proposal, and it's separate from the effort outlined in this issue.
> 
> Thoughts?

+1 I don't think the above discussion directly affects this issue or removing the use of `RequeueAfterError`

**Comment by benmoss** [comment]
> In this context it probably makes sense to have different abstractions, wouldn't the caller of those inner services be responsible to understand the error and decide if there is a need to requeue or not?

Exactly. I think this is definitely beyond the scope of this issue but it reminds me of my time working on web applications, and I think it's a common growing pain in all software. Initially you have small amounts of logic, and so you keep it all in the main function or private methods descending from there. Controller methods, whether we're talking HTTP or controller-runtime, act more-or-less as main functions since they are the entry point into the program.

At some point it starts to make sense to restructure the program into different components that are linked together via APIs much like the external API of the program. This helps reduce cognitive overhead by allowing you to constrain the problem space. It also lets you develop more thorough tests, since you can come up with a structure that lets you test significant logic without having to include now-irrelevant details like JSON serialization or complex third-party APIs. People talk about this as "domain logic", where you express logic in the pure terms of your domain, and keep out inessential factors like transport mechanisms or storage. People also love to talk about the potential for reuse, to be able to take significant amounts of code that was developed for a server and repurpose it to be used inside a CLI, but I think that ends up being more rare than people imagine.

Anyway I know I'm architecture-astronauting here but it is a subject I'm passionate about 😸 . It's all beyond the scope of this issue but it did raise this kind of concern in my mind.
