### ISSUE TITLE
Move published artifacts images to use k8s.gcr.io

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3384]
As reported in Slack (https://kubernetes.slack.com/archives/C8TSNPY4T/p1595441096272200) by @detiber, after the new domain comes into effect, we should be able to safely switch our images to use `k8s.gcr.io` in all our artifacts.

We'll probably going to hold this change until we have some confirmation that the migration went smoothly, probably until early next week.

/kind cleanup
/milestone v0.3.8
/priority important-soon

**Comment by fabriziopandini** [comment]
@vincepri @detiber I'm trying to derive action items for this issue.

AFAIK, in CAPI we are publishing our with google cloud build and images are already replicated to `{us, eu, asia}.gcr.io/k8s-artifacts-prod/cluster-api`.

If this is true, should we now change our templates to fetch from `k8s.gcr.io` instead of `us.gcr.io/k8s-artifacts-prod/cluster-api`? is this the only change required in CAPI?

**Comment by vincepri** [comment]
Yes, we should switch the manifests at some point before releasing v1alpha4
