### ISSUE TITLE
[clusterctl] local-overrides hack should also copy the metadata.yaml

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/cluster-api#3393]
**User Story**

As a provider developer, I would like to run our provider using clusterctl locally it can be done using local-overrides hack. However not all providers already have pre-defined metadata in clusterctl it would be better if we also copy the `matadata.yaml` from provider_repos if any there.

**Anything else you would like to add:**

Currently, only `infrastructure-docker` have metadata from local-overrides script
https://github.com/kubernetes-sigs/cluster-api/blob/60147823dc2131b822125598a73b2ad34e55b050/cmd/clusterctl/hack/local-overrides.py#L176-L177

/kind feature

**Comment by vincepri** [comment]
/assign @fabriziopandini @wfernandes 
to triage

**Comment by wfernandes** [comment]
@prksu I see that since clusterctl ships with [metadata built in](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/client/repository/metadata_client.go#L102) for many of the major providers they don't necessarily need to provide an external metadata file. 

Maybe in order to automate this in `./hack/local-overrides.py` we can define a `metadataFile` property as part of the `clusterctl-settings.json` for an infrastructure provider.
```json
{
  "name": "infrastructure-aws",
  "config": {
    "componentsFile": "infrastructure-components.yaml",
    "metadataFile": "path-to-metadata-file-in-provider-repo",
    "nextVersion": "v0.5.0",
  }
}
```
If the metadata file exists, then we can copy that into the overrides directory. This is a little different from the `componentsFile` since that is being built on-demand via `kustomize build` on the repo.

Were you planning on creating a PR for this perhaps?

**Comment by prksu** [comment]
@wfernandes Sorry for the delayed response. Yeah, I'll create a PR for this.

/assign
/lifecycle active

**Comment by fabriziopandini** [comment]
given the fact that CAPD artifacts are now published as part of the release, this should not be a problem anymore.
@prksu @wfernandes could you kindly confirm?

**Comment by prksu** [comment]
@fabriziopandini CAPDO metadata.yaml are now published in the release artifacts as well. this issue was not a problem from my side anymore.

**Comment by fabriziopandini** [comment]
/close 
as per comment above
