### ISSUE TITLE
MachinePool experiment API group should be under `cluster.x-k8s.io`

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3424]
MachinePool is today an experiment, and the API group we originally decided to pick was `exp.cluster.x-k8s.io`. Given that the intent is in the future to move MachinePool to the core API group, we should rewrite the experiment to use` cluster.x-k8s.io` or whatever the final group should be.

/kind cleanup
/milestone v0.4.0

**Comment by rudoi** [comment]
yeah yeah CI bot, we know :(

**Comment by vincepri** [comment]
@mytunguyen You should open an issue in k8s-sigs to the into the org, I'm happy to sponsor as well.

One thing to note, this would be for v1alpha4 and we haven't opened the main branch yet, if you want to get a head start please do :), just a warning that it might have to be rebased later

**Comment by vincepri** [comment]
Yeah better to do this now, rather than later. We need to document the transition. There isn't any good way to do this without breaking user in one way or another; we could have a controller that looks for the old resources and recreates them, although that might cause delete/create behaviors regardless

**Comment by detiber** [comment]
We could leverage `clusterctl` to provide a custom migration step to re-write the resources safely rather than a controller, especially since it should be short lived.

Longer term, we could also potentially leverage the management cluster operator (?? can't remember what naming was decided upon) to perform these types of actions.

I do think it would be good to make sure that we are publishing the old CRD info and have webhook validation to reject requests with a friendly message.

**Comment by CecileRobertMichon** [comment]
IMO, a reconciler to migrate the CRDs is a bit overkill for an exp/ feature in an alpha API. We would be introducing more complexity and more code to maintain. I'm leaning towards ripping off the band-aid now and avoiding making the same mistake in the future with other exp APIs. 

> We could leverage clusterctl to provide a custom migration step to re-write the resources safely rather than a controller, especially since it should be short lived.

That seems like a reasonable compromise to me, especially if any users speak up and tell us they would suffer from a breaking change on MachinePools.

> I do think it would be good to make sure that we are publishing the old CRD info and have webhook validation to reject requests with a friendly message.

Definitely.

/cc @devigned

**Comment by vincepri** [comment]
@CecileRobertMichon @devigned Should we do this in v0.4.0, as release blocker?

**Comment by CecileRobertMichon** [comment]
/unassign
I'm not actively working on this 

@nprokopic you had expressed interest in keeping back compat for MachinePool in office hours if I recall correctly.
Also cc @dthorsen since I know your team uses MachinePools. 

This change is going to be breaking so we need to get it in before v0.4.0 I believe. Anyone interested in working on this?

**Comment by vincepri** [comment]
During April 28th community meeting, most folks were ok with a breaking change without a migration path. We should definitely document the change and communicate it.

/assign @CecileRobertMichon 
/assign @yastij  to send an email to the mailing list
