### ISSUE TITLE
RFE: Management cluster operator

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3427]
Design and implement a clusterctl self-managing operator. 

/kind feature
/kind design
/milestone v0.4.0

**Comment by vincepri** [comment]
Details TBD, opening this issue just to track for now.

**Comment by randomvariable** [comment]
Just a note from Kubecon, that we should highlight self-managed clusters for use in gitops in the docs more.

**Comment by fabriziopandini** [comment]
I'm starting to work with this together with @wfernandes:
The main goal the IMO this work should achieve are:
- To make CAPI more git ops friendly by making it easier to handle the management cluster with git ops (vs opting out to clusterctl to do so)
- To make clusterctl simpler to use for teams of admins by sharing the same settings in the cluster (vs manually synchronizing local settings across workstations)

Looking forward to hearing from others in order to better shape out goals and non goals

**Comment by zawachte-msft** [comment]
I work on a team that built an operator which leverages clusterctl library to deploy and manage the management cluster.

Its closed source for now ... along with an infrastructure provider my team has been working on. Hopefully open sourcing soon!

Would love to bubble up some of the ideas and code we used to solve our usecase!

**Comment by detiber** [comment]
Feeding back in the suggestion from the Cluster API meeting today that we should probably call this "management cluster operator" or something similar to more accurately convey what the operator is managing.

**Comment by vincepri** [comment]
✅ Renamed the issue, it's super explicit now!

**Comment by richardcase** [comment]
@fabriziopandini @wfernandes - I'm really interested in this. We've been building GitOps+CAPI solutions for customers for a while now (since Dec 19).  A "management cluster operator" would really help in simplifying the GitOps+CAPI story.....we have to write a lot of code that essentially replicates init (or move). 

We've been toying with the idea of building something and created a very rough test operator that re-used the same package that clustectl uses for `init` so that the providers are declarative.

Would love to help out.

**Comment by vukg** [comment]
Oh, that would be cool to work out. @MaxRink was just scoping our operator to use clusterctl lib few weeks ago and we have been pumping up to start working on it for our use case, but we are also happy to contribute to community effort (specs, deployment and code contrib). Definitelly 👍

**Comment by fabriziopandini** [comment]
Thanks all for chiming in! I will try to set up a working group to define goals and non-goals and collects all the valuable experience you are bringing to this discusssion

**Comment by MaxRink** [comment]
I did some initial write-up of my Ideas in form of a HLD a few months ago ( https://github.com/MaxRink/cluster-api/blob/feature_clusterctl-improovements/docs/proposals/20200615-Clusterctl-Operator.md ), just hvent found the time to follow up on it.

**Comment by wfernandes** [comment]
Hey everyone! Thanks for being so patient. 

We've updated the [Management Cluster Operator CAEP](https://docs.google.com/document/d/1ZsusF5c9pYxseuaKxTpctI5aUDqzl0sdCW4xxDbLm3k). It now includes content regarding the proposed API and some examples of how it can be used. 

We'd appreciate any feedback, comments, suggestions on the API.
