### ISSUE TITLE
Flake in e2e tests for pivoting self-managed cluster

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#3536]
Seeing the following flakes in CI:

CAPI e2e:
* When testing Cluster API working on self-hosted clusters Should pivot the bootstrap cluster to a self-hosted cluster - https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api#capi%20e2e%20tests

CAPI unit tests:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api#unit%20tests 
seems to be mostly MachineHealthCheck

**Comment by randomvariable** [comment]
Breaking this out into two issues as per @ncdc's advice

/retitle Flake in e2e tests for pivoting self-managed cluster

**Comment by randomvariable** [comment]
Other issue is #3539

**Comment by sedefsavas** [comment]
I am not able to replicate this locally. On the failed tests, it is failing to connect to the management cluster after 9 retries. It may be because retry steps are not enough. 

I also see another issue in the failed tests, which may/may not be related:
`watch of *v1.Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Unexpected watch close - watch lasted less than a second and no items received`
Will investigate more.

**Comment by sedefsavas** [comment]
/close
Fixed by
https://github.com/kubernetes-sigs/cluster-api/pull/3675
https://github.com/kubernetes-sigs/cluster-api/pull/3667
