### ISSUE TITLE
breaking changes in patch releases

### ISSUE THREAD

**Issue by xh3b4sd** [kubernetes-sigs/cluster-api#3566]
Hello, I wanted to rather ask a general question. I see that it more often happens in this project that breaking changes get published in patch releases. I wonder why one would do something like that. The structure of the released tags looks pretty much like a semver version, though its semantics are not respected. What is the philosophy behind the currently implemented practice? I am a developer and my life gets just so much harder with breaking changes in patch releases, because then e.g. dependabot PRs are broken and one has to put way more effort into figuring out why this or that does not work again anymore.

**Comment by ncdc** [comment]
Hi @xh3b4sd, thanks for your question. This is a difficult thing to get "right" for everyone based on the state of the project today. Technically, because the project's version is less than 1.0.0, it has not yet reached the threshold for an initial stable public API. From https://semver.org/#spec-item-4:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

In this aspect, we are adhering to the rules put forth by semver correctly. However, we do realize and recognize that there are downstream consumers of Cluster API who may be impacted by breaking changes to our code base. We strive to consider every possible breaking change in every pull request, and only proceed with a breaking change in a patch release when the benefit (having access to whatever feature we're adding in the pull request ~ now) greatly outweighs the cost (having to wait months for the next minor release).

We would be interested to hear about specific breaking changes that caused you problems - would you be able to enumerate some of them? I can't promise that we will or won't make patch policy changes without discussing things with the other maintainers first, but having details will be helpful. Thanks!

cc @kubernetes-sigs/cluster-api-maintainers

**Comment by xh3b4sd** [comment]
I understand this. I also did realize that this is the major zero version still. The latest batch of around 15 broken dependabot PRs found their way to my email inbox this morning. One example is https://github.com/giantswarm/aws-operator/pull/2714. For now we just closed all of them. So we have to pickup the pieces once we get to it. Thank you for getting back to this so quickly. Keep up all the good work.

**Comment by fabriziopandini** [comment]
@xh3b4sd I have checked the build logs and I have found this error:
```
/go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.9/util/util.go:667:8: i.IsZero undefined (type reconcile.Result has no field or method IsZero)
```
The `reconcile.Result` type is from controller runtime; CAPI is using controller runtime v0.5.10, with the `IsZero` method, while your project is on v0.6.1 but this method does not exist in this version 😭

**Comment by vincepri** [comment]
> The reconcile.Result type is from controller runtime; CAPI is using controller runtime v0.5.10, with the IsZero method, while your project is on v0.6.1 but this method does not exist in this version 😭

It does exist in v0.6.2 https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.6.2

@xh3b4sd Appreciate you reaching out, let me read through this later. We're usually very careful with breaking changes, as Andy mentioned above we're still alpha and trying to figure things out. If you have other experiences like this that have happened in the past I'd love to take a look so we can learn from our own mistakes. Parts of the codebase are also not subject to the same guarantees (like clusterctl, and the experiments) and these are all documented.

The other challenge that we face is that while we have semver, we also have to adhere to go module compatibility and Kubernetes CRD API guidelines. We're also all on slack, and happy to jump on Zoom to see if we can find a better way to proactively communicate.

**Comment by xh3b4sd** [comment]
It is alright. Thanks everyone for your engagement. We can figure out the compile issues on our side. This can happen with unstable APIs. I was just not fully aware of the major zero version and its implications in this particular project.

**Comment by vincepri** [comment]
We should document this a little better, for this particular issue I'd suggest to always try to match dependencies (in this case controller runtime) with Cluster API, so when you update to the latest version, the dependencies get updates as well as part of `go mod tidy`

**Comment by ncdc** [comment]
@xh3b4sd is the timing (Wed 10 PT) convenient for you to join the public community meetings to discuss things like this?

**Comment by xh3b4sd** [comment]
Documentation is fair so that it is apparent which libraries work well together and in which versions. I am not 100% into dependabot in this case and how one might configure it. It might be that you cannot setup a lockstep between different dependencies. That would mean we just go manual for now. I have quite a bit on my plate though I will ask around internally to check if someone from Giant Swarm wants to join the next syncs.

**Comment by vincepri** [comment]
Thank you all, we started documenting more where compatibility guarantees aren't respected throughout our codebase, I'll go ahead and close this for now, thank you all for chiming in and definitely join our community meetings if you can!

/close
