### ISSUE TITLE
[e2e] Remove CNIManifestPath from the test framework

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3611]
CNI in e2e tests will be installed using ClusterResourceSet going forward, we can remove CNIManifestPath from ApplyClusterTemplateAndWaitInput. Since this is a breaking change, we should add this change in the release notes.

Here is the PR to revert this change for v0.3.8 release as it was not added to the release notes: https://github.com/kubernetes-sigs/cluster-api/pull/3608

/kind cleanup

**Comment by fabriziopandini** [comment]
I think that it will be useful to leave the possibility to install CNI without ClusterResourceSet, but we should document the two options are mutually exclusive

/milestone next

**Comment by randomvariable** [comment]
It's reasonable to add a deprecation notice now, with removal in v0.4.0 IMHO.

**Comment by CecileRobertMichon** [comment]
what's the need to remove it now if it can just be optional while CRS is still experimental?

**Comment by CecileRobertMichon** [comment]
Sort of related, I just realized there is no way for me to install a different CNI per workload cluster / `ConfigClusterInput` with v0.3.9 which is a blocker for https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/646 since we have a different Calico spec for IPv6... So I definitely need `CNIManifestPath` back until we can figure out how to allow per workload cluster CNI path.

**Comment by sedefsavas** [comment]
We can apply different CNIs to different e2e tests with ClusterResourceSet. Example here: sedefsavas/cluster-api#8

**Comment by vincepri** [comment]
Let's keep it for now, until CRS is promoted later on

/close
