### ISSUE TITLE
Deprecate Status.FailureMessage, FailureReason and use conditions for it

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3692]
Conditions in Cluster API are becoming the main tool for reporting status to the users.

In light of that, we should consider if in v1alpha4 we should deprecate Status.FailureMessage, FailureReason and use conditions for it as well.

Related to https://github.com/kubernetes-sigs/cluster-api/issues/3153

/kind feature

**Comment by bboreham** [comment]
Should this have the `kind/api-change` label?

**Comment by vincepri** [comment]
Sure

/kind api-change
/area api

**Comment by ncdc** [comment]
I'm in favor of switching to conditions as soon as is reasonable.

Some questions:

1. What condition(s) would we create to replace these 2 strings?
1. How would we convert the data between v1alpha3 and v1alpha4?

**Comment by srm09** [comment]
@ncdc @vincepri and I had a [Slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1607458426121600) around it. Continuing the discussion here.

> What condition(s) would we create to replace these 2 strings?
Creating a new condition, say `FailedCondition`, which would be added to the object in case of a failure. Any logic previously depending upon checking for failure message/reason in the status object will be moved to checking the presence of this condition on the object. Similarly, instead of populating the failure msg/reason, we add a condition to the object during the reconciliation loops.

> How would we convert the data between v1alpha3 and v1alpha4?
The best way would be to look for the presence of failure msg/reason on the object and populate the condition on the object as part of the conversion webhook. Not quite sure if this is how it would work, correct me if I am wrong here.

To @vincepri's concern around conditions being mutable, is there no case right now wherein we the CAPI objects can recover from the existing failure. My question being around, is there any specific reason why the existing Failure Msg/Reason fields should be immutable?

**Comment by ncdc** [comment]
Failure message & reason were explicitly designated as indications of a permanent failure from which there is no recovery (assuming you are using a MachineDeployment/Set and you have MachineHealthCheck enabled, this combination would yield the failed Machine being deleted and the MachineSet creating a replacement replica).

**Comment by srm09** [comment]
I do not see a way around making the, so called, `Failed` condition immutable except for adding a check in the validation webhook and adding documentation around this condition. @fabriziopandini might have some more thoughts around this one.

**Comment by fabriziopandini** [comment]
AFAIK failure msg/reason is used only in a few cases, and if we start by mapping those use cases probably this will make the discussion more concrete.

WRT to create new condition for terminal failures I'm a little bit hesitant for two reasons.
- Most probably those failures happen in the context of operation already monitored by other conditions. e.g. Failure messages can flow up from a clusterinfrastructure objects, but we already have the InfrastructureReadyCondition reporting progress for this process. Why not to surface the problem using the existing condition instead of creating a new one/forcing the use to correlate two conditions?
- CAPI conditions already have a severity field that can qualify a condition failure, why not use it?

looping into @yastij that might add more context given https://github.com/kubernetes-sigs/cluster-api/issues/3938

**Comment by yastij** [comment]
I think we are using those in a few places in CAPV and CAPA

#3938 - is to actually use severity to convey such information, and let the machine healthcheck decide, based on the severity, if it should remediate the machine or not. I'm planning on opening the PR tomorrow to kickoff discussions around this

**Comment by srm09** [comment]
The idea around creating a new Condition was that presence/absence of that particular condition across all CAPI objects will give an idea of the status of that object. It was more of providing a single way of figuring out the status of the CAPI objects, which can be used by providers and other API consumers.

**Comment by fabriziopandini** [comment]
> It was more of providing a single way of figuring out the status of the CAPI objects, which can be used by providers and other API consumers.

Might be I'm missing something but I'm still not grasping what will be the user experience with the new condition...

The baseline for my concerns is that now all the objects have a set of conditions, each one representing the status of a particular underlying bit of infrastructure/process, plus the ReadyCondition which already provides a single way of figuring out the status of the CAPI objects. 
Last but not least, the Ready condition flows up from an object to another to improve visibility through the object hierarchy. 

Let's try to make an example to understand how this will change:

- In the AWS cluster infrastructure object there is e.g. VpcReady, SubnetReady Conditions (let's limit to those two for simplicity), and there is also the ReadyCondition summarizing everything else
- Let assume we add a new FailureCondition for reporting a fatal error.
- As a user, how can I correlate the FailureCondition with the source of this error: is it related to the Vpc to to the Subnet?
- Let's assume the source of the error is the Vpc, are we expecting to have some consistency rule to make sure that VpcReadyCondition and the FailureCondition are consistently saying the same thing? If not, could this be confusing for the users? if yes, why we need two conditions to say the same thing?
- How the FailureCondition will be reflected in the ReadyCondition? are we expecting to have some consistency rule to make  sure that ReadyCondition and FailureCondition are consistently saying the same thing? Same as above (is it confusing or a duplicate?)
- How the FailureCondition is expected to flow up through the object hierarchy? What if we have many objects depending on one parent (control-plane machines to KCP)?

**Comment by srm09** [comment]
Just to give you some tiny background,
I had initially thought of using the `Ready` Condition as a candidate to use to populate the failure message/reason. But the Ready condition being false does not indicate that there has been any catastrophic failure/terminal error. A False Ready Condition could also mean that things are still going on, and eventually the object will be ready.
So IMO, Ready Condition was a not a good candidate to populate the failure reason.

Moving over to the above example:
- My idea was that the Failure Condition would act as a single check to query for the health of the object. Rather than having to cycle across multiple conditions to see if there is any issue/not, the consumer of the object can be sure of the object health by checking for the presence of this condition.
- Having a single condition indicating the failure scenario would provide an easier interface for the consumers to query the status if the object

But I think, it seems like I am replacing the `FailureMessage` and `FailureReason` with a new Condition which does the exact same thing. Instead of being an immutable field, it will be a condition giving the same functionality/information. 
Plus, introducing it would incur additional complexity around keeping the conditions consistent which might be more difficult that actually looping thru conditions to check the health of the object.

**Comment by CecileRobertMichon** [comment]
FYI I found some uses of FailureMessage in the CAPI cluster-autoscaler provider, e.g. https://github.com/kubernetes/autoscaler/blob/06e5f6a0ed3c46d51347787d04712ea10d76d3b2/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L456 

cc @elmiko

**Comment by vincepri** [comment]
Just re-read the whole conversation above, what if we keep Conditions for to describe the current state of the resource _until there is a terminal failure_. As in, Conditions should be treated as fully mutable and they're never a terminal state, while we keep the current fields (or something similar, a struct maybe) to determine a terminal state?

By having it in a field, we could add a requirement on a validation webhook that these fields are immutable, and that we could have reconciliation to stop or filter these objects out completely (maybe, we'll see, need to think about this one more).

**Comment by yastij** [comment]
@vincepri - from a UX perspective, it's pretty implicit that the current fields are for terminal failures,  having everything under conditions would ease things debugging, it would also simplify MHC to only deal with conditions in v1a4

**Comment by vincepri** [comment]
As long as we have some default validation that won't allow further modifications to a specific condition, I'm +1 with it. This makes sure that once an object has transitioned to a failure state (which is terminal), there is no way back to a non-terminal state and the object has to be deleted or recreated.

For any other non-terminal failure, a different condition should be used.

Something I was thinking last time I was on this topic was that conditions aren't really meant (today) to be used in this way. Furthermore, conditions outside of the terminal failure might still be patched or updated after the failure is set.

The last point we should probably check is where and how to express a failure state.

**Comment by vincepri** [comment]
/milestone Next

Folks, moving this to Next as I'm not totally sure if we want to deprecate this fields just yet. Having a separate entity altogether for failures is a bit easier to understand, while conditions are a great way to express current state and possible blockers, I would like to see if we can find a way to better express terminal failures.
