### ISSUE TITLE
KCP: support pluggable proxy providers

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#3700]
**User Story**

As a user, I would like to create a new cluster using a proxy provider of my choosing, instead of having kubeadm install kube-proxy, because I'd like to use something other than kube-proxy from the start.

As a user, I would like to manage my proxy provider separately from KCP, decoupling their lifecycles, so that I'm in control of my proxy provider.

**Detailed Description**

See user stories

**Anything else you would like to add:**

kubeadm is currently responsible for installing kube-proxy and we'll need to be able to disable that.

/kind feature
/milestone Next

**Comment by neolit123** [comment]
the current way is by passing `--skip-phase=addons` or a specific `addon/x`.
but i guess for CAPI this has to be supported via the config:
https://github.com/kubernetes/kubeadm/issues/2261

**Comment by sbueringer** [comment]
> kubeadm is currently responsible for installing kube-proxy and we'll need to be able to disable that.

@fabriziopandini I think this is possible today via: `controlplane.cluster.x-k8s.io/skip-kube-proxy`

Not sure if this covers the entire issue.

**Comment by fabriziopandini** [comment]
I have to dig into this, but on top of my mind what we have now isn't a clean API because you have to use phases to skip addon installation and then use the annotation above to avoid errors on upgrades.
But you are right, this can be achieved now; let's keep this open to see if we gather ideas about if and how we should improve the UX

**Comment by sbueringer** [comment]
Oh you're right. Same for CoreDNS

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

We already have skip-proxy annotation that allows to achieve something similar, but considering that there is no demand and the issue is not updated since 2022, I don't see this making progress anytime soon

/close
