### ISSUE TITLE
Define Condition reason severities for providers

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3732]
When setting a condition, checking the suggested severity of a reason is somewhat error prone.
It may be useful to have a helper function for all providers that returns the default severity of condition reasons. 

Similar to this:
```
func (c ConditionReason) GetSeverity() clusterv1.ConditionSeverity {
	switch c {
	case controlplanev1.PodProvisioningReason:
		return clusterv1.ConditionSeverityInfo
	case controlplanev1.PodMissingReason:
		return clusterv1.ConditionSeverityWarning
	default:
		return clusterv1.ConditionSeverityInfo
	}
}
```

One down side here is we will have to maintain it everytime we add a new condition reason.

**Comment by fabriziopandini** [comment]
This could be something interesting to explore, but we should figure out how this could work with different sets of conditions reason, at least one for each project using CAPI conditions, being converted in different `ConditionReason` types all landing on a single set of a utility (e.g. `conditions.MarkFalse` or `conditions.FalseCondition`)

Might be defining an interface `ConditionReasonSeverityGetter` could help to address this problem, so we can e.g.

Move from 
```
func FalseCondition(t clusterv1.ConditionType, reason string, severity clusterv1.ConditionSeverity, messageFormat string, messageArgs ...interface{}) *clusterv1.Condition
```
to
```
func FalseCondition(t clusterv1.ConditionType, reason ConditionReasonSeverityGetter, messageFormat string, messageArgs ...interface{}) *clusterv1.Condition
```

One there is agreement on a solution, this requires an update to the proposal + documentation because it is a breaking change

**Comment by fabriziopandini** [comment]
/kind cleanup
@vincepri I'm +1 to move to release next due to bandwidth

**Comment by vincepri** [comment]
/assign @fabriziopandini 
to re-triage

**Comment by fabriziopandini** [comment]
/close
This code cleanup provides a real advantage only if we are setting the same condition/reason in many places, and this is not  what happen in the most of the cases.
