### ISSUE TITLE
Add tilt-provider file to CAPD

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3785]
CAPD is missing tilt-provider.json, which is used to start a management cluster with CAPD using tiltfile, similar to: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/tilt-provider.json

**Comment by detiber** [comment]
This makes me wonder if it'd be possible to remove the custom tilt-provider.json and our custom tilt-settings.json file with [Tiltfile Config](https://docs.tilt.dev/tiltfile_config.html) and [include/load Tilt files](https://docs.tilt.dev/multiple_repos.html) from the individual provider repos where needed

**Comment by ncdc** [comment]
+1 to Tiltfile config; that didn't exist when we initially added Tilt support. That's tracked in #3415.

re including/loading, that's worth exploring. The Tiltfile in this repo does have the "dev" Dockerfile setup + live reloading, although it's not that much code, so maybe we could find some way to share it w/o copying it everywhere. Maybe file a separate issue for this?

**Comment by detiber** [comment]
@ncdc I suspect the [restart_process](https://github.com/tilt-dev/tilt-extensions/tree/master/restart_process) tilt extension would probably help simplify it, will file an issue.

**Comment by fabriziopandini** [comment]
CAPD does not requires a  tilt-provider.json, because it is hard coded in the main tilt file
https://github.com/kubernetes-sigs/cluster-api/blob/19e40cd536d5ea0296599e2678e7cc70e385b452/Tiltfile#L69-L89

Nevertheless, +1 to explore Tiltfile config or other means to simplify our tilt file (I recently created https://github.com/tilt-dev/tilt-extensions/tree/master/cert_manager with the same goal in mind)

**Comment by sedefsavas** [comment]
Closing this issue. Follow up on tiltfile config is here: https://github.com/kubernetes-sigs/cluster-api/issues/3793
