### ISSUE TITLE
Node to Machine mapping function should filter by namespace and cluster

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#3831]
**Detailed Description**

This came out from https://github.com/kubernetes-sigs/cluster-api/pull/3826#discussion_r508557322, we need to audit and see where we use a mapping function from node -> machine and filter out on cluster and namespace.

- For cluster filtering, we can achieve this today by using a label selector.
- For namespace filtering, we need instead to wait for controller runtime to support this functionality.

/kind cleanup
/milestone v0.4.0
/cc @ncdc

**Comment by enxebre** [comment]
>For cluster filtering, we can achieve this today by using a label selector.

Or an indexField for `spec.ClusterName` but how do we know the cluster in the scope of `nodeToMachine` since `type MapFunc func(client.Object) []reconcile.Request` does not take parameters? Is there something in the nodes e.g a label we can use?

>For namespace filtering, we need instead to wait for controller runtime to support this functionality.

@vincepri For namespace aren't we filtering already since we are using the cached `r.Client.` which is scoped to the manager namespace?
