### ISSUE TITLE
Enable running multiple versions of CAPI controllers in paralell

### ISSUE THREAD

**Issue by MarcelMue** [kubernetes-sigs/cluster-api#4004]
**User Story**

As an operator I would like to be able to run multiple versions of CAPI controllers to limit the number of management clusters.

**Detailed Description**

The current guideline to change the version of CAPI controllers which reconcile a set of clusters is to move the CRs of the cluster to a new management cluster containing the desired version of CAPI controllers.

This process becomes difficult with a large number and diversity of clusters.

I want to propose that multiple versions of CAPI controllers can run on the same management clusters. The controllers would only reconcile CRs with a certain label. Example:
`cluster.x-k8s.io/watch-label:v0.3.9` -> reconciled by controllers with version `v0.3.9`
`cluster.x-k8s.io/watch-label:v0.3.11` -> reconciled by controllers with version `v0.3.11`

**Anything else you would like to add:**

Using labels for this purpose is not optimal as they are not very structured. They do however make it easy to enable this functionality quickly.

/kind feature

**Comment by fabriziopandini** [comment]
I think this should be discussed in the CAPI meeting, given that previous discussions on the same topic lead to a different direction.

Wrt to the proposed label, I find a little bit confusing the idea of using a label for instructing each CAPI controller instance to reconcile different version of CRs because:
- in Kubernetes, there is only a single storage version for each CR (v1alpha3 for the v0.3.x series).
- the CR version does not change for an entire lifespan of a minor version (e.g both v0.3.9 and v0.3.11 use the same API versions)
- each controller versions typically manages more CR versions (e.g both v0.3.9 and v0.3.11 works with v1alpha2 and v1alpha3) in order to support upgrades
