### ISSUE TITLE
Kubeconfig secrets created by CAPI v1alpha2  are not regenerated by KCP

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#4011]
**What steps did you take and what happened:**
1. Create a cluster using v1alpha2 controllers and CRD.
2. Upgrade the controllers to CAPI 0.3.10 and CAPA 0.6.3
3. Make sure the kubeconfig has less than 6 months for the certs to expire.
4. Upgrade a v1alpha2 cluster. KCP adopts the control planes and then upgrades the cluster.
5. The kubeconfig certs were not regenerated.

**What did you expect to happen:**
1. Expected the kubeconfig to be regenerated.

**Anything else you would like to add:**
This issues occurs because kubeconfigs secrets created by v1alpha2 controllers had Cluster as the owner. KCP [regenerates](https://github.com/kubernetes-sigs/cluster-api/blob/af6630920560ca0e12179897b96d6ea8bd830b63/controlplane/kubeadm/controllers/helpers.go#L72) certs only if the secret is owned by KCP and because old kubeconfigs are not owned by KCP it is not regenerated.

**Environment:**

- Cluster-api version: 
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/area control-plane
/priority critical-urgent
/milestone v0.4.0

The fix should be backported in v0.3.x as well

**Comment by fabriziopandini** [comment]
Problem triage + possible solution

In the cluster controller
- [reconcileKubeconfig](https://github.com/kubernetes-sigs/cluster-api/blob/e73e3d9021e5df61ea2861be6f73698a031a63c3/controllers/cluster_controller_phases.go#L261-L263) stops to manage a kubeconfig secrets as soon as there is control plane ref (and there is no renewal logic)
In KCP controller
- [adoptMachines](https://github.com/kubernetes-sigs/cluster-api/blob/979197c35281c21bb34a7bc0b70f5c66af6c48cb/controlplane/kubeadm/controllers/controller.go#L543), well, adopt machines and everything related to them, but not the kubeconfig secret which is at the cluster level.
- the kubeconfig secret is then reconciled by [reconcileKubeconfig](https://github.com/kubernetes-sigs/cluster-api/blob/e73e3d9021e5df61ea2861be6f73698a031a63c3/controlplane/kubeadm/controllers/helpers.go#L46) where there is an explicit test for skipping renewal in case of secrets not owned by KCP. The last time this code was touche is https://github.com/kubernetes-sigs/cluster-api/pull/3140, and from my understanding, this is intentional as per https://github.com/kubernetes-sigs/cluster-api/pull/3140#issuecomment-639712859 (I assume this is for the user provider CA scenario as well)

Now, according to my understanding of this issues, a possible way forward is to get reconcileKubeconfig in KCP to change the ownership of the kubeconfig from owned by cluster --> controlled by KCP, but we still want to ignore the kubeconfig files without any ownership

@ncdc @vincepri @detiber does this makes sense?

**Comment by ncdc** [comment]
Maybe this was an accidental miss? We do have `adoptOwnedSecrets` in KCP, but that only adopts secrets owned by the KubeadmConfig (all the certs, IIRC).

My quick reaction is 👍 to having KCP adopt the kubeconfig secret if it exists and is currently owned by the Cluster.

**Comment by vincepri** [comment]
@fabriziopandini @wfernandes @sedefsavas Any of you can take this + backport?

**Comment by fabriziopandini** [comment]
If no one gets on this before, I can give it a try tomorrow
