### ISSUE TITLE
Establish a stronger link between Machines, MachineSets, and MachineDeployments with their Cluster.

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#41]
_From @dgoodwin on February 15, 2018 17:12_

On Feb 14 Cluster API working group call, a couple parties indicated we would like to make use of the ability to have multiple clusters to exist in one namespace, which would free up namespaces to be used for other levels of organization. (one customer, one cloud provider account, etc) In this case we would not be able to assume all machines or machine sets in a namespace belong to the single cluster in the namespace, and as such a stronger link between the two could be useful for some adopters of the cluster API.

_Copied from original issue: kubernetes/kube-deploy#609_

**Comment by rsdcastro** [comment]
_From @dgoodwin on February 15, 2018 17:14_

FWIW, in our very young OpenShift Cluster Operator code we've been using owner references to do this. (machine to machine set to cluster)

**Comment by krousey** [comment]
This was not fixed with that PR. That was a separate issue.

**Comment by krousey** [comment]
@dgoodwin I've been thinking about this, and is owner references a good fit for this? It seems to require a UUID. That seems prohibitively awkward for a user to fill out. What does everyone think?

**Comment by dgoodwin** [comment]
Agreed it would have to be handled automatically, this led to our idea regarding the labels (which the user would need to set) and the owner reference (which a controller would set, as soon as the referenced owner exists).

**Comment by vincepri** [comment]
On Wed 9 January 2019 meeting, the group discussed to potentially revert the assumption that clusters and machines living in the same namespace are tied together.

Some meetings notes:

This is the PR that implemented the cluster-machines namespace #481
Related: #177
Do we want a tighter relationship between clusters / machines so that we can have multiple clusters in a single namespace
[ashish] When I started the above PR, the consensus was that we wanted one cluster per namespace #252 (comment)
[ashish] more context on the issue #252
[vince] That is the current assumption. Do we want to make that official?
[robert] Hardik has mentioned that Gardener found it useful to put multiple clusters into a namespace so that things like references to secrets can be shared
[justinsb] We may want to get an api reviewer to take a look at our API and help us answer some of these types of questions. I'm not sure if there are other examples of singletons.
[detiber] If we create a link between the two we should be aware of the use case of using machines without clusters and we'd need to make the link optional
[robertbailey] We could use labels to match them up
[robertbailey] Even if there are examples of singletons, they certainly aren't commonplace
[justinsb] kops wouldn't object to creating a dummy cluster object if necessary to adopt the machines api
[robertbailey] the other use case is to put cluster and machine resources in different kubernetes universes; so then the link would also need to be optional
[vince] If we use the label, then providers can adopt them over time
[justinsb] Label selectors are great for many-many which doesn't work well here. Maybe have a field that just points to the owning cluster (even across universes). If it doesn't exist fall back to existing behavior of same-namespace

The goal of this issue is to get an agreement if we want to support multiple clusters in a single namespace. A followup issue, after this one is closed, will be opened to discuss implementations.

**Comment by roberthbailey** [comment]
Expanding the scope after closing https://github.com/kubernetes-sigs/cluster-api/issues/145 to include MachineSets and MachineDeployments in addition to Machines.
