### ISSUE TITLE
Add ability to specify user data secret namespace and key

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4114]
I'd like to have the ability to specify the namespace and key for user data secret. The current [implementation](https://github.com/kubernetes-sigs/cluster-api/blob/b08ed532156e011a0e100a79c11a1726577524b7/api/v1alpha4/machine_types.go#L225) of user data secret reference is represented as a string:

```golang
type Bootstrap struct {
        ...
	DataSecretName *string `json:"dataSecretName,omitempty"`
}
```
Proposed change:

```golang
type Bootstrap struct {
        ...
	DataSecret *Datasecret `json:"dataSecret,omitempty"`
}

type DataSecret struct {
        // DataSecretReference reference to a secret that contains bootstrap script
        DataSecretReference *corev1.ObjectReference `json:"dataSecretReference,omitempty"` 
      
        // Key secret key used to obtain bootstrap data script content
	Key *string `json:"key,omitempty"`
}

```
The key value can default to a value that is currently used by infrastructure providers.

/kind feature

**Comment by JoelSpeed** [comment]
I think this will be useful for scenarios where we want to have a decoupled infrastructure where the data isn't necessarily being created by something akin to the KubeadmControlPlane. One question I would have is around the security concerns, perhaps it is easier for users to be able to deploy so that all secrets are in one namespace, does this make this a power user feature where you have to extend the RBAC to allow cross namespace secrets?

As an alternative suggestion for the `DataSecret`, you could embed the `ObjectReference` so that in yaml you have:
```
dataSecret:
  name: ...
  namespace: ...
  key: ...
```
Instead of the current
```
dataSecret:
  dataSecertReference
    name: ...
    namespace: ...
  key: ...
```

**Comment by alexander-demichev** [comment]
@JoelSpeed AWS provider, for example, expects the user data secret to be present in the same namespace where machines are located https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/scope/machine.go#L253 , it means that access to a different namespace is expected.

**Comment by vincepri** [comment]
What's the use case we're trying to solve here?
