### ISSUE TITLE
KCP upgrade fails when KCP remediation moves leadership

### ISSUE THREAD

**Issue by jan-est** [kubernetes-sigs/cluster-api#4124]
**What steps did you take and what happened:**

We are testing KCP upgrade using CAPM3 as a infrastructure provider. In our test environment we have 3 controlplane Machines consuming all 3 physical servers. 

```
kubectl get machines -n metal3
NAME          PROVIDERID                                      PHASE     VERSION
test1-7x2pg   metal3://39e8666c-b55c-4cd6-8306-5c32b38b6758   Running   v1.19.3
test1-vttz2   metal3://53495ad9-caa9-4b1d-8abd-651f8e63fb92   Running   v1.19.3
test1-xlpdg   metal3://3163cdc0-180d-4413-a2ba-33f576714e98   Running   v1.19.3

kubectl get bmh -n metal3
NAME     STATE         CONSUMER                   ONLINE   ERROR
node-0   provisioned   test1-controlplane-sn69z   true     
node-1   provisioned   test1-controlplane-csnwh   true     
node-2   provisioned   test1-controlplane-cqfmh   true 
```
We triggerd KCP update knowing that the update would not succeed because there are no extra resources available for KCP to scale-up. So new Machine will stay on provisioning state. 

```
kubectl get machines -n metal3
NAME          PROVIDERID                                      PHASE          VERSION
test1-7x2pg   metal3://39e8666c-b55c-4cd6-8306-5c32b38b6758   Running        v1.19.3
test1-vttz2   metal3://53495ad9-caa9-4b1d-8abd-651f8e63fb92   Running        v1.19.3
test1-xlpdg   metal3://3163cdc0-180d-4413-a2ba-33f576714e98   Running        v1.19.3
test1-zcg8q                                                   Provisioning   v1.19.1
```  
We tried to use KCP remediation feature to remove one of the old Machines so we patch one of the Machines with `OwnerRemediated=false` and `HealthCheckSucceeded=false` conditions.

**What did you expect to happen:**

We expect KCP remediation to be able to recover from situation where updated control plane Machines is still in provisioning state and one of the Machines with old spec is set for the remediation. We expect remediation to remove patched Machine, which eventually will deprovision one of our physical servers and our Machine in provisioning state could consume that server.  

During the testing we hit the following error

```
E0121 09:27:41.226214  1 remediation.go:129] controllers/KubeadmControlPlane "msg"="Failed to move leadership to 
candidate machine" "error"="leader has no node reference" "cluster"="test1" "kubeadmControlPlane"="test1"
"namespace"="metal3" "candidate"=test1-zcg8q"
```
Now we got stuck on this phase. Leadership was tried to move on the Machine that is still in provisioning state and remediation did not pick another Machine.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
> We expect KCP remediation to be able to recover from situation where updated control plane Machines is still in provisioning state and one of the Machines with old spec is set for the remediation. 

Given that KCP is handling a control plane, IMO we should stick to safe side and prevent KCP remediation to take actions while the cluster is in a transitional state.

That's means that, if there is a provisioning machine, KCP should report using conditions that it can't proceed until the machine is fully provisioned (similar to what happens if there is a deleting machine), instead of trying to remediate as described above.

**Comment by vincepri** [comment]
@fabriziopandini Let's tackle this before v0.4.0 release.

**Comment by jan-est** [comment]
@fabriziopandini I’m not sure does scale-in rollout stop us from hitting this issue? Scale-in does solve lot of baremetal use cases, but is this issue something we would need to prevent in general?

**Comment by fabriziopandini** [comment]
IMO remediation main concern is to preserve a functional cluster, so IMO it should not be used as a strategy for solving other problems, like resource constrained environments. 

There are a lot of unknown when remediating a machine when another one is still in the middle of provisioning, beacuse any assumption about the operation (and especially about the target etcd quorum) can be invalidated any time, and if the joining etcd member have some problems this could be destructive for the entire cluster.

I'm for making out remediation logic more restrictive, and block remediation if there is a machine still provisioning (except for the machine being provisioned), but this isn't what the issue is asking for.

**Comment by fabriziopandini** [comment]
By Mistake I delete my comment... sorry

IMO the main concern of remediation is to preserve the operational state of cluster, and it should not be used as as strategy for solve other problems like resource constrained environments.

Remediation a machine one another is being provisioned have several unknowns, because any assumption made before remediating can be invalidated whenever the member being provisioned join the cluster, and if the joining etcd has some problem, this can lead to a non operational cluster.

This is why I'm +1 to implement a new preflight check preventing remediation when there is a machine still provisioning (except of the machine being provisioned), but this is different from what the issue was originally asking for...
