### ISSUE TITLE
Refactor main to be in line with kubebuilder generated ones

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4136]
**Detailed Description**
As per comment https://github.com/kubernetes-sigs/cluster-api/pull/3985#discussion_r566476491

We should refactor our main functions in order to be in line with kubebuilder generated ones, and more specifically `setupReconcilers` and `setupWebhooks` etc will need to be consolidated back into a single main function.

**Anything else you would like to add:**

We should check if inlining everything into the main function does not compromise readability for newcomers (the number of reconciler/webhook in CAPI is relevant)

/kind feature

**Comment by vincepri** [comment]
We should be able to use the tags to make kubebuilder still work?

**Comment by fabriziopandini** [comment]
> We should be able to use the tags to make kubebuilder still work?

This should be investigated, let's make it clear if we consider this a goal

**Comment by sbueringer** [comment]
I'm wondering why exactly do we want to refactor it to be in line with kubebuilder?

Some options:
* so that the generation works (I would also think this works based on the tags alone)
* we're closer to the "standard", so its easier to keep up and sync with new kubebuilder / controller-runtime releases
