### ISSUE TITLE
What are the advantages of Cluster API test framework over clusterctl CLI on developing e2e testing?

### ISSUE THREAD

**Issue by Insullone** [kubernetes-sigs/cluster-api#4406]
We are developing e2e tests in [cluster-api-provider-metal3](https://github.com/metal3-io/cluster-api-provider-metal3), and according to [Developing E2E tests](https://cluster-api.sigs.k8s.io/developer/e2e.html) in Cluster API book, [Cluster API test framework](https://pkg.go.dev/sigs.k8s.io/cluster-api/test/framework) and [test E2E package](https://pkg.go.dev/sigs.k8s.io/cluster-api/test/e2e) are suggested to use. The situation is that we have already built our similar testing environment with clusterctl CLI and ansible in Shell scripts, and the question is, should we replace the existing testing environment with a new one using Cluster API test framework and test E2E package? Is the replacement worth doing for long-term benefits? If yes, what are the advantages (functional and non-functional) of Cluster API test framework and test E2E package over clusterctl CLI in shell scripts for developing e2e tests? Thank you.

**Comment by fabriziopandini** [comment]
I second @sbueringer consideration that there is definitely long term value in sharing and maintaining the test framework code together instead of reinventing it a slightly different way in every provider.

WRT to the value the test framework can already provide as of today:
- A set of helpers for managing E2E test (bootstrapping, log collection, tear down)
- A set of helpers for handling cluster templates or single CAPI resources during common E2E scenarios
- A set of pre-existing test cases that can be easily replicated on different infrastructure providers
- A growing number of E2E tests implemented using the above stack both in CAPI and in several infrastructure providers

**Comment by furkatgofurov7** [comment]
@sbueringer hello!  Thanks for sharing your thoughts and experience. 

> I migrated CAPO recently to the e2e test framework

Yes, I have seen the patches in CAPO, that is excellent work. 

> Apart from setting up the test environment via Ansible, shell scripts and clusterctl. How are you running you're actual tests on top of that currently?
> 
> I'm talking about things like:
> 
>     * deploying resources like Clusters / MachineDeployments / ...
> 
>     * validating that they are successfully reconciled
> 
>     * dumping resources and logs to be able to debug test failures

In [CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3), we do currently have only integration tests run and all the setup is split into two different repositories. 

1. Jenkins setup hosted in [project infra repo](https://github.com/metal3-io/project-infra) which has configurations for creating Openstack VMs in [CityCloud](https://citycloud.com/) (public cloud environment) where integration tests will be run and deleted once finished;
2. Ansible playbooks + shell scripts which are used in integration tests are hosted under [metal3-dev-env repo](https://github.com/metal3-io/metal3-dev-env). A bit more context on this below:
- [script_1](https://github.com/metal3-io/metal3-dev-env/blob/master/01_prepare_host.sh) prepares and sets up libvirt nodes  
- [script_2](https://github.com/metal3-io/metal3-dev-env/blob/master/02_configure_host.sh) sets up networking for libvirt nodes and starts some containers
- [script_3](https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh) runs `clusterctl init ` (+ some other deployments related to metal3)
- [script_4](https://github.com/metal3-io/metal3-dev-env/blob/master/04_verify.sh) verifies all resources (CRs', Clusters, MD, MS, machines, etc) and if they are reachable
- [script_5](https://github.com/metal3-io/metal3-dev-env/blob/master/05_test.sh) provisions/deprovisions(cluster/controlplane/workers) using ansible tasks [here](https://github.com/metal3-io/metal3-dev-env/tree/master/vm-setup/roles/v1aX_integration_test/tasks) (also some other tests, like pivot/remediation). dumping manifests using [this script](https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/fetch_manifests.sh) and fetching logs using [this](https://github.com/metal3-io/project-infra/blob/master/jenkins/scripts/fetch_logs.sh). 

As you see, we have only integration tests in place that somehow/in someway IMHO(not the E2E test framework expert) replicates what CAPI E2E framework does. What we want to explore and would like to know is, if we can also use CAPI E2E framework in CAPM3 with the current setup we have and if yes, we would like to understand and make sure that this work will not be the replica of what we currently have(meaning that our integration tests being the same thing to e2e tests but doing it differently). 

> WRT to the value the test framework can already provide as of today:
> 
>     * A set of helpers for managing E2E test (bootstrapping, log collection, tear down)
> 
>     * A set of helpers for handling cluster templates or single CAPI resources during common E2E scenarios
> 
>     * A set of pre-existing test cases that can be easily replicated on different infrastructure providers
> 
>     * A growing number of E2E tests implemented using the above stack both in CAPI and in several infrastructure providers

@fabriziopandini hi! I fully agree, and we also checked those other providers implementing the same stack, but since we have different ways of setup and CI in terms of testing (since we are not under k8s-sigs) compared to other providers, not fully sure but it might be slightly different how we can/should utilize the framework, IMO. 
So that's why we wanted to know the long-term benefits and possible ways of how can we make it happen to be able to utilize the CAPI E2E  framework in CAPM3. Any suggestions/feedbacks are welcome and helpful. Thanks!

**Comment by sbueringer** [comment]
@furkatgofurov7 

I think it would be useful to roughly split up the tests in 2 parts:

* setup the environment (I think you can keep using your scripts: script_1, script_2)
  * this should setup all external dependencies which are also usually expected when running your provider in production
  * I don't really know what this includes in your case, in case of CAPO it was: setting up an OpenStack and providing credentials to an OpenStack tenant

* build required images and run the e2e tests via the e2e framework. This roughly looks like:
  * make e2e-image
  * make test-conformance (which runs ginkgo ...)
    * the cluster-api test framework provides code to (in this order):
      * create a kind cluster
      * load provider images into the kind cluster
      * deploy providers (core, bootstrap, control plane, infra (your provider)) based on a config file: [e2e_conf.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/test/e2e/data/e2e_conf.yaml) and wait until they are ready
    * then you're tests are run (if you want, in parallel)

I think it makes sense to take a look at existing implementations. I would suggest taking a look at either the tests in the cluster-api repo or maybe CAPO (already v1alpha4 on the main branch) / CAPA to get a feel for the framework.

I also had only one e2e test before which installed a cluster and then ran the Kubernetes conformance test. After I had that one migrated to the cluster-api framework it was easy to add other tests for various variants.

I think you should be able to utilize the framework, even if you're not part of one of the Kubernetes orgs and are not using Prow. Actually all tests I've taken a closer look at (CAPD/CAPO/CAPA) can be run from a regular linux machine when the prerequisites like credentials for the respective cloud are fullfilled.
