### ISSUE TITLE
Add maximal machine age to MHC

### ISSUE THREAD

**Issue by alexander-demichev** [kubernetes-sigs/cluster-api#4450]
**User Story**

As a [developer/user/operator] I would like to set maximal age for my machines using MHC. The reason is the ability to recycle machines that are older than the user wants them to be. Example use case: Preemptible instances on GCP are deleted every 24 hours and there is no preemptible event coming from the termination endpoint. As a user I'd like to recycle these machine when they exist for about 24 hours.

**Detailed Description**

This can be implemented by adding a new field MHC spec - `MaxAge *metav1.Duration `json:"maxAge"``, this field will be optional and no default value is required.

/kind feature

**Comment by enxebre** [comment]
+1
How will we prevent all machines in a scalable resource which might have very similar creation timestamp from being deleted at a time? So we don't drain to relocate workload inefficiently?

**Comment by JoelSpeed** [comment]
I think the `maxUnhealthy` should come into play here right? If they all reach the expiry at once, then it will trip `maxUnhealthy` and none of them will get remediated.

Do we need to revisit how `maxUnhealthy` works and make it so that it can go up to that limit for this case? This would be more like how a PDB works with disruptions

**Comment by fabriziopandini** [comment]
This seems to me more a Machine attribute than a MHC rule.
Also we should make this consistent with `UpgradeAfter` existing at KCP level, even if I found using `Rollout` instead of `Upgrade` could be more appropriate.

**Comment by elmiko** [comment]
i've heard a similar user story as in the example, on some cloud platforms users would like to consistently replace machines at certain intervals. the story i heard was about improving stability by remediating machines older than a few days. we talked about several ways to do this type of interaction, using the mhc, using metrics/alerting, even using a cronjob. it seems like the mhc is a good tool for doing this recycling type of activity.

> This seems to me more a Machine attribute than a MHC rule.

that's an interesting thought

> Also we should make this consistent with UpgradeAfter existing at KCP level, even if I found using Rollout instead of Upgrade could be more appropriate.

i'm not overly familiar with this workflow, does the "Rollout" option just replace the machine?

**Comment by detiber** [comment]
To add to what @fabriziopandini mentioned about consistency with `UpgradeAfter`, someone was recently asking about having `UpgradeAfter` semantics for MachineDeployments, so it seems like having consistent behavior around `UpgradeAfter` and `UpgradeOlderThan` for all resources that may own a Machine would definitely make sense.

Consistent implementation similar to `UpgradeAfter` for something like `KubeadmControlPlane` would be pretty straightforward, though `MachineDeployment` presents some challenges since it expects to handle rollouts over multiple MachineSets.

MHC would be a potential workaround to avoid the above MachineDeployment issue (as well as applying to bare MachineSets), but I do agree with @fabriziopandini that it feels like wrong. I'm not sure I like the idea of it being reconciled directly at an individual Machine level, either, though (bare Machines deleting themselves seems like a bad idea, and individual Machines wouldn't have enough context to know if it's safe to delete themselves).

When adding MHC remediation support into KCP, we added additional safeguards beyond what MHC provides with `MaxUnhealthy`, I'm wondering if there is something similar we can do on the MachineDeployment/MachineSet side that would allow for us to leverage the same owner-managed remediation policies without being tied directly to MHC for an implementation?

**Comment by fabriziopandini** [comment]
Agreed with Jason, this annotation should go on the entities who are responsible for managing set of machines,  MachinesDeployments, KCP, possibily MachinePools, and it does not make sense on a single machine.

Wrt to machine deployments, a possible way out is to add a `cluster.x-k8s.io/restartedAt:time` annotation into `spec.template.metadata` as soon as `UpgradeAfter` is past (this is the same trick we are using in the `clusterctl rollout` command)

**Comment by enxebre** [comment]
>Consistent implementation similar to UpgradeAfter for something like KubeadmControlPlane would be pretty straightforward, though MachineDeployment presents some challenges since it expects to handle rollouts over multiple MachineSets.

For either `rolloutAfter`  or `rolloutOlderThan` in machineDeployments we could introduce and additional logic which does not interfere with the existing one based on the spec changes, i.e the new one would leverage only the newest machineSet by scaling it out/in to satisfy maxSurge/minAvailable. I'll try to implement this. Does this make sense to you @detiber?

I still see no reason for not considering having this also in MHC so you can have this feature as part of your remediation input in environments where you might be running on machineSets.

**Comment by Arvinderpal** [comment]
Wondering if a combination of CronJob + existing rollout support in MD is the simplest way to accomplish this? 

Also, wouldn't we have to have some reconcile event occur on the MD for the rolloutAfter to work. The current time > rolloutAfter is not sufficient in itself. I assume we have or will need some periodic reconcile mechanism in place.

**Comment by JoelSpeed** [comment]
I think the problem with something like a cronjob is it that we want to obey some sort of disruption budget as it were. If all machines come online at once, then they would all go away at once with a simple script. So without some way to prevent that and delay some of the machine disruptions, I don't think a cronjob would be sufficient
