### ISSUE TITLE
Potential Bug: Pause Annotation blocks all reconciliation

### ISSUE THREAD

**Issue by relyt0925** [kubernetes-sigs/cluster-api#4473]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Set a MachineSet or MachineDeployment to have the paused annotation when it has machines provisioned (let's say 3 machines total).

Then delete one of the downstream machines. The actual replicas of the MachineSet remain at 3 because the pause annotation blocks all reconciliation. 

**What did you expect to happen:**
Depending on how you interpret pause: I would expect that even though creation of new machines/ scale down of machines are paused: If some entity successfully deletes downstream machines associated with a machineSet/machineDeployment the actual replica count still should be reconciled and accurate.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This popped up in implementation of this pr:
https://github.com/kubernetes-sigs/cluster-api/pull/4346

These two comments will give more supporting details into current and potential desired behavior:
https://github.com/kubernetes-sigs/cluster-api/pull/4346#issuecomment-809051472
https://github.com/kubernetes-sigs/cluster-api/pull/4346#issuecomment-809610682

**Environment:**

- Cluster-api version: 0.4
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by CecileRobertMichon** [comment]
IMO it might be valuable for _all_ reconciliation activities to be paused in some situations. For example, when the cluster is being moved from one management cluster to another. So it might not be a bug but rather a matter of making documenting the intended behavior very explicit. And possibly adding more robust tests around the behavior of each controller when pause is enabled.

**Comment by detiber** [comment]
I think even in the case where a resource is being moved from one management cluster to another, updating only the status (no mutating of spec or changes to the underlying resources being managed) should be fine, since the status is not copied to the new management cluster.

This would also give us the ability to do things like add a 'Paused' condition to the resource. Taking it a step further, we could define annotations that could help indicate why a resource has been paused, and some type of status for that operation, which could also be reflected in the conditions and/or kubectl output.

I think it would also have the added benefit for things like manual remediation of KubeadmControlPlane, where users could see when the manual remediation steps that have taken are sufficient to restore the cluster without having to potentially fight against the controller during those manual remediation steps.

**Comment by vincepri** [comment]
> This would also give us the ability to do things like add a 'Paused' condition to the resource.

Would this still be informational only? Or are you thinking to replace annotations with a condition? That might not work for `move` given that (as you mentioned) status isn't copied over, and it might cause the pause to be removed too early

**Comment by detiber** [comment]
> Would this still be informational only? Or are you thinking to replace annotations with a condition? That might not work for `move` given that (as you mentioned) status isn't copied over, and it might cause the pause to be removed too early

I was thinking informational only, I don't think we can get rid of the annotation unless we formalize it into a required field as part of the contract for the reasons you mentioned.
