### ISSUE TITLE
Revisit MachineDeployment.Spec.Strategy to be required

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#4525]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

`MachineDeployment.Spec.Strategy` is marked as optional https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/machinedeployment_types.go#L73

**What did you expect to happen:**
Any field which prevents the backend controller from operating and reconciling successfully should be required, regardless of we choose to default it for UX.

**Anything else you would like to add:**
Additionally this field is being defaulted by webhooks here https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/machinedeployment_webhook.go#L126-L151

We might want to continue the discussion in https://github.com/kubernetes-sigs/cluster-api/pull/4511#discussion_r619046482 and consider dropping this webhook logic and defaulting by using structural schema annotation instead.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
+1 on making this required in the next iteration, seems like a good improvement to the APIs.

> We might want to continue the discussion in #4511 (comment) and consider dropping this webhook logic and defaulting by using structural schema annotation instead.

-1 on this specific bit, I don't think we should default structs using json-based text in struct annotations.

**Comment by sbueringer** [comment]
I also agree with making this mandatory.

I would also like to keep avoiding defaulting structs via tags. I think it's "less magic" (sorry that's a bit vague) to just do the defaulting of everything apart from single values in the defaulting webhook instead of distributing it between the default webhook and tags and then you have to look at both places to know what the defaults are.

**Comment by CecileRobertMichon** [comment]
I'm +1 on defaulting everything in webhooks besides single values so we can have unit tests.

For `MachineDeploymentStrategy` specifically, we could do something like:

```
type MachineDeploymentStrategy struct {
	// Type of deployment.
	// Default is RollingUpdate.
	// +kubebuilder:default==RollingUpdate,validation:Enum=RollingUpdate;OnDelete
	Type MachineDeploymentStrategyType `json:"type,omitempty"`

	// Rolling update config params. Present only if
	// MachineDeploymentStrategyType = RollingUpdate.
	// +optional
	RollingUpdate *MachineRollingUpdateDeployment `json:"rollingUpdate,omitempty"`
}
```

And then default `MachineRollingUpdateDeployment` in the webhook based on the value of `MachineDeploymentStrategyType`. 

The other advantage of not doing this all in schema annotations is that we allow the user to specify `MachineDeploymentStrategyType` as `RollingUpdate` without specifying the `MachineRollingUpdateDeployment` values instead of having an all or nothing defaulting.

**Comment by enxebre** [comment]
Closing as per https://github.com/kubernetes-sigs/cluster-api/pull/4527#issuecomment-833602169
/close
