### ISSUE TITLE
Add IgnorePreflightErrors to KubeadmConfig types

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#4581]
**What steps did you take and what happened:**

Based on Slack thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1619121490147500

We saw that there were some fields missing which are in upstream kubeadm v1beta2. At a first glance we're missing:
* CertificateKey
* IgnorePreflightErrors

The theory in Slack was that these fields were added after we forked the types

**What did you expect to happen:**
I would have expected to be able to confgure (at least) `IgnorePreflightErrors`. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
Hopefully I can help with some context here:
1. Current version of Cluster API `KubeadmConfig` is derived from kubeadm API v1 beta1
2. Starting from v1alpha4, Cluster API KubeadmConfig types are decoupled from a specific version of the kubeadm API
3. Building on top of 2, it is now possible to implement some changes/cleanups in `KubeadmConfig` to improve usability

Accordingly
- `IgnorePreflightErrors` does not exists yet because this field was not present in v1beta1; I'm +1 to get this added, but we should be aware that this field will be no-op on older Kubernetes (this is not a problem IMO)
- `CertificateKey` was not present in v1beta1 too, however I don't think that we should add it to `KubeadmConfig` because we are not using automatic copy of certificates in Cluster API.

**Comment by sbueringer** [comment]
Makes sense to me. Is there already an issue open for v1alpha4 changes to the KubeadmConfig types or do we want to keep the current issue open to add the `IgnorePreflightErrors` field?

**Comment by fabriziopandini** [comment]
AFAIK there is no issue. It is ok to use this one for now.

**Comment by vincepri** [comment]
/retitle Add IgnorePreflightErrors to KubeadmConfig types
/assign @sbueringer 
/milestone v0.4
/priority important-longterm

We should add validation that this field should only be used with Kubernetes v1.22+

**Comment by fabriziopandini** [comment]
NOTE: Validation can be tricky for Machine deployments because the Kubernetes version to use might be on a different resource (while on KCP instead everything is on the same resource)
