### ISSUE TITLE
Failing conformance test

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api#4660]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
https://testgrid.k8s.io/provider-azure-master-signal#capz-conformance

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/capz-conformance-master/1396926343957975040

The test is showing green but is not running any tests since 05-21.  This appears to be a change introduced in the way the conformance image loads:

```
Digest: sha256:7ddbc3c3ba569e975f63b404abf798c106444735a66c7a6b50728a4d733fc007
Status: Downloaded newer image for gcr.io/k8s-staging-ci-images/conformance:v1.22.0-alpha.2.79_ebd61572c57947
2021/05/24 20:45:42 Saving results at /tmp/results
2021/05/24 20:45:42 failed to create log file /tmp/results/e2e.log: open /tmp/results/e2e.log: no such file or directory
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

1.22+

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dims** [comment]
@wilsonehusin @vladimirvivien @johnSchnake

**Comment by wilsonehusin** [comment]
posting for visibility -- the actual error quoted in the issue came from here:
https://github.com/kubernetes/kubernetes/blob/f545438bd347d2ac853b03983576bf0a6f1cc98b/cluster/images/conformance/go-runner/main.go#L63-L66

**Comment by wilsonehusin** [comment]
also generally the conformance image doesn't expect the results directory (i.e. `/tmp/results` for default) to be present in container because it's supposed to be a mounted volume

https://github.com/kubernetes/kubernetes/blob/f545438bd347d2ac853b03983576bf0a6f1cc98b/cluster/images/conformance/conformance-e2e.yaml#L71-L77

**Comment by wilsonehusin** [comment]
reading again on the actual docker command on Prow console -- 

```
command=/usr/bin/docker run --user 0:0 -v/logs/artifacts/kubetest/config/kubeconfig:/tmp/kubeconfig
  -v/logs/artifacts/kubetest:/output -v/logs/artifacts/kubetest/config/viper-config.yaml:/tmp/viper-config.yaml 
  -t --network=kind gcr.io/k8s-staging-ci-images/conformance:v1.22.0-alpha.2.79_ebd61572c57947
  /usr/local/bin/ginkgo -nodes=1 -slowSpecThreshold=120 /usr/local/bin/e2e.test -- 
  --viper-config=/tmp/viper-config.yaml --num-nodes=2 --kubeconfig=/tmp/kubeconfig
  --provider=skeleton --report-dir=/output --e2e-output-dir=/output/e2e-output
  --dump-logs-on-failure=false --report-prefix=kubetest.
```

i believe the intent here is to execute the ginkgo binary, but as of https://github.com/kubernetes/kubernetes/pull/99178, the conformance image actually [defines `ENTRYPOINT` to be the conformance binary](https://github.com/kubernetes/kubernetes/blob/f545438bd347d2ac853b03983576bf0a6f1cc98b/cluster/images/conformance/Dockerfile#L43).

as @CecileRobertMichon pointed out in Slack, the following code is where the action happens. seems like the resolution is to use `--entrypoint /usr/local/bin/ginkgo` instead of executing it as if it's the first arg for the command.

https://github.com/kubernetes-sigs/cluster-api/blob/fca52981fe0afcca91a0e014a444f703d83c64fc/test/framework/kubetest/run.go#L157-L167
