### ISSUE TITLE
Improve log streaming for E2E tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4684]
**User Story**

As a developer I would like that the E2E framework streams all the logs from my controllers during a test

**Detailed Description**

When we install providers using the E2E test framework, we start a go routine that streams logs from the pods hosting our CAPI/Providers controllers.

However, now that our test are getting more and more complex, it happens that the pods hosting CAPI/Providers controllers gets destroyed/re-created, and under this circumstances the streaming code in the go routine fails. AFAIK this currently applies to two test spec:

- clusterctl upgrades 
- self hosted upgrades

The main difference between the two use cases is that within clusterctl upgrades we are controlling the process, so the test framework creates go routines streaming logs from the new pods (while the old one are failing). 
Instead during self-hosted upgrades it is Kubernetes taking care of scheduling a new instances of the controllers while machines are being rolled out and the test framework currently does not creates new go routines when this happens (so we are missing logs from the new controller instances).

/kind feature
/area testing

/milestone Next

**Comment by chrischdi** [comment]
@fabriziopandini : after taking a look and playing a bit around:

* For `clusterctl upgrades`: as you mentioned this is currently not an issue because we start another watch go routine which then streams the logs of the new pods
* For `self hosted upgrades`: If I got it right, there is no test for self hosted upgrades 🤔 
  * The WIP implementation at #7007 may work for for a self hosted upgrade scenario or (at least does for recreated pods of the deployment, I would have to check if the watch stays alive during the upgrade).

So because we currently don't have a test: should this issue even get this implemented or just closed?

Or should we add a test which does a self-hosted upgrade?

**Comment by fabriziopandini** [comment]
/close
Let's make sure we keep this in the radar while implementing the test for self hosted upgrades
