### ISSUE TITLE
The cluster status is stuck in "Deleting"

### ISSUE THREAD

**Issue by wuli-jessica** [kubernetes-sigs/cluster-api#4685]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Hi. When I created the workload cluster, I encountered the "providerClient authentication err: Authentication failed" because I wrote something wrong in clouds.yaml , and when I executed "kubectl delete" to delete the cluster, the command did not return and the cluster was stuck in "Deleting" status, check the log, the deletion process also meets the "Authentication failed" error. How does cluster-api handle this situation? Is this a bug? Are you considering fixing it or accepting some code contributions?

**What did you expect to happen:**
the cluster be deleted after delete.

**Environment:**

- Cluster-api version: v0.3.15
- Minikube/KIND version: 
- Kubernetes version: (use `kubectl version`): 1.20
- OS (e.g. from `/etc/os-release`): Ubuntu20.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
Contributions are always welcome!

As far as I understand this problem, most probably this issue has different connotations on the various infrastructure providers, because CAPI "core" does not handle infrastructure credentials at all. 
So my suggestion is to close this issue here and open a new one in the repository for the infrastructure provider of your choice
