### ISSUE TITLE
Make the workflow for the creation of the external cluster pluggable

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api#479]
Currently, the create workflow that clusterctl uses minikube to standup an "external" cluster (aka the bootstrap cluster) or it may rely on an existing cluster as the "external" cluster.  The minikube workflow served as a good start point for a proof of concept.  The request is to make the creation of the external cluster pluggable and allow experimentation by vendors.  Eventually, a good best practice should emerge among the various vendors and we can share it among all providers.  This topic was mentioned in #157 and discussed in the lifecycle's google group.

- [ ] Break down the workflow stages for creation of the external cluster
- [ ] Identify an approach to validate the stages are complete
- [ ] Create a new interface for the "externalProvider".  This interface should allow for pluggable providers, even providers that are remote services (e.g. a non-kubernetes api server)
- [ ] Prototype an example

**Comment by jessicaochen** [comment]
Pulling thoughts from email to this issue.

My 2c:
> Agreed that all that matters is that there is an external control plane. Feel free to correct me but the scenario you described (provision external cluster in some vendor specific way) can already be achieved with the current abstractions.

> The ClusterDeployer already takes a ClusterProvisioner interface and uses it to create/connect/cleanup the external cluster. https://github.com/kubernetes-sigs/cluster-api/blob/master/clusterctl/clusterdeployer/clusterdeployer.go#L43

> (Option A)
One could implement that ClusterProvisioner interface in a vendor specific way. Specifically, where Create() does nothing and GetKubeconfig() asks "is there an external cluster and is properly configured for cluster api's use?" and grabs the kubeconfig or errors (if appropriate).

> (Option B)
One could implement that ClusterProvisioner interface in a vendor specific way. Specifically, where Create() runs the vendor-specific way of creating an external cluster and GetKubeconfig() grabs the config.

> (Option C)
The vendor tool creates or fetches the external cluster in a vendor specific way first and then passes the kubeconfig for it into clusterctl via https://github.com/kubernetes-sigs/cluster-api/pull/442 .

Response from Lubomir I. Ivanov neolit123@gmail.com :
> i'm not deep enough into the Cluster API, but i participated in
yesterday's "cluster-api-cloud-provider-vsphere" meeting.
we've agreed that we should strive for having a well abstracted,
unified way for all cloud providers in the cluster API and minimize
the work that cloud providers have to do - creating separate tooling
if and/or forking.
this should apply for all CPs and it's very important to not have
fragmentation early in the project, because this fragmentation can
only exponentiate over time.

> so it seems to me that "Option C" is the way to go.
but i would defer to others for opinions.

**Comment by Lion-Wei** [comment]
@sflxn @roberthbailey Is anyone working on this? I'd like to be participate in this work if you don't mind. : )

**Comment by roberthbailey** [comment]
I'm going to dupe this one with https://github.com/kubernetes-sigs/cluster-api/issues/554, since it has a lot of overlap.
