### ISSUE TITLE
clusterctl installs wrong version of CAPV

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api#4889]
**What steps did you take and what happened:**
I created a new kind cluster and ran `clusterctl init --infrastructure vsphere` and the output of the CAPV controller showed it installed manager 0.6.6.

**What did you expect to happen:**
I expected 0.7.8 to be installed.

**Anything else you would like to add:**
We fixed this using `clusterctl init --infrastructure vsphere:v0.7.8`.

**Environment:**

- Cluster-api version: `clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.20", GitCommit:"ea9dc4bdc2a9938325aab3817ece3e654873aaab", GitTreeState:"clean", BuildDate:"2021-06-30T22:21:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}`
- Minikube/KIND version: `kind v0.11.1 go1.16.4 darwin/amd64`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-03-11T06:23:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): macOS 10.15

CC @randomvariable 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by randomvariable** [comment]
This is from a zoom call we had, so happy to take a look. Just wanted it filed as an issue first.

/assign

**Comment by randomvariable** [comment]
Also, can confirm this was clusterctl v0.3.20

**Comment by CecileRobertMichon** [comment]
@randomvariable I think I know what the issue is... In #4856, I added a check that looks at metadata and gets the release series for the current contract, assuming 1 release series per contract (which is the case for core CAPI). CAPV has 2 minor releases for v1alpha3 which are documented in the metadata.yaml file of v0.7 and it happens to fetch the first one which is 0.6.

A quick way to fix this is to only put the latest v1alpha3 release in the CAPV 0.7 release metadata. A better long term fix is to fix clusterctl to get the latest contract series if there are multiple (which will require a PR + backport + release)

**Comment by vincepri** [comment]
> A quick way to fix this is to only put the latest v1alpha3 release in the CAPV 0.7 release metadata. A better long term fix is to fix clusterctl to get the latest contract series if there are multiple (which will require a PR + backport + release)

This is probably a good thing to do, @ykakarap would you be interested in tackling this?

**Comment by ykakarap** [comment]
I will take it :) 

/assign
