### ISSUE TITLE
Make ClusterController ready for ClusterClass

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#4909]
**Detailed Description**

As an initial activity for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md) we should make the ClusterController "tolerant" of following use case:

- A cluster with Spec.Topology != nil (a managed cluster), with spec.infrastructureRef and spec.controlPlaneRef nil

This happens immediately after creating a managed cluster, while waiting for the topology to be generated; in this case, the controller should log a message, and return without error; the cluster object will be processed again after the topology is generated (including assigning a value to the above fields).

**Anything else you would like to add:**

This could be implemented only after is https://github.com/kubernetes-sigs/cluster-api/issues/4908 completed.

Also, In a follow up iteration we might consider to add a condition to better surfaces this state; I'm considering if to open a separated issue for discussing ClusterClass/Managed topologies conditions.

/kind feature

**Comment by srm09** [comment]
@fabriziopandini I have been thinking about this issue. Currently, if either of the `spec.InfrastructureRef` or `spec.ControlPlaneRef` is `nil`, we just return without any error. And the idea is in the subsequent reconcile loops when the value is set, we will handle the reconciliation cases then.

The idea behind making the cluster controller more acceptable is
1. to punt the reconciliation when these references are set &
2. to expose a condition which reports this state. (Because the remaining logic would work as-is, once the two specs are set by the topology reconciler.

Is that the idea here? And we can add a note to tackle part 2 with the CC/Cluster topology condition issue.

**Comment by fabriziopandini** [comment]
The goal of this issue is to allow a managed Cluster to exists without spec.InfrastructureRef and spec.ControlPlaneRef (which is the short timeframe while we wait for the topology to be reconciled).

Now, AFAIK a Cluster can exists without spec.ControlPlaneRef (this is a legacy thing from before ControlPlane provider were introduced)

I'm not sure the same applies to spec.InfrastructureRef. What happen if a Cluster does not have this value?
We should make sure that a managed cluster can reconcile without errors in this state (like you are saying, punt the reconciliation).
Note: instead it will be fine to fail with error if the cluster is not managed

I also agree we should defer surfacing this state via condition to a follow up issue where we define all the conditions for ClusterClass and managed topologies.
