### ISSUE TITLE
Clear documentation for machine and cluster actuator interface

### ISSUE THREAD

**Issue by anfernee** [kubernetes-sigs/cluster-api#505]
The machine actuator interface is not defined clearly here: https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/actuator.go#L25 It's confusing to the implementer of the interface about the expected behavior. The same applies to cluster actuator. 

For instance: 
- Existed
  - What is existing? VM is created, or started, or network stack is ready, or the service is started and healthy? 
- Create and Update
  - it looks like both Update and Create are idempotent, then what is the difference between them. https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L137 and https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L148  

Also, is it a good idea to put the idempotent burden to actuator implementer? especially for Create. Create does the whole lot of thing, and doing it idempotent isn't a trivial job. If the VM doesn't exist, it's fine. However, if the target VM exists, what should we do? Those logics are very common to all different actuators. Should we handle this in in controller? Actuator should just become a stateless cloud provider abstraction.

**Comment by dlipovetsky** [comment]
These are great questions. Since what the methods do differs among providers (e.g. I'm implementing a provider that targets pre-existing machines, so `Create` only deploys software), I think the provider office hours could be a good place to discuss (any proposed changes would be presented at the working group meeting).

Here's a gdoc for jotting down thoughts: https://docs.google.com/document/d/1PTAWB8jC1PTx6K2-emvi7Mmo7ZVtLIE11rNEJJm2TJw/edit#

**Comment by dlipovetsky** [comment]
Here's a relevant discussion about the Cluster actuator interface: https://github.com/kubernetes-sigs/cluster-api/pull/190#discussion_r189697124
