### ISSUE TITLE
Add a Predicate for skipping clusters without Topology in the topology/ClusterReconciler

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5120]
**Detailed Description**

In the topology/ClusterReconciler we are currently returning if a Cluster has Topology nil

https://github.com/kubernetes-sigs/cluster-api/blob/1fb53c85d7ffd25f9e2fe0004be006a31ff51d58/controllers/topology/controller.go#L97-L101

This could be transformed into a predicated to be added in https://github.com/kubernetes-sigs/cluster-api/blob/1fb53c85d7ffd25f9e2fe0004be006a31ff51d58/controllers/topology/controller.go#L59-L71

Thus entirely avoiding to trigger reconcile

/kind feature

**Comment by sbueringer** [comment]
@ykakarap Are you currently working on the issue? Should we potentially make it a help wanted issue? I think it would be great issue for new contributors.

**Comment by ykakarap** [comment]
Good idea to make it a good first issue. 

/good-first-issue
/help

/unassign

**Comment by budhirajamadhav** [comment]
Hey @fabriziopandini @sbueringer I was trying to transform the above-mentioned: ` if cluster.Spec.Topology == nil { 
 	return ctrl.Result{}, nil 
 } ` into a predicate.  
So, since the `"sigs.k8s.io/controller-runtime/pkg/predicate"` package isn't imported in the `cluster_controller.go` file, should I import the package and write the predicate there only(inline, [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/topology/cluster_controller.go#L81)) or write it somewhere else and then import that?

Also, if I am not wrong the predicate should return "true" when the "topology is found nil". Or otherwise?

**Comment by ykakarap** [comment]
@budhirajamadhav You will need to add a new predicate definition in the file here: https://github.com/kubernetes-sigs/cluster-api/blob/main/util/predicates/cluster_predicates.go

In the above file define a function called `ClusterIsManagedTopology` that returns `predicate.Funcs` (refer to other predicates in the same file for an example).

The predicate should be considered true if `topology is NOT nil` and false otherwise.
The `"sigs.k8s.io/cluster-api/util/predicates"` package is [already imported in controller](https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/topology/cluster_controller.go#L33) so you should be able to use the new predicate without having to import any new packages.

**Comment by budhirajamadhav** [comment]
Ok, Thanks @ykakarap. :,)
