### ISSUE TITLE
Error when updating spec.machineTemplate.infrastructureRef.apiVersion to new version v1alpha4

### ISSUE THREAD

**Issue by rodrigoscna** [kubernetes-sigs/cluster-api#5130]
**What steps did you take and what happened:**
I upgraded my cluster from v1alpha3 to v1alpha4 according to bellow table:
```
NAME                    NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm       capi-kubeadm-bootstrap-system       BootstrapProvider        v0.3.22           v0.4.1
control-plane-kubeadm   capi-kubeadm-control-plane-system   ControlPlaneProvider     v0.3.22           v0.4.1
cluster-api             capi-system                         CoreProvider             v0.3.22           v0.4.1
infrastructure-aws      capa-system                         InfrastructureProvider   v0.6.8            v0.7.0
```

When I tried to update the field `spec.machineTemplate.infrastructureRef.apiVersion` from v1alpha3 to v1alpha4 on KubeadmControlPlane resource, the API gave me the following error: `The KubeadmControlPlane "****" is invalid: spec.machineTemplate.infrastructureRef.apiVersion: Forbidden: cannot be modified`

**What did you expect to happen:**
The API should allow me to update the infrastructureRef according to the new Cluster API ref version.

**Environment:**

- Cluster-api version: upgrading from v0.3.22 to v0.4.1
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): v1.20.4
- OS (e.g. from `/etc/os-release`): N/A

/kind bug
/area api
/area provider/aws
/area control-plane

**Comment by vincepri** [comment]
@fabriziopandini Shouldn't we have caught this in the e2e tests?

**Comment by vincepri** [comment]
Also we might have to update the reference to the current contract like we do in other places.

**Comment by fabriziopandini** [comment]
@vincepri  
> Also we might have to update the reference to the current contract like we do in other places.

I agree the main problem here is that KCP controller is not taking charge of upgrading its own reference to the infrastructure machine (which in turn requires to relax mutability). 

> Shouldn't we have caught this in the e2e tests?

In our E2E tests we are upgrading the providers from v1alpha3 to v1alpha4, then executing an operation (a Kubernetes Version upgrade) on an existing workload Cluster to check it is still manageable by CAPI.

We are not upgrading a Cluster from v1alpha3 to v1alpha4, because this already happens "automatically" inside the management cluster: storage versions are converted by API machinery/controllers, API version and references are upgraded by controllers calling `ConvertReferenceAPIContract`.

Unfortunately KCP was not upgrading its reference, and being v1alpha3 still working in the system and compatible with v1alpha4 for the infrastructure machine contract, no error has been surfaced till now.

**Comment by sbueringer** [comment]
@fabriziopandini I'm a bit confused about our clusterctl e2e test. It seems to start with v1alpha3, but the final KCP resource seems to have an upgraded ref:
* https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1429727011512782848/artifacts/clusters/clusterctl-upgrade-axusr4/clusterctl-upgrade-lu5s8f-cluster-template.yaml
* https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1429727011512782848/artifacts/clusters/bootstrap/resources/clusterctl-upgrade-xneggz/KubeadmControlPlane/clusterctl-upgrade-axusr4-control-plane.yaml

I'm probably missing something.

**Comment by fabriziopandini** [comment]
@sbueringer that is something to be investigated. I searched for ConvertReferenceAPIContract in KCP code I did not find it used anywhere. I will made a more detailed search given your evidences but I'm wondering how this could work with the webhook preventing the field to be updated 🤔

**Comment by sbueringer** [comment]
@fabriziopandini Yeah something is strange here :). I can take over and step through the e2e test if you want.

**Comment by sbueringer** [comment]
Okay simple explanation. The files I linked above are from different clusters. Our clusterctl upgrade test uses two clusters: one provisioned with v1alpha4 to host the old/new versions of providers and one workload cluster provisioned by the old/new providers.

So tl;dr in our upgrade test:
* the cluster on which the providers are running and upgraded is provisioned with v1alpha4 and has a v1alpha4 KCP (including machine infra template v1alpha4)
* the workload cluster of those providers is provisioned with v1alpha3 and has a v1alpha3 KCP (including machine infra template v1alpha3). And it stays on v1alpha3 during the test because we never trigger the conversion.
