### ISSUE TITLE
Ability to manage core cluster deployments and daemonsets prior to upgrading a ClusterClass managed cluster

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#5230]
**User Story**

As a vendor of a product using Cluster API I would like to manually control kube-proxy and CoreDNS deployments as well as additional machine labels during a ClusterClass managed cluster upgrade. In this environment, there's no registry from which etcd, coredns, etc... OCI images can be retrieved from, but all images are baked into the machine images using https://github.com/kubernetes-sigs/image-builder . We use the opt-out annotations of KCP to allow us to manage these addons ourselves.

Because each OS image only contains the images specific for that version, we need to ensure that the correct CoreDNS deployment and kube-proxy daemonset is applied. We use per-Kubernetes-version node selectors to target the applied pods for each machine with the matching k8s version used in image builder.  

**Detailed Description**

Related to #5222 

This is a specific use case, but you could in theory generalise this into the need for lifecycle hooks for various moments in the lifecycle of a cluster, with the specific one being the moment when the version field is changed in the clusterclass and before KCP does any change to realise that state.

**Anything else you would like to add:**

I'm also wondering in this specific use case, we should be doing some of the above in KCP/ClusterClass anyway:
- Apply a version label to every machine
- Create k8s version specific CoreDNS deployments and Kube-Proxy DaemonSets with appropriate node selectors.

/kind feature

**Comment by fabriziopandini** [comment]
Recap of the specific use case:
- Cluster with KCP with annotations to opt-out from default kube-proxy and CoreDNS lifecycle management.
- It is required to have a hook to trigger external lifecycle management of those components before Cluster upgrade.

WRT to detailed description, while I understand that this can fall into the bucket of a generic idea of Lifecycle hooks, I personally think we should scope down the problem because in a CAPI cluster there are many objects and each one has it's own lifecycle. it is impractical to tackle all of them together.

A tricky point is also the fact that Cluster API does not owns the lifecycle of the control plane, which is change of a provider (KCP in this example, but it could be anything). Cluster with ClusterClass/Managed topologies could provide a solution to this point, but the solution won't work with unmanaged Clusters. Is this acceptable for this use case? Is this acceptable as a generic approach (lifecycle hooks only on managed topologies at Cluster level)?

Restricting the scope will also help in starting to figure out where those hooks should implemented (in which controller), and how much this can be invasive on the existing code.

/milestone v1.0

**Comment by fabriziopandini** [comment]
[The ](https://github.com/kubernetes-sigs/cluster-api/pull/6418) is going to provide the foundation for this work; after this is merged we should check if there are missing items to be addressed of if we can close this issue
/remove-lifecycle stale

**Comment by fabriziopandini** [comment]
@randomvariable can we re-assess requirement here now that runtime SDK is available
/triage accepted
