### ISSUE TITLE
MachineSet version changes, upgrading from v1alpha3 to v1alpha4 

### ISSUE THREAD

**Issue by abhinavnagaraj** [kubernetes-sigs/cluster-api#5405]
**What steps did you take and what happened:**
Launch a cluster in v1alpha3 (capi v0.3.19), with one MachineDeployment containing 2 replicas and with strategyType='RollingUpdate'.

Upgrade the cluster to v1alpha4(capi v0.4.0), without any changes in MachineDeployment spec.

This results in the creation of new MachineSets and hence new machines.

**What did you expect to happen:**
If there is no change in the MachineDeployment spec, there should be no rolling-upgrade of MachineSets.

**Anything else you would like to add:**
In v1alpha4 MachineDeployment and MachineSet template versions(`spec.template.spec.version`) is expected to be prefixed with a 'v'.
A Default() function in MachineDeployment webhook adds this prefix - [#4670 ](https://github.com/kubernetes-sigs/cluster-api/pull/4670)
But this is missing in the MachineSet webhook.

**Environment:**

- Cluster-api version:v0.4.0
- Minikube/KIND version:v0.11.1
- Kubernetes version: (use `kubectl version`):v1.21.1
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by abhinavnagaraj** [comment]
@ykakarap Yes, these steps are correct. Now, if we scale the MachineDeployment with API version `v1alpha4`, we would expect the corresponding MachineSet(`v1alpha4`) to also scale up. Instead, the MachineDeployment version updates to have the prefix 'v'. A new MachineSet is launched with the version set to have prefix 'v'. The old MachineSet finally reconciles to have 0 replicas, but does not get deleted.

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale
@sbueringer to re-assess

**Comment by sbueringer** [comment]
@fabriziopandini To summarize:
* In a regular CAPI update we update core CAPI, the bootstrap, the controlplane and the infra provider.
* for this issue it's relevant that either the bootstrap provider or the infra provider used in the MachineSet is updated
* when the MachineSetReconciler updates either of the references in the MachineSet because of that, this issue is automatically mitigated (because an update to one of the refs, automatically adds the `v` prefix to the version field)

In my opinion now the issue can only occur if someone upgrades only core CAPI, without upgrading the bootstrap or infra provider. In my opinion that's as very uncommon case. So I personally wouldn't try to add handling for that case. Especially as we didn't get any reports that it is an issue. 

(The PR which closed this issue added the v-prefix defaulting in the MS webhook, which made it possible for the reconciler to automatically mitigate)

**Comment by sbueringer** [comment]
If we want to mitigate that edge case ,we could add code which adds the prefix to the version field during each reconcile (if necessary).

I think I would prefer avoiding that, if we don't have to.

**Comment by fabriziopandini** [comment]
> the issue can only occur if someone upgrades only core CAPI, without upgrading the bootstrap or infra provider. 

That's a use case we are not supporting, given that clusterctl ensures that all the providers move up at the same time
I agree we should not fix

**Comment by sbueringer** [comment]
> > the issue can only occur if someone upgrades only core CAPI, without upgrading the bootstrap or infra provider.
> 
> That's a use case we are not supporting, given that clusterctl ensures that all the providers move up at the same time I agree we should not fix

As discussed in the grooming on 18th February, let's close this issue based on that it's an unsupported use case to only upgrade core CAPI.
