### ISSUE TITLE
Are CAPI conditions fully kstatus compatible?

### ISSUE THREAD

**Issue by matthchr** [kubernetes-sigs/cluster-api#5472]
If using CAPI with a tool like [fluxcd](https://github.com/fluxcd/flux2), which internally uses [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus), there isn't a good way for kstatus to know if the CAPI resource is in a terminal state or if waiting longer may result in reconciliation driving the resource to `ready=true`.

As per the [kstatus documentation](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#conditions), they have recommended condition guidance, but they also understand the `Ready` condition which is what CAPI uses. For the `Ready` condition though, they specifically state:

> There is no way to determine if a resource with the Ready condition set to False is making progress or is doomed.

CAPI's conditions have a `Severity` which solves this problem I'm pretty sure. It doesn't solve it in a way `kstatus` understands though. kstatus wants a `Stalled=true` condition.

This maybe really comes down to the fact that the conditions guidance given by Kubernetes upstream is pretty vague. There are some commonly adopted conditions (`Ready`), but no guidance on the correct way to convey this "can I progress" information.

**My question is:** is the CAPI team aware of this issue? Are there any plans to either make CAPI do what kstatus wants, or make kstatus understand what CAPI does?

A random aside: I happen to prefer CAPIs pattern to what kstatus expects (splitting "will this progress" and "what state am I in" across multiple conditions feels awkward to me), but if that's what the community/ecosystem _wants_...

**Comment by matthchr** [comment]
See some related discussion here: https://github.com/fluxcd/flux2/issues/1254

**Comment by fabriziopandini** [comment]
I took a look at https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#conditions, and it seems that it is trying to solve the very same problem CAPI addressed with Severity, that is to determine if Status=false but we are making progress or we are blocked somehow.

However, I'm kind of skeptical about the solution because
- It addresses this problem only for the Ready condition, which is limiting (other conditions have the same requirement too!)
- It requires two additional conditions, Reconciling and Stalled, and there is no guarantee that the community will adopt this new pattern widely

Given that, I'm currently -1 to do further steps in this direction

**Comment by fabriziopandini** [comment]
/close
As per the comment above I don't see us moving in this direction, we can eventually reconsider if there is consensus
