### ISSUE TITLE
Add documentation for ClusterClass controller

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5502]
Add a page to the controllers section of the Cluster API book that covers the high level workings of the [clusterClass controller](https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/topology/cluster_controller.go). 

The documentation should minimally include:

1) A diagram showing the workings of the Cluster Controller in the Topology package.
1) A list of the main responsibilities of the Cluster Controller in the Topology package.

Good examples of controller pages to emulate are [the main Cluster controller page](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html) and the [MachineDeployment controller page](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine-deployment.html)

c/f https://github.com/kubernetes-sigs/cluster-api/issues/5475

**Comment by klxfeiyang** [comment]
Thanks @ykakarap for working with me to create a draft activity diagram of the clusterclass topology controller attached below.  It focuses on the reconcile loop of the controller, in line with documentation of the other controllers.  I will work on translating this into a `plantuml` diagram.   

![Screen Shot 2021-10-29 at 16 21 14](https://user-images.githubusercontent.com/42789705/139513552-466cb23b-2d1c-4333-b07f-c3d36d8d5b3a.png)

I actually really like `plantuml`, since it can be source controlled.  IMO, it's much easier for other folks to maintain and modify later, but it's probably not as convenient to sketch out a quick idea.

Thanks @sbueringer for sharing the high level architecture diagram.  This may be worthwhile to include as well.   Let me know if there are other diagrams in existing materials that would be worthwhile to include as part of this section.

**Comment by sbueringer** [comment]
@klxfeiyang I'm not aware of other diagrams for the ClusterClass controller.

**Comment by fabriziopandini** [comment]
@sbueringer @klxfeiyang is I see a PR has been merged.
Can we close the issue now?

**Comment by sbueringer** [comment]
Yes, looks good to me.
/close
