### ISSUE TITLE
Provide a way to exclude certain resources when pivoting a cluster

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#556]
Currently when pivoting a cluster all resources included in the provider config are created on the target cluster. Ideally there should be a way to exclude certain resources (either through a predefined annotation or a label) to allow for certain marked resources to be excluded from the pivot (and potentially also from the generated configmap).

Use case for this is currently with the AWS provider, we would like to create a secret that is used only on the bootstrapping cluster to provide temporary AWS credentials to be used for spinning up the target cluster. When the resources are pivoted over to the target cluster we no longer need the temporary credentials, since we can leverage the IAM instance profile attached to the instance running the pivoted components.

**Comment by vincepri** [comment]
@sflxn You can `/lifecycle active` to mark items you're working on.

**Comment by sflxn** [comment]
@detiber Can you describe how you are feeding this secret into clusterctl just so I don't miss anything?  I assume you're adding that to provider-components.yaml?

**Comment by vincepri** [comment]
I'll try to answer best I can 😄, in the AWS provider, the secret is generated through an external util `clusterawsadm` and then it's generated in provider-components though kustomize.

**Comment by sflxn** [comment]
You know what, I thought I had figured out two ways of doing it and was proceeding down the simpler of the two paths when a 3rd, more obvious and simpler path came up so I am going to put it here for discussion instead of continuing down the path I was going.

*Mutating adminission webhook*
---
Pros:

- It will be generic solution (not just specific to clusterctl)
Cons:
- More development than option 2
- The webhook must be up and running before resources are applied to the target cluster.
- More deployment and configuration steps needed to add to the target cluster
- Must deal with certificates

Exclusion tagging:
- Add exclusion info to the webhook configuration
- Add annotations to the resource to mark the exclusions

* Mutating resouces within clusterctl before applying*
---
Pros:
- This approach is quite simple.

Cons:
- Resources are applied to the target cluster using multiple methods and any exclusion must be applied separately for each type.  For instance provider-components and machines will require different checks and mutations.
- Will be a clusterctl specific solution

Exclusion tagging:
- Clusterctl command line option - best if small number of exclusions.
- Separate yaml file that contains more complex types of mutations
```
clusterctl create cluster -p provider-components.yaml -x "secrets/myaws-secrets"
clusterctl create cluster -p provider-components.yaml -xf exclusions.file
```

Exclusion method:
- For string resource (provider-components.yaml), string manipulation.  There doesn't appear to be a way to decipher the resource type name and resource names in the file without knowing the types ahead of times.  For instance,
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinesets.cluster.k8s.io
```
In the above, there is no way to decode the name or the type ahead of time.  For this specific resource, we can import the types into clusterctl to decode, but if we're talking about an arbitrary resource type, I don't know of a way to do it.
- For cluster API resources, direct access type members and empty out values

*Introduce another input resource file to clusterctl*
---
Pros:
- Brain dead simple.  Instead of some complex programmatic approach, we just use a mechanical mechanism.  We can make clusterctl know this is a resource file for exclusion and simply not apply it to the target cluster.  There can be modification to clusterctl but not much.

Cons:
- Yet another file input.  Puts the onus on the provider's build process to create yet file.

---
Initially, I investigated prototyping option 2, "mutating resources within clusterctl before applying", but the inability to query type names and resource names when reading provider-components.yaml and be forced to use string manipulation made me brainstorm with a colleague (@dougm) and realized the KISS solution was option 3.  I halted the early development of option 2 to see if this is reasonable to the community, especially @detiber, the original requester.

**Comment by detiber** [comment]
@sflxn :+1: to introducing a new resource file, I'm not sure why it hadn't occurred to me sooner. This additional file will need to also be passed in for the `delete` command to allow for the temporary cluster to be able to access the same type of credentials that the bootstrapping cluster would need.

**Comment by vincepri** [comment]
I like the idea of having a different file feed to `clusterctl`. It's clean, straightforward and there should be a way for the pivot phase to "see" these resources and not pivot them. 

One question that I have is how do we deal with dependency between resources. For example in the AWS provider, we have a secret that we don't want to pivot but this is referenced in the provider components as a volume.
