### ISSUE TITLE
[cabpk] Ability to configure hostname

### ISSUE THREAD

**Issue by omniproc** [kubernetes-sigs/cluster-api#5562]
**User Story**

As a service provider I would like to manualy configure the hostname of every `Machine` / K8s Node to align with DNS name / hostname definitions of my enterprise and to have predictable, consistent hostnames when re-deploying CAPI managed K8s clusters.

**Detailed Description**

Currently - as far as I was able to track this - the GenerateName function of CABPK is responsible to generate a name for every `Machine`. As far as I can tell CABPK is responsible for generating the _Cloud-Init_ config from the `KubeadmConfigTemplate`. The process looks something like this (I wasn't able to find the source, happy if someone can point me to it):

- Get the `metadata.name` of the `MachineDeployment` and use it as a prefix for the hostname's of the generated `Machine` resources
- Call GenerateName function in CABPK to generate a random number that will be added as a suffix so every `Machine` has a unique hostname
- Generated hostname is used for other CAPI resources and also by some CAPI providers for their resources
- Generated hostname is passed to the generated _Cloud-Init_  and can be referenced inside the provisioned `Machine` (concrete implementation depends on the CAPI provider used, e.g. in CAPV this results in `VsphereMachine`) by `ds.meta_data.hostname`. Also it can be referenced as `ds.meta_data.hostname` inside `KubeadmConfigTemplate` which is usualy done by CAPI providers to setup the actual hostname of the generated K8s node. E.g. you'll see something like this in the CAPV default template:

```yaml
preKubeadmCommands:
  - hostname "{{ ds.meta_data.hostname }}"
  - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
 ```

CAPI providers also often use the generated hostname to name other intermediate resources similar so the reference to the `Machine` object becomes clear by looking at the `metadata.name` property of a resource.

As a service provider using CAPI I'd like to be able to assign pre-defined hostnames to K8s nodes deployed by CAPI. By doing so I have to make sure a hostname is unique within a deployment. I see two possible ways down the road of implementing this, a short term fix that would help people to achieve this goal and a long term solution which would require way more work.

1. For a **long-term solution** I'd envision a a IPAM-like definition of available hostnames in a YAML array, e.g. `HostnamePool: ['hostname1', 'hostname2', 'hostname3']` that is then assigned to a `MachineDeployment` so any provisioned `Machine` can consume available hostnames from that pool. If the pool is depleded, `Machines` will wait until a name is available again. By doing so however we'd also need a way to map those hostnames to IPs that the node should use (which is the reason why I think this is rather a long-term solution). 
The definition could be expanded to something like `DnsPool: [[hostname: hostname1, ip: 172.16.0.11], [hostname: hostname2, ip: 172.16.0.12], [hostname: hostname3, ip: 172.16.0.13]]` so that a `Machine` can then reference a element of that array and assign the hostname and IP to the K8s node that's being deployed. So there's a dependency on static IP-assignment which is currently not handled by CABPK.

2. As a intermediate, **short-term solution** it would be great to be able to patch the generated hostname of the `Machine` object after the resource has been generated. Since all providers I checked reference that resource when going for the hostname a flag on the `MachineDeployment`, something like `StaticHostname: true` could be implemented to have the`Machine` objects generated by that `MachineDeployment` wait until the hostname is patched. This would cause all resources refering to that hostname to wait before using it to name other resources (which is problematic because K8s metadata.name is immutable). Since it's a new flag it should be backward compatible.

**Anything else you would like to add:**

There are many issues, e.g. #1579, that have asked for this in the past. Unfortunatly they all have been killed due to k8s-ci-robot's exitement for ticket-closing (I get it - but it's still annoying, imho) or due to lack of feedback from the issue author. I'm dedicated to track this until a decision / solution is found. So, let's try this again. It would be awesome if this feature could be added since I see a _huge_ demand in enterprise for this.

/kind feature

**Comment by enxebre** [comment]
>As a service provider I would like to manualy configure the hostname of every Machine / K8s Node to align with DNS name / hostname definitions of my enterprise and to have predictable, consistent hostnames when re-deploying CAPI managed K8s clusters.

Hey @omniproc to make sure we can have a productive discussion and find a way to help, can you elaborate as much as possible on the particular use case you are interested in that is not possible to achieve today?

Particularly for vSphere it seems the Machine name is made available to the metadata via [1] and [2] that then can be used by the `preKubeadmCommands`.
cc @randomvariable @srm09 @yastij 

[1] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/d455fe437d46b0fad5e7c65b82d2803fd2f2c1fb/controllers/vspheremachine_controller.go#L400
[2] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/pkg/services/govmomi/service.go#L242
[3] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9a88c652fba6bb2ea1b7faf8a301796cba6e9a60/pkg/services/govmomi/extra/config.go#L56-L58

**Comment by omniproc** [comment]
@enxebre the problem isn't that you cant refer to the generated name in k8s, the problem is that you can't tell CAPI what the generated name should be.

**Comment by enxebre** [comment]
>@enxebre the problem isn't that you cant refer to the generated name in k8s, the problem is that you can't tell CAPI what the generated name should be.

ok I see, can you elaborate on the need for that so we can consider solutions?

**Comment by omniproc** [comment]
- Enterprise compliance reasons. Most enterprises define a given hostname schema. This often isn't pure eye-candy but you'll often have business processes that rely on such internal definitions (if that's something you'd want or not is another discussion but it's a given reality in most big enterprises).
- Consistent re-deployments of cluster nodes. In case you have / want to redeploy a node you want the new node, that replaces the old node, to come up with the same IP and hostname the old node had.

**Comment by enxebre** [comment]
I think the uses cases described above are to make machines behave more like pets which does not align with the main machineSet/machineDeployment design and assumptions.

For such static use cases where you need fixed names and more control you could create single Machines resources with well known names and no upper level owner controller. Would this satisfy the needs? Furthermore, nothing would preclude you from developing your own ad-hoc controller that would enforce static machines.

Because of the above I question we should support this in the existing scalable resources. Happy to hear other thoughts.

**Comment by omniproc** [comment]
Can you point me to any documentation explaining how to implement such an ad-hoc controller? 

I agree that it somewhat goes the pets way but keep the re-deploy case in mind which *is* a cattle approach. Given a cluster breaks for some reasonI want to redeploy it and once it's ready have it the same way the old cluster way. From the k8s perspective no assumptions are made regarding any *name* of a resource at all. So the re-deployed cluster *is* the same on that layer. 
The special case that ClusterAPI faces from my point of view is that it interacts with the infrastructure of the providers. And that infrastructure often *does* make assumptions about the names of things and in special about hostnames.
So in a perfect k8s world I'd agree. But in the infrastructure stack below reality is often different. Currently providers can't control the hostname since it's generated by CAPI as far as I understand.

If you say it would be possible implementing ad-hoc controllers then that could be a method a provider that does wish to control the hostname could take. But from comments in different issues in CAPV I had the assumption that currently it's not possible at all.

**Comment by enxebre** [comment]
>Currently providers can't control the hostname since it's generated by CAPI as far as I understand.

To make sure my feedback is useful for you and that we are on the same page: the issue you have is by using scalable resources i.e MachineSet/MachineDeployment which generate the Machine names dynamically.

Now, nothing would prevent you from creating a single Machine CR with the name of your choice which it'll be set as the hostname e.g in vSphere as pointed in https://github.com/kubernetes-sigs/cluster-api/issues/5562#issuecomment-963225733. So that would support your use case, correct?

**Comment by omniproc** [comment]
@enxebre I wasn't aware creating a Machine directly is possible with CAPV so I didn't know that's an option. If it's really that easy to directly access the Machine ressource shim provided by CAPV, which should be VSphereMachine, then that probably would do the trick for my use case.

Still I think there's more to it. If you look through the issues you'll notice ppl. asking for a feature to control the hostname in nearly every provider repo and in the CAPI repo as well multiple times. Do you think the point I made in my last comment is invalid? Do you mind elaborating why you think so?

**Comment by enxebre** [comment]
Hey @omniproc 

>I agree that it somewhat goes the pets way but keep the re-deploy case in mind which is a cattle approach. Given a cluster breaks for some reasonI want to redeploy it and once it's ready have it the same way the old cluster was.

If you restore from a backup all names will be honoured and so they will honour hostname as well. Correct?

>The special case that ClusterAPI faces from my point of view is that it interacts with the infrastructure of the providers. And that infrastructure often does make assumptions about the names of things and in special about hostnames.
So in a perfect k8s world I'd agree. But in the infrastructure stack below reality is often different. Currently providers can't control the hostname since it's generated by CAPI as far as I understand.

I think scalable resources are designed to treat machines are "cattle" and this is a fair assumption for majority of use cases. If you need a "pet" you have the choice of creating a single Machine CR .

>If you say it would be possible implementing ad-hoc controllers then that could be a method a provider that does wish to control the hostname could take. But from comments in different issues in CAPV I had the assumption that currently it's not possible at all.

What I meant is now you have created a single Machine CR to satisfy your use case, nothing would prevent you from writing your upper level controller to manage that machine/machines ala stateful set or enforcing whatever behaviour you need.

>Still I think there's more to it. If you look through the issues you'll notice ppl. asking for a feature to control the hostname in nearly every provider repo and in the CAPI repo as well multiple times. Do you think the point I made in my last comment is invalid? Do you mind elaborating why you think so?

I think if I'm not mistaken your use case falls under a pet use case for a Machine and is supported as stated in https://github.com/kubernetes-sigs/cluster-api/issues/5562#issuecomment-967340506 and as elaborated in this comment above. If you still disagree and you think there's enough justification as to include hostnames in the scalable resources or you have any other approach in mind maybe a good way to get it going is to get all those issues you mention together and start with a design proposal https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#proposal-process-caep. My feeling with current feedback/context is that this can be approached as elaborated above.

**Comment by omniproc** [comment]
> 
> If you restore from a backup all names will be honoured and so they will honour hostname as well. Correct?
> 

Well the hole point of using CAPI is to have  cattle / reproducable / re-deployable infra-stack, isn't it? So if you argue "use backup" I'd argue we already had that before CAPI. Maybe it's just me but all this discussion is about which attributes can/should change between redeployments and which can't / shouldn't. I see use-cases were you want to keep the hostname and I don't think "restore from backup" is a valid solution altought _of course_ it _would_ work. But then again: with that approach we could dump CAPI all together and just restore K8s clusters from backup if we need a redeployment (I'm aware there are other benefits of using CAPI, I'm just exaggerate to clearify my point). 


> I think scalable resources are designed to treat machines are "cattle" and this is a fair assumption for majority of use cases. If you need a "pet" you have the choice of creating a single Machine CR .

So you say wanting to be able to have predictable hostnames always means you have "pets"? If so then why does CAPI support the concept of anything static? Like static IPs? Static DNS servers? Static image version numbers?
The definition of cattle and pet is not as clear as you make it  sound and I still think a method to have static hostnames for cluster nodes is a valid use-case and doesn't necessarily break the cattle approach if done right.


> What I meant is now you have created a single Machine CR to satisfy your use case, nothing would prevent you from writing your upper level controller to manage that machine/machines ala stateful set or enforcing whatever behaviour you need.

As I said I'll trest that and most likely it would be a workaround I can go on with for now. But tbh you could always say "do your own fork" or "write your own controller" or "write a bash script and script your ressources as you need". This discussion is about whether or not this feature is important enough to a sufficently enough set of CAPI users to integrate it in CAPI itself.

>If you still disagree and you think there's enough justification as to include hostnames in the scalable resources or you have any other approach in mind maybe a good way to get it going is to get all those issues you mention together and start with a design proposal https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#proposal-process-caep. My feeling with current feedback/context is that this can be approached as elaborated above.

I never wrote a proposal for k8s/CAPI but certainly, if required I could do this but I'd need quite some time until I had the chance to go through the required Go sources and honestly, by then I could implement it myself and present a PR.
So I opend this issue to see if I'm the only one asking for this or if I'm missing something that's already available because writing a design proposal or even PR that then just get's refused because nobody is interested isn't something I'm looking forward to.
If your opinion on this is final and other people see it your way, then I guess we can close this and just say CAPI will never support this feature. I'm not sure if you have a "won't fix" tag but with that decission at least it would be a clear statement for the provider writers as well, who could then consider not using the CAPI name generation at all. Because honestly for now it's not very clear why this was never considered as a feature - see my comment on why I don't think static hostnames necessarily mean pet-approach above.

**Comment by enxebre** [comment]
hey @omniproc I didn't meant restore from a backup as a solution to the problem, I mistakenly understood that's what you were doing in the  context of your re-deploying scenario :)

Sure, I'm just trying to gather as much feedback as possible to understand the problems and challenges being faced in this scenario to figure and discuss the best angle to approach them and to weight the level of support CAPI should provide.
I wouldn't be in favour of limiting scalable resources ability to scale based on a pool of hostnames as suggested in the desc but let's wait to hear from others, as they might have thoughts in a different direction than mine.

Another space where this might be relevant to discuss is the effort to decouple machine and kube bootstrapping https://github.com/kubernetes-sigs/cluster-api/issues/5294

Another space to gather feedback and interest would be to bring it up in the regular community call and may be add it as a roadmap candidate https://github.com/kubernetes-sigs/cluster-api/discussions/5556.

**Comment by omniproc** [comment]
> hey @omniproc I didn't meant restore from a backup as a solution to the problem, I mistakenly understood that's what you were doing in the context of your re-deploying scenario :)

I see. No, I'm not doing stuff like *that* :-)

> Another space where this might be relevant to discuss is the effort to decouple machine and kube bootstrapping #5294

I'm definitly in favour of this since I believe many issues are related to bootstrapping and unnecessarily coupled with kubeadm which currently seems to be 'abused' as tool to exec shell commands for pretty much everything.
If it would be more loosely coupled, possibly with a way to extend and even override what happens during bootstrap that would be awesome. A more direct access to cloud-init or ignition would be awesome and potentially make it possible to deal with a huge amount of use cases without having do directly support them in CAPI. The CAPI name generator could simply be replaced by a JINJA filter, for example, and used in the default cloud-init script that ships with the provider a user choose. If you don't want that, replace it with whatever cloud-init you want and use the JINJA filters that ship with CAPI out of the box or build your own.

**Comment by macaptain** [comment]
The discussion above was interesting to me, especially the suggestion of creating Machine CRs instead of a MachineDeployment and managing the Machines manually. (tagging @enxebre since your suggestions above are very helpful.)

A use case to illustrate the problem: 

I have external network infrastructure which cares about the IP addresses of worker nodes in my Kubernetes cluster. I'm running MetalLB, and for BGP reasons, when the backend set of IP addresses for the load balancer changes (i.e. the IP addresses of my worker nodes), routers need reconfiguring with the new IP addresses of the BGP neighbors. 

When I do a RollingUpdate of my MachineDeployment (say, to install a new Kubernetes version), the Machines in the new MachineSet have different IP addresses, and so MetalLB BGP breaks until the router is reconfigured.

However, if I could choose the names of my Machines, it would be possible in my environment to map the hostnames back to the IP addresses they had previously via IPAM/cloud-init/dhclient/provider specific implementations allocating IP addresses, etc. and maintain the backend set of IP addresses throughout a RollingUpdate. Otherwise, since there's no 'memory' in a RollingUpdate, there's no way for me to recover the IP addresses used for the nodes in the cluster in the new MachineSet.

> I think the uses cases described above are to make machines behave more like pets which does not align with the main machineSet/machineDeployment design and assumptions.

Yes, agreed. What I imagine is more of a 'MachineStatefulSet' than a 'MachineDeployment'. Just as a MachineDeployment is analogous to a Deployment in Kubernetes, where the Machines/Pods get random names, a 'MachineStatefulSet' would behave more like a Kubernetes StatefulSet, where pod names and the update procedure are deterministic.

The obvious Kubernetes-way solution is an operator which dynamically keeps the router configuration up to date, but here we hit the enterprise problem where as a Kubernetes administrator, I am not necessarily going to have credentials to manage production network infrastructure. Ordinarily, as a Kubernetes administrator, I have the ability to configure hostnames and IP addresses for my nodes, but CAPI doesn't support this.

The pool of Machine names idea in the issue description would work, but I agree it doesn't feel quite right to limit scalable resources like that. I'd be open to any other suggestions on how to manage this from CAPI.

**Comment by omniproc** [comment]
> The pool of Machine names idea in the issue description would work, but I agree it doesn't feel quite right to limit scalable resources like that. I'd be open to any other suggestions on how to manage this from CAPI.

In most cases you'll have some counter so the 'pool' could be a template rather then a list of static hostnames, thus "infinite" pool of hostnames that's still compliant with whatever you need.

**Comment by enxebre** [comment]
>When I do a RollingUpdate of my MachineDeployment (say, to install a new Kubernetes version), the Machines in the new MachineSet have different IP addresses, and so MetalLB BGP breaks until the router is reconfigured.

Hey @macaptain please have a look at https://github.com/kubernetes-sigs/cluster-api/pull/6000 where you might want to share some tangential thoughts

>Yes, agreed. What I imagine is more of a 'MachineStatefulSet' than a 'MachineDeployment'. Just as a MachineDeployment is analogous to a Deployment in Kubernetes, where the Machines/Pods get random names, a 'MachineStatefulSet' would behave more like a Kubernetes StatefulSet, where pod names and the update procedure are deterministic.

See also https://kubernetes.slack.com/archives/C8TSNPY4T/p1643735192772679
