### ISSUE TITLE
Docker less CAPD 😜 

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5836]
**User Story**

As a developer, I would like to have a docker less dev env for CAPI
As a maintainer, I would like to run E2E tests without being required to use docker

**Detailed Description**

This is a follow-up of 1. Docker license model changes and 2. Kubernetes removing docker shim from kubelet

Using docker both locally and in CI is getting "complex", so we should start considering options to get our test framework and CAPD, to work without docker.

The problem has two dimensions:
1. local dev env on macOS or windows, where there are a few alternatives to docker, with podman probably being the one causing less friction to the users
2. local dev env or CI machines on linux, where we can directly interact with containerd

Solving this issue requires:
- doing some research
- propose a solution for 1 and 2 (or 2 solutions if required) and get community consensus
- implement the corresponding changes in https://github.com/kubernetes-sigs/cluster-api/tree/main/test/infrastructure/container, which is the CRI abstraction recently introduced by @stmcginnis (thanks!)
 
**Anything else you would like to add:**

There is an existing [issue for podman support](https://github.com/kubernetes-sigs/cluster-api/issues/5146) with some interesting comments about using `podman service` as a transparent replacement to docker daemon

Possible alternatives to be investigated are using containerd client or CRI libraries

Last bu not least, we should also consider that kind and tilt are integral part of our dev env, and this checking how those communities are dealing with the change of the Docker licence model could be interesting

/kind feature

**Comment by fabriziopandini** [comment]
Also https://github.com/kubernetes-sigs/cluster-api/issues/5634 can be related

/milestone Next
/area testing
/area provider/docker

**Comment by adisky** [comment]
would like to explore on making CAPD work with CRI (containerd) with the little knowledge i have on CRI/containerd And also use this as an opportunity to learn about cluster API, essentially i can focus on

> 2. local dev env or CI machines on linux, where we can directly interact with containerd

**Comment by sbueringer** [comment]
It would be great if we can keep using the same underlying "container provider" for the dev env, local test execution and in CI/Prow.

I think otherwise we will run into problems if there are too much differences between those environments.

(I'm not sure if the issue already states that it should also be possible to run the new thing in CI/Prow)

**Comment by dims** [comment]
/assign @adisky 

:)

**Comment by anusha94** [comment]
@adisky would you like to pair on this? I'd like to learn more about CRI / containerd with the little knowledge I have of CAPI :)

**Comment by adisky** [comment]
@anusha94 yup Anusha, lets do some pairing :)

**Comment by fabriziopandini** [comment]
FYI https://github.com/kubernetes-sigs/cluster-api/issues/5146#issuecomment-992595937

**Comment by jorgemoralespou** [comment]
@fabriziopandini This issue seems more targeting CAPD as a testing tool than as a Provider. I would have expected to see something like this in the description:

- As a user, I would like to leverage my local container runtime as infrastructure provider so that I can use the same CAPI semantics to provision clusters locally.

On [ClusterAPI README.md](https://github.com/kubernetes-sigs/cluster-api) one can read:

> Cluster API is a Kubernetes sub-project focused on providing declarative APIs and tooling to simplify provisioning, upgrading, and operating multiple Kubernetes clusters.

Which this means is that it's not impossing any limitation on infrastructure providers, so why not have local desktops/laptops and their container runtimes (or hypervisor layers) be this infrastructure provider? In that regard, I would love to see CAPD be a real infrastructure provider rather than just a means to test CAPI itself.

**Comment by fabriziopandini** [comment]
@jorgemoralespou this issue is about how to interact with a CRI without the docker daemon/CLI, so the idea of CAPD is not in discussion but is just adapting to the changed context.

WRT to I would love to see CAPD be a real infrastructure provider rather than just a means to test CAPI itself, this goes behind the scope of this issue and if you are interested in this topic I suggest you open a separated issue where you can add more details about the GAP between current CAPD implementation which are relevant for you and your expectations.

**Comment by sbueringer** [comment]
@Namanl2001 just fyi, you can self-assign if you want to (it's just that others can't)

**Comment by fabriziopandini** [comment]
/close
we are not making progress and it seems there isn't strong demand for this.

**Comment by Namanl2001** [comment]
I attempted to implement Dockerless CAPD with Containerd. However, I have hit a few roadblocks and thought of putting them here for anyone interested in taking this up in the future. 

Since containerd is available as a daemon for Linux and Windows, which can manage the complete container lifecycle of its host system, in CAPD, I implemented all the [runtime interface](https://github.com/Namanl2001/cluster-api/blob/main/test/infrastructure/container/interface.go#L31-L42) methods for containerd, taking help from the [crictl](https://github.com/containerd/containerd/blob/main/docs/cri/crictl.md) and [nerdctl](https://github.com/containerd/nerdctl) codebase; However, native containerd support on mac OS is WIP ([tracking issue](https://github.com/containerd/containerd/issues/1881)), but as a workaround mac users can use [Lima](https://github.com/lima-vm/lima) + [nerdctl](https://github.com/containerd/nerdctl)

To test each function, I created a containerd container using nerdctl/crictl and called the implemented functions individually to check their respective outputs. Eg: after calling the [DeleteContainer](https://github.com/Namanl2001/cluster-api/blob/dockerless-capd/test/infrastructure/container/containerd.go#L426) function, the specific container was deleted. All other functions are also giving the expected outputs.

Design Doc: https://docs.google.com/document/d/1-Y5KF8pLlxEYuxhXRg5DkYk3YbCT_b6dBA2G23mO8Fo/edit?usp=sharing 

Proposed code changes: https://github.com/Namanl2001/cluster-api/tree/dockerless-capd

To integrate the dockerless-capd with the existing cluster-api code, I [invoked](https://github.com/kubernetes-sigs/cluster-api/compare/main...Namanl2001:cluster-api:dockerless-capd#diff-c4604297ff388834dc8c6de30c847f50548cd6dd4b2f546c433b234a27ad4631L182-R182) containerdClient instead of dockerClient. And on manually running & testing dockerless-capd with the above changes, following the instructions [given here](https://cluster-api.sigs.k8s.io/developer/guide.html#option-2-the-old-fashioned-way), it runs successfully. However, to make it possible, we had to mount the containerd socket in the [deployment files](https://github.com/Namanl2001/cluster-api/blob/e0fdec5360d011a29d801e61fc030c0501421d78/config/default/manager_image_patch.yaml#L12-L18)

```cmd
lnaman@instance:~/cluster-api$ kubectl get po -n capd-system
NAME                                       READY   STATUS    RESTARTS   AGE
capd-controller-manager-557b4c9bbb-78zmp   1/1     Running   0          9s
lnaman@instance:~/cluster-api$ kubectl get po -n capd-system
NAME                                       READY   STATUS    RESTARTS   AGE
capd-controller-manager-557b4c9bbb-78zmp   1/1     Running   0          17s
```

But while running the present e2e tests with `make test-e2e` command, machines are not getting provisioned as expected, and we’re facing problems debugging the failure.
<details close>
<summary>expand to see the error logs</summary>

```error
Will run 21 of 21 specs

STEP: Initializing a runtime.Scheme with all the GVK relevant for this test
STEP: Loading the e2e test configuration from "/home/lnaman/cluster-api/test/e2e/config/docker.yaml"
STEP: Creating a clusterctl local repository into "/home/lnaman/cluster-api/_artifacts"
STEP: Reading the ClusterResourceSet manifest ./data/cni/kindnet/kindnet.yaml
STEP: Setting up the bootstrap cluster
STEP: Creating the bootstrap cluster
INFO: Creating a kind cluster with name "test-6ba6po"
Creating cluster "test-6ba6po" ...
 • Ensuring node image (kindest/node:v1.23.4) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.23.4) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
INFO: The kubeconfig file for the kind cluster is /tmp/e2e-kind207258860
INFO: Loading image: "gcr.io/k8s-staging-cluster-api/cluster-api-controller-amd64:dev"
INFO: Loading image: "gcr.io/k8s-staging-cluster-api/kubeadm-bootstrap-controller-amd64:dev"
INFO: Loading image: "gcr.io/k8s-staging-cluster-api/kubeadm-control-plane-controller-amd64:dev"
INFO: Loading image: "gcr.io/k8s-staging-cluster-api/capd-manager-amd64:dev"
INFO: Loading image: "quay.io/jetstack/cert-manager-cainjector:v1.5.3"
INFO: Loading image: "quay.io/jetstack/cert-manager-webhook:v1.5.3"
INFO: Loading image: "quay.io/jetstack/cert-manager-controller:v1.5.3"
STEP: Initializing the bootstrap cluster
INFO: clusterctl init --core cluster-api --bootstrap kubeadm --control-plane kubeadm --infrastructure docker
INFO: Waiting for provider controllers to be running
STEP: Waiting for deployment capd-system/capd-controller-manager to be available
INFO: Creating log watcher for controller capd-system/capd-controller-manager, pod capd-controller-manager-7bf64c7595-kjc9j, container manager
STEP: Waiting for deployment capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-controller-manager to be available
INFO: Creating log watcher for controller capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-controller-manager, pod capi-kubeadm-bootstrap-controller-manager-7f6d6b679d-jxjhz, container manager
STEP: Waiting for deployment capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager to be available
INFO: Creating log watcher for controller capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager, pod capi-kubeadm-control-plane-controller-manager-7b5b9c65f4-xpxq4, container manager
STEP: Waiting for deployment capi-system/capi-controller-manager to be available
INFO: Creating log watcher for controller capi-system/capi-controller-manager, pod capi-controller-manager-75f65654b4-tddv7, container manager
When testing node drain timeout
  A node should be forcefully removed if it cannot be drained in time
  /home/lnaman/cluster-api/test/e2e/node_drain_timeout.go:82
STEP: Creating a namespace for hosting the "node-drain" test spec
INFO: Creating namespace node-drain-022vkp
INFO: Creating event watcher for namespace "node-drain-022vkp"
STEP: Creating a workload cluster
INFO: Creating the workload cluster with name "node-drain-55yw54" using the "node-drain" template (Kubernetes v1.23.4, 3 control-plane machines, 1 worker machines)
INFO: Getting the cluster template yaml
INFO: clusterctl config cluster node-drain-55yw54 --infrastructure (default) --kubernetes-version v1.23.4 --control-plane-machine-count 3 --worker-machine-count 1 --flavor node-drain
INFO: Applying the cluster template yaml to the cluster
configmap/cni-node-drain-55yw54-crs-0 created
clusterresourceset.addons.cluster.x-k8s.io/node-drain-55yw54-crs-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/node-drain-55yw54-md-0 created
cluster.cluster.x-k8s.io/node-drain-55yw54 created
machinedeployment.cluster.x-k8s.io/node-drain-55yw54-md-0 created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/node-drain-55yw54-control-plane created
dockercluster.infrastructure.cluster.x-k8s.io/node-drain-55yw54 created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/node-drain-55yw54-control-plane created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/node-drain-55yw54-md-0 created

INFO: Waiting for the cluster infrastructure to be provisioned
STEP: Waiting for cluster to enter the provisioned phase

• Failure [304.693 seconds]
When testing node drain timeout
/home/lnaman/cluster-api/test/e2e/node_drain_timeout_test.go:26
  A node should be forcefully removed if it cannot be drained in time [It]
  /home/lnaman/cluster-api/test/e2e/node_drain_timeout.go:82

  Timed out after 300.001s.
  Expected
      <string>: Provisioning
  to equal
      <string>: Provisioned

  /home/lnaman/cluster-api/test/framework/cluster_helpers.go:134

  Full Stack Trace
  sigs.k8s.io/cluster-api/test/framework.WaitForClusterToProvision({0x3932f38?, 0xc00012a5c0}, {{0x7f23182786b8?, 0xc0004ecc40?}, 0xc00052bdc0?}, {0xc000f4b8c0, 0x2, 0x2})
        /home/lnaman/cluster-api/test/framework/cluster_helpers.go:134 +0x19c
  sigs.k8s.io/cluster-api/test/framework.DiscoveryAndWaitForCluster({0x3932f38?, 0xc00012a5c0}, {{0x7f23182786b8, 0xc0004ecc40}, {0xc0005646c0, 0x11}, {0xc000564720, 0x11}}, {0xc000f4b8c0, 0x2, ...})
        /home/lnaman/cluster-api/test/framework/cluster_helpers.go:192 +0x3a6
  sigs.k8s.io/cluster-api/test/framework/clusterctl.ApplyClusterTemplateAndWait({_, _}, {{0x3940f40, 0xc0021e4400}, {{0xc0007de780, 0x36}, {0xc000954ad9, 0x45}, {0xc000954b1f, 0x16}, ...}, ...}, ...)
        /home/lnaman/cluster-api/test/framework/clusterctl/clusterctl_helpers.go:276 +0x8b3
  sigs.k8s.io/cluster-api/test/e2e.NodeDrainTimeoutSpec.func2()
```
</details>

We suspected the problem with the machine not getting provisioned is related to mounting of the containerd socket, to debug this we tried mounting the socketPath via [YAML deployment files](https://github.com/Namanl2001/cluster-api/blob/e0fdec5360d011a29d801e61fc030c0501421d78/config/default/manager_image_patch.yaml), alternatively we also configured containerd’s socketPath in place of [docker’s](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/bootstrap/kind_provider.go#L181-L182) for allowing the containerd provider to access containerd on the host, but got the same error.  We also got the same error with tilt.

> What’s the need to mount the containerd socket?
Kind starts containerd in its node for the kubelet to connect to. So normally we have a docker container for the node which runs kubelet and containerd. The config now did overwrite the containerd socket inside the node and the kubelet in the docker container does now talk to the hosts containerd process instead.
