### ISSUE TITLE
`clusterctl generate` creates a duplicate deployment

### ISSUE THREAD

**Issue by frezbo** [kubernetes-sigs/cluster-api#5851]
**What steps did you take and what happened:**

```bash
❯ clusterctl generate provider --infrastructure aws:v0.5.0 | yq eval 'select(.kind == "Deployment").metadata.name' -
capa-controller-manager
---
capa-controller-manager
```

```bash
❯ clusterctl generate provider --control-plane talos:v0.2.0  | yq eval-all 'select(.kind == "Deployment").metadata.name' -
cacppt-controller-manager
---
cacppt-controller-manager
```

**What did you expect to happen:**

```bash
❯ clusterctl generate provider --control-plane talos:v0.2.0  | yq eval-all 'select(.kind == "Deployment").metadata.name' -
cacppt-controller-manager
```

**Anything else you would like to add:**

```bash
❯ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.2", GitCommit:"89db44e9a462028267ed49295359fe9db2a6a10a", GitTreeState:"clean", BuildDate:"2021-12-06T17:52:47Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by stmcginnis** [comment]
Hi @frezbo, can you add some description to the issue of what the problem encountered is? With the example output you added, it's not very clear what the issue is.

**Comment by fabriziopandini** [comment]
@ykakarap PTAL
Not sure this is an actual issue or it depends by the provider yamls, but worth to investigate

**Comment by ykakarap** [comment]
@frezbo  From a quick glance, it looks like this could be a result of using the newest version of clusterctl (`v1.2.0`) with old version of CAPA. CAPA v0.5.0 is a `v1alpha3` release that should be used with `v.0.3.x` binaries of clusterctl. 

The output of `./clusterctl-1.0.2 generate provider --infrastructure aws:v1.2.0` seems to be correct, with only one Deployment.

(I suspect the 2 deployments could be because the v1alpha3 version of providers use to have 2 deployments - one for the manager and the other for the webhooks. This combined with a v1beta1  version of clusterctl might be acting weird.)

I will take a closer look to see what the expected behavior should be when using new version of clusterctl will old versions of providers.

**Comment by ykakarap** [comment]
After analyzing further:
The output for the cases used in the issue description is supposed to have two deployments. The versions used are v1alpha3 versions and as mentioned previously these versions came with 2 deployments. One for the manager and one for the webhook. Example ref: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v0.5.0/infrastructure-components.yaml

However the 2 deployments are deployed in the two different namespaces. For AWS, lets say, the namespaces will be `capa-system` and `capi-webhook-system`. The new `clusterctl generate provider` however performs a `fixTargetNamespace` on all objects.
(This was not a problem with cluserctl v0.3.x because we used to fixTargetNamespace only on a subset of the component objects and the webhook deployments were not in that set.)



@fabriziopandini do we really want to support using the new `clusterctl generate provider` on provider versions that are incompatible with the clusterctl version?
I would personally vote for not supporting this command on incompatible providers versions and return an error early if we are working with an incompatible version of the provider.

**Comment by frezbo** [comment]
@ykakarap thanks for explaining the issue in detail :+1: :muscle: . I'm going to close this, doesn't make sense to support this use case for clusterctl with older versions. Probably returning an error like  `init` when using a `v1alpha*` version should be sufficient.

**Comment by ykakarap** [comment]
>>I would personally vote for not supporting this command on incompatible providers versions and return an error early if we are working with an incompatible version of the provider.

>That could be a nice improvement

Opened https://github.com/kubernetes-sigs/cluster-api/issues/5864 to follow on up.
