### ISSUE TITLE
Cloud Provider implementation for AWS

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#59]
_From @rsdcastro on January 29, 2018 23:8_

_Copied from original issue: kubernetes/kube-deploy#541_

**Comment by dragan** [comment]
Has anybody volunteered for this? I meant to attend the SIG meeting today and introduce myself, however prior engagements kept me away. I'd like to volunteer. I'm also happy to work with anybody else to implement an AWS actuator.

In the past I've used Terraform to launch an HA Kubernetes cluster and have been running kubernetes in a production environment since 1.0.0. I'm ready to align to a single API to provision clusters and I'm in love with this initiative. Therefore, I do have a few questions about technology choices and how the freedom could be allowed through the API:

1. Has there been any discussions on allowing freedom in technology choices? For instance, using [CoreOS Container Linux](https://coreos.com/os/docs/latest/) instead of say Ubuntu?
2. With that freedom, the userdata script will change, are there extension points in regards to allowing different meta config templates? Sorry for any misconceptions with the vernacular, I quickly looked over the codebase and I'm still educating myself.

Thanks!

**Comment by rsdcastro** [comment]
Hi Dale - we had a couple of people starting some work on the AWS provider implementation before but those didn't get sent out as PR (and it's been a while now). So please feel free to pick this up - and thank you for doing it! 

On your questions. Yes, what each platform provider supports is totally independent from each other. Our goal is that much of the code to support a particular OS can be reused, but we're not at that stage yet. I'd recommend you follow some of the configuration design implemented by @kcoronado for more configurable OS/start up scripts. https://github.com/kubernetes/kube-deploy/pull/664

If you have any questions, please reply here or on Slack. Katie should be able to help with specific questions on her work.
 
As you're not part of the K8s org, I'll assign it to myself so we know that this is being worked on.

cc @dragan
/assign @rsdcastro

**Comment by dragan** [comment]
Hi Rodrigo! No problem, I'm happy to help!

Thanks for the information and I'll take a look @kcoronado PR. I'm starting on this now! As soon as I have something working, I'll submit a PR to start the feedback process.

/cc @rsdcastro

**Comment by enxebre** [comment]
bare bones implementation repo has been proposed by @detiber here https://github.com/kubernetes-sigs/cluster-api/issues/425 We'll next share a starting design doc so we have a common place to collaborate and discuss implementation details cc @csrwng

**Comment by roberthbailey** [comment]
Now that https://github.com/kubernetes-sigs/cluster-api-provider-aws exists I think this issue should be closed and as @enxebre suggested implementation discussions for an aws provider should happen in the new repo.
