### ISSUE TITLE
Test_objectMover is flaky

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5938]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

The Test_objectMover is failing from time to time with the following error
```yaml
    mover_test.go:724: 
        Expected
            <time.Time>: 2022-01-10T22:00:03.398330287Z
        to be <
            <time.Time>: 2022-01-10T22:00:03.398330287Z
    --- FAIL: Test_objectMover_backupTargetObject/Cluster (0.03s)
```

Recent run:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1480660217195663360

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
fyi @killianmuldoon

**Comment by killianmuldoon** [comment]
It seems that when this happens it's impacting two test cases so there must be some subtle file system issue that's causing this and we're not catching the error somehow.

 I'm investigating this, but it's not going to be easily reproducible.

**Comment by Jont828** [comment]
As @killianmuldoon and I discussed on Slack, I am able to repro this locally by running `make test` using Go 1.17.6 on Arch Linux in WSL with kernel ` 5.10.16.3-microsoft-standard-WSL2`. I think it's most likely an issue with virtual filesystem, @sbueringer also mentioned that it's possible that the file is written but the timestamp didn't change, or the file isn't written because the contents didn't change.

**Comment by sbueringer** [comment]
Let's see if that was enough to fix it :)
