### ISSUE TITLE
CAPD: Inconsistent Load Balancer Behaviour on Mgmt Cluster deletion and recreation

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#5975]
When the management cluster with the Docker Infrastructure provider is deleted the containers backing it up the DockerMachines are not deleted. This can cause a number of problems on a user machine as a number of containers not seen by Cluster API continue to run.

Step by step:
1. Create a management cluster and create a workload cluster using docker infrastructure. (**cluster apply 1**) 
1. Delete the management cluster but don't delete the workload cluster.
1. Create a new management cluster and create the same workload cluster again. (**cluster apply 2**) 
1. Run `docker ps`

Docker will show that all of the containers from **cluster apply 1** are still there along with similar containers created in **cluster apply 2**

This issue surfaced as a certificate error in the CAPI logs with the form:
`controller/kubeadmcontrolplane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/my-cluster\": Get \"https://172.18.0.4:6443/api?timeout=10s\": x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")" "cluster"="my-cluster" "name"="controlplane" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" 
`
This issue was directly caused by the Load Balancer created by CAPD using all of the existing Control Plane docker containers as backers for the Control Plane. Only one of the existing containers was actually part of this Kubernetes cluster so the control plane machine created in **cluster apply 1** did not have a valid certificate.

/kind bug

**Comment by sbueringer** [comment]
I think it's expected behavior that CAPD doesn't do anything in step2, as for CAPD the Cluster resources are all still there and it only gets a terminate signal (at best).

I think the problem is in step 3 where we:
* are creating new machines (instead of using the existing ones)
* are re-using the original lb container
* are adding old and new machines to the lb configuration of the lb container 

I think we should aim to clearly have one of the following behaviors in step 3:
1. CAPD adopts the existing cluster (including machines)
2. CAPD creates a new cluster including machines which is entirely separated from the old cluster

Currently, we have a mixture of both as:
* the lb-container is re-used
* all other containers are recreated
* the lb-configuration includes old and new control plane machines

I think it would make sense to investigate how CAPD currently works, before deciding how/if we can improve on the current situation.

**Comment by fabriziopandini** [comment]
TBH I don't think there is something we should fix until we define a shared set or rules/a sort of contract that all the providers should comply with in order to deal with existing infrastructure. In other words, IMO re-starting a cluster without properly cleaning up the previous incarnation of the same cluster is not a supported use case in CAPD (and most probably in other containers as well).

WRT to the current behavior being inconsistent I get the point, but AFAIK all the providers rely on a mix of naming conventions and labeling, so in that sense, CAPD is not an exception.

**Comment by fabriziopandini** [comment]
/close
We can eventually re-open in case we identify some actionable item
