### ISSUE TITLE
KCP InfrastructureMachineTemplate not deleted after Cluster deletion if infrastructure never becomes ready

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#6006]
**What steps did you take and what happened:**

1- Create a Cluster where infrastructure never becomes ready (e.g., AWS does not have enough resources)
2- Delete the Cluster and `InfrastructureMachineTemplate` referenced by KCP never gets deleted.

KCP does not set owner reference to its `InfrastructureMachineTemplate` until infrastructure becomes ready and if the `Cluster` is deleted, `InfrastructureMachineTemplate` is not cleaned up due to the missing owner reference.

This issue is not happening with `MachineDeployments` because the owner reference is set at the reconcile.

**What did you expect to happen:**

**Anything else you would like to add:**
Owner reference of `InfrastructureMachineTemplate` needs to be set before this point: https://github.com/kubernetes-sigs/cluster-api/blob/5d5dc7a1d50842577b32fbc41bcedc48925f125c/controlplane/kubeadm/internal/controllers/controller.go#L153

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by ykakarap** [comment]
@sedefsavas I tried to reproduce the issue and here are my findings.

In a case where the InfrastructureCluster never becomes ready and one tries to delete the cluster the delete operation is stuck and the Cluster, KCP and InfraMachineTemplate used by KCP are never deleted. This is because the KCP reconciler returns early before reaching the `reconcileDelete` block. 

However, I think the case you explained in the issue might have happened under the following circumstances:
* Create a Cluster in which the Infrastructure is never ready
* A delete is issued to the cluster object
* While the delete operation is stuck and does not proceed any further the infrastructure might have become ready
* Now, the KCP reconciler directly goes into `reconcileDelete` without ever going into `reconcile`.
* This will delete the other objects and orphan the InfrastructureMachineTemplate

Can you confirm is this is the behavior you observed as well?

In any case, I think it makes sense to move the Infrastructure Ready check after the owner references are set. This should help in solving both the problems mentioned above.

https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/controllers/controller.go#L253-L256 <- Move infrastructure ready check after this section.

**Comment by ykakarap** [comment]
Update: The scenario mentioned in the issue is more generally possible and doesn't need the circumstances mentioned in https://github.com/kubernetes-sigs/cluster-api/issues/6006#issuecomment-1031421920 to happen. 
The cluster deletion gets blocked in case of CAPD clusters because of the following:
* DockerMachines are not deleted because the reconciler returns early if `cluster.status.infrastructureReady` is false.
* Cluster reconciler wait eternally for the MachineDeployment using these DockerMachines to get deleted.
* Never issues a delete on KCP 
* The entire delete operation is then hung in this state.

However, the problem mentioned in the issue still persists even when CAPD is not used. MachineTemplates are orphaned if the cluster is deleted before the infrastructure is ready. 

The linked PR addresses for the cases. #6183

**Comment by sbueringer** [comment]
@sedefsavas fix has been merged on main. thx @ykakarap 

Should this fix be cherry-picked to v1.1?

(cc @fabriziopandini )
