### ISSUE TITLE
🐛  clusterctl init fails with 'failed to get cert-manager object'

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#6051]
clusterctl init is failing with an error 'failed to get cert-manager object'. This is due to cert-manager [changing its repo location](https://github.com/cert-manager/cert-manager/issues/3451) (from github.com/jetstack to github.com/cert-manager). 

The solution for this issue is to add the new URL to the clusterctl config file, [as described here](https://cluster-api.sigs.k8s.io/clusterctl/configuration.html#cert-manager-configuration), adding:
```yaml
cert-manager:
  url: "https://github.com/cert-manager/cert-manager/releases/latest/cert-manager.yaml"
```

Alternatively users can use the clusterctl overrides folder to install the cert-manager from a yaml [as described here](https://cluster-api.sigs.k8s.io/clusterctl/configuration.html#overrides-layer)

/kind bug

**Comment by fabriziopandini** [comment]
/milestone v1.2
This is due to the GitHub client, that uses owner and repository from the above URL but it doesn't detect the URL redirect.

Let's change the URL as a quick fix, but long term we should implement URL redirect check in clusterctl, eventually rewriting the owner/repository passed to the GitHub client.

**Comment by fabriziopandini** [comment]
(fix to be backported up to 0.4)

**Comment by killianmuldoon** [comment]
I'll open another issue around the github client once the fix is in.

**Comment by sbueringer** [comment]
Just fyi. The `DownloadRelesaeAsset` func of the GitHub client is actually following redirects. But I think the issue is that we are retrieving a release (including assets) from a release of a new location and then passing in the owner of the old location.

But the fix stays the same, we have to detect the change and pass the right owner/repository through.
