### ISSUE TITLE
Enable a richer set of go template functions for defining ClusterClass patches

### ISSUE THREAD

**Issue by vuil** [kubernetes-sigs/cluster-api#6091]
**User Story**

As an operator I would like to define patches for a ClusterClass more efficiently by leveraging additional go template functions. 

**Detailed Description**

While the [go template](http://golang.org/pkg/text/template/) language has already enabled a good amount of flexibility in how the ClusterClass json patches can be authored, it is still lacking some basic functionality that makes defining those patches inconvenient or at times impossible. Fortunately the set of template functions can be extended through integrating with a library like [Sprig](https://github.com/Masterminds/sprig)

Some situations we have found so far that could have benefitted from said integration are

1. splitting string with delimiter-separated values into array
2. base64 encoding a constructed string
There seems to be possibilities of using the Sprig's list manipulation functions to make array modifications easier to define in a patch as well.

but I am pretty certain there will be other real-world templating use cases that could leverage other template function offered by this library.

**Anything else you would like to add:**

Note: Sprig is also used by Helm to extend its templating capabilities.
https://repeatit.io/ is a useful resource to examine the effect of go template processing in the presence of Sprig (Sprig integration can be turned on or off)

/kind feature

**Comment by sbueringer** [comment]
/area topology

Thx for creating the issue, will take a closer look soon.

**Comment by vincepri** [comment]
/milestone v1.1

During the backlog grooming session on Feb 11th we discussed about adding support for these additional go template functions within ClusterClass and Managed Topologies within the v1.1(.2?) release to allow adopters to experiment with ClusterClass patching and other advanced use cases sooner rather than later, especially given that KubeCon is a few months away.

/assign @fabriziopandini 
/priority important-soon

**Comment by fabriziopandini** [comment]
@vuil @sbueringer I was taking a look at sprig, and I was considering including only the so-called `HermeticFunc` that is a subset of func with only repeatable functions. This will help us in preventing users to write templates triggering infinite reconciliation because they use things like Now or Rand.

The list of functions that are going to be dropped is defined at https://github.com/Masterminds/sprig/blob/e4c0945838d570720d876a6ad9b4568ed32317b4/functions.go#L67-L91

opinions?

**Comment by fabriziopandini** [comment]
@sbueringer also, I'm assuming that we want sprig support only for variables, not for enableIf (even if it is not a problem to add it for both). wdyt?

**Comment by vuil** [comment]
@fabriziopandini nice catch, I wasn't even aware the library has called out this class of functions. It makes totally sense to exclude those functions since no patch should be written expecting non-repeatable behavior anyway.

**Comment by vuil** [comment]
> I'm assuming that we want sprig support only for variables, not for `enableIf` (even if it is not a problem to add it for both). wdyt?

my 2c, so feel free to assess it along with any potential impact it may have:

tbh so far we have not encountered a scenario where we need sprig support for enableIf, but it wouldn't be too inconceivable that we may encounter some in the future. Basides, it would probably be less surprising to authors working with golang templates to have consistent behavior wherever they are used.

**Comment by tenczar** [comment]
I can imagine a scenario where `upper`/`lower` would be useful for evaluating string equality in enabledIf. The `semverCompare` function might also prove useful.

**Comment by sbueringer** [comment]
I agree, we have to exclude non-hermetic functions.

I think I would prefer having the same features in `enabledIf` and `valueFrom.template`. It's easier to implement and explain to users as we don't have to explain the difference.

Functions like semverCompare, upper/lower, trim should be useful for `enabledIf`.

**Comment by fabriziopandini** [comment]
Thanks all for the quick feedback, it seems there is consensus on the direction, I'll start working on PR
