### ISSUE TITLE
Topology controller keeps rolling out InfrastructureMachinteTemplates when ClusterClass is supplied with Array typed patches

### ISSUE THREAD

**Issue by weikaipan** [kubernetes-sigs/cluster-api#6113]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Created a `ClusterClass` with Array typed patches. (See attached) The `MachineDeployment` is defined with `replicas=1`
Apply a `Cluster` referencing the `ClusterClass` above and supply the values to the array variable.

The values from variables are substituted as array element correctly. However the controller keeps creating and replicating the `InfrastructureMachineTemplates` of the same type.

Please check logs and objects attached.

**What did you expect to happen:**
Single instance of `InfrastructureMachineTemplates` where the values from the variable are added to it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 1.1.0
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.21.0
- OS (e.g. from `/etc/os-release`):

/kind bug
[bug.zip](https://github.com/kubernetes-sigs/cluster-api/files/8052180/bug.zip)

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
/milestone v1.2
/priority critical-urgent

+1 to backport as soon as we figure out the fix

**Comment by killianmuldoon** [comment]
@weikaipan Could you add the templates referenced in the bug-clusterclass yaml? That would make this easier to reproduce.

**Comment by sbueringer** [comment]
I added the missing objects manually by just guessing how they probably look like.

I got the following results:

### With exactly the same patch definition as in the zip file

I get the following errors (but no machine templates are created):
> E0214 18:56:54.178543      16 controller.go:317] controller/topology/cluster "msg"="Reconciler error" "error"="error computing the desired state of the Cluster topology: failed to apply patches: failed to generate patches for patch \"volumes\": failed to generate JSON patches for template MachineDeployment/InfrastructureMachineTemplate infrastructure.cluster.x-k8s.io/v1beta1/VSphereMachineTemplate, MachineDeployment topology linux-workers, MachineDeployment class linux-worker: failed to calculate value for template: failed to unmarshal rendered template: \"[map[capacity:map[storage:2Gi] mountPath:/var/lib/containerd name:containerd]]\\n\": error converting YAML to JSON: yaml: did not find expected ',' or ']'" "name"="my-cluster-bug" "namespace"="vsphere" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" 

This makes sense as `{{ .volumes }}` is rendered as `[map[capacity:map[storage:2Gi] mountPath:/var/lib/containerd name:containerd]]` and as this is not a valid JSON/YAML the reconcile just returns an error (without creating a machine template)

### When using `valueFrom.variable: "volumes"`

In this case infinite VSphereMachineTemplates are created. The reconcile tries to create a VSphereMachineTemplate with the following volumes field
```yaml
spec:
  template:
    spec:
      - mountPath: '/var/lib/containerd'
         name: 'containerd'
         capacity:
           storage: '2Gi'
```
This is looks valid and the create call for this VSphereMachineTemplate **does not fail**. **But** the resulting VSphereMachineTemplate does not have the field at all.

As this is different to the desired state, infinite VSphereMachineTemplates are created. If I saw correctly the issue is that the `volumes` field doesn't exist in the CRD definition. So I think the apiserver just prunes the field without an error.

I'm not sure if we have any alternative to detect that the create call didn't actually create the resource as expected. If there is an error on creation we handle that gracefully (just returning an error and not creating any resources)

**Comment by sbueringer** [comment]
Ups, just saw that there's an additional `VSphereMachineTemplate` crd in config/supervisor/crd which wasn't deployed in my tilt cluster.

So just echo'ing what Killian said. I think we need all resources (+/- the values shouldn't matter if they should be confidential).

Also I wonder how the PatchDefinition looks like, as the reconciler failed way earlier with the one in the zip file.

**Comment by weikaipan** [comment]
Thank you. I have uploaded the entire templates including ClusterClass and `VSphereMachineTemplate`.

[cluster-clusterclass.zip](https://github.com/kubernetes-sigs/cluster-api/files/8066360/cluster-clusterclass.zip)

**Comment by sbueringer** [comment]
I can't replicate the issue with the files in the zip file.

I observed the following issues:
* the VSphereClusterTemplate, KubeadmControlPlaneTemplate, VSphereMachineTemplates, KubeadmConfigTemplate had `-volume` suffix, but the ClusterClass uses templates without that suffix
    * => I fixed that, otherwise the topology reconciler would have failed very early. Do you maybe have additional resources deployed in your cluster?

* Then VSphereMachineTemplate could not be created with the following error:
    ```bash
    failed to create VSphereMachineTemplate.vmware.infrastructure.cluster.x-k8s.io: FieldValueInvalid: 
    spec.template.spec.volumes: Invalid value: "string": spec.template.spec.volumes in body must be of type array: "string"
    ```
    * The patch value renders to string: "<no value>" (because `{{ .volumes }}` is used, but the variable is called foo)

**Comment by sbueringer** [comment]
@fabriziopandini 
I think in a situation like on this issue it should be possible to make it safe for users by specifying the variable schema on the ClusterClass correctly.

I.e. if the variable schema looks like this:
```yaml
        openAPIV3Schema:
          type: array
          items:
            type: object
            properties:
              name:
              ...
              capacity:
              ...
```
we should make sure that a variable value like this is never stored in etcd:
```yaml
        value:
          - mountPath: '/path' # should be pruned
            name: 'containerd'
            capacity:
              storage: '2Gi'
```

It looks like upstream Kubernetes has two features for this:
1. kubectl on client-side validates the OpenAPI schema and returns an error like this:
  > error: error validating "./cluster-bug.yaml": error validating data: ValidationError(Cluster.spec.topology): unknown field "abc" in io.x-k8s.cluster.v1beta1.Cluster.spec.topology; if you choose to ignore these errors, turn validation off with --validate=false
2. If validate=false is used the APIserver prunes unknown fields, before storing the object in etcd. I think this should be relatively easy to do by calling the Prune upstream func in our mutating ("defaulting") webhook.

**Comment by fabriziopandini** [comment]
@weikaipan to confirm above assumptions + eventually close
@sbueringer  +1 to track possible improvements in separated issues; in order to provide a batter UX I think we should block users to create variables with fields non defined in the API schema (like kubectl); pruning on storage could be implemented as a safeguard

**Comment by weikaipan** [comment]
Confirmed that removing the unknown fields, the repeating roll outs stop and the template generation succeeded. Thank you.
