### ISSUE TITLE
Machine controller with namespace

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#62]
_From @medinatiger on January 26, 2018 23:13_

The current implementation assume default namespace. The machine controller need to handle resource from multiple namespace.

_Copied from original issue: kubernetes/kube-deploy#520_

**Comment by rsdcastro** [comment]
_From @krousey on January 27, 2018 0:10_

I think for initial implementation, it would be ok to handle a single namespace.

**Comment by rsdcastro** [comment]
I believe this issue is not specific to GCP but the common machine controller code, so marking it as such.

**Comment by spew** [comment]
Being worked on in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/156

**Comment by davidewatson** [comment]
Even though https://github.com/kubernetes-sigs/cluster-api/pull/156 has been merged, [these](https://github.com/kubernetes-sigs/cluster-api/blob/master/clusterctl/clusterdeployer/clusterapiservertemplate.go) resources are still deployed to the default namespace. The cluster deployer also assumes the default namespace [here](./clusterctl/clusterdeployer/clusterclient.go).

Since there is another ticket for [Support cluster and machine in multiple namespaces in clusterctl create](https://github.com/kubernetes-sigs/cluster-api/issues/252) I think we can close this.

**Comment by vincepri** [comment]
@davidewatson The links to the resources are giving me 404, is this issue still relevant?
