### ISSUE TITLE
Support password from secret in KubeadmConfig

### ISSUE THREAD

**Issue by weikaipan** [kubernetes-sigs/cluster-api#6247]
**User Story**

As a user/operator I would like to supply a Kubernetes API object from `Cluster.spec.variables` and `Patch` can apply the content for passing these content to `KubeadmConfigTemplate`

**Detailed Description**

One example use case is `KubeadmConfigTemplate.spec.users.password`. As a user, they would like to create a `Secret` object and let patching configure the password sourcing `Secret` object.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
+1 to Vince's comment.

Retrieving variable values from resources would also have a big impact on variable validation on Cluster and ClusterClass creation/updates.

**Comment by fabriziopandini** [comment]
For context, `KubeadmConfigTemplate.spec.users.password` expect a hash (not a plain text password); and also a copy/paste of the cloud-init documentation that provides context about limitations of the underlying primitive. 

#   passwd: The hash -- not the password itself -- of the password you want
#           to use for this user. You can generate a safe hash via:
#               mkpasswd --method=SHA-512 --rounds=4096
#           (the above command would create from stdin an SHA-512 password hash
#           with 4096 salt rounds)
#
#           Please note: while the use of a hashed password is better than
#               plain text, the use of this feature is not ideal. Also,
#               using a high number of salting rounds will help, but it should
#               not be relied upon.
#
#               To highlight this risk, running John the Ripper against the
#               example hash above, with a readily available wordlist, revealed
#               the true password in 12 seconds on a i7-2620QM.
#
#               In other words, this feature is a potential security risk and is
#               provided for your convenience only. If you do not fully trust the
#               medium over which your cloud-config will be transmitted, then you
#               should use SSH authentication only.
#
#               You have thus been warned.

+1 to turn this into a CABPK enhancement

**Comment by schrej** [comment]
In addition, copying a value from a secret into another API object that isn't a secret makes using a secret in the first place pretty useless, doesn't it?

**Comment by fabriziopandini** [comment]
Adding some note on CABPK changes

A new `PasswdFrom` field should be added to https://github.com/kubernetes-sigs/cluster-api/blob/8941f168e9b45c0d94267cd957eaa3d1bba36a97/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L280-L282

The type of this field should be named `PasswdSource` and mirror what we have for `FileSource`.

Once the new file is added and API conversion implemented in order to not loose the information when roundtripping from v1beta1-->oldVersion-->v1beta1, like e.g. https://github.com/kubernetes-sigs/cluster-api/blob/8941f168e9b45c0d94267cd957eaa3d1bba36a97/bootstrap/kubeadm/api/v1alpha4/conversion.go#L53

Then the controller should retrieve the info before generating the cloud-init/ignition script, like we are doing for `resolveFiles`, e.g.

https://github.com/kubernetes-sigs/cluster-api/blob/8941f168e9b45c0d94267cd957eaa3d1bba36a97/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L444-L448

In this case, we should implement resolveUsers, and the return value can be used to override https://github.com/kubernetes-sigs/cluster-api/blob/8941f168e9b45c0d94267cd957eaa3d1bba36a97/bootstrap/kubeadm/internal/controllers/kubeadmconfig_controller.go#L456

**Comment by sbueringer** [comment]
@fabriziopandini Q: Follow-up similar kind of validation like we have for Content & ContentFrom? (e.g. that they shouldn't be set at the same time)

**Comment by vincepri** [comment]
Please rename the issue once we're in agreement on next steps

**Comment by weikaipan** [comment]
@sbueringer 

> @fabriziopandini Q: Follow-up similar kind of validation like we have for Content & ContentFrom? (e.g. that they shouldn't be set at the same time)

Can you elaborate the validation that needed for this issue? Thank you.

**Comment by sbueringer** [comment]
Sure. Here is how we validate content/contentFrom: https://github.com/kubernetes-sigs/cluster-api/blob/ffc99439dc5fdd195b0e57f9af7644d79010afc5/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_webhook.go#L108-L140

I think we have to think about what combinations of set/unset fields are valid for password/passwordFrom and then implement a validation for that. It's probably pretty similar to content/contentFrom

**Comment by willemm** [comment]
Oh dang, I thought this would be useful for my use-case but turns out it's not useful at all.

Use case: We need to pass a password to one of the commands in postKubeadmCommands, so it can authorize itself (in our case, join a domain realm).
