### ISSUE TITLE
Make listObjByGVK retry with backoff

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6261]
**What steps did you take and what happened:**
the func `listObjByGVK` is used in clusterctl during the upgrade process, however this function does not implements a retry/backoff loop so it makes this bit of code sensible to transient errors that can happen during upgrades / in environments with poor network connections.

e.g.
```
Performing upgrade...
Scaling down Provider="cluster-api" Version="" Namespace="capi-system"
Scaling down Provider="bootstrap-kubeadm" Version="" Namespace="capi-kubeadm-bootstrap-system"
Scaling down Provider="control-plane-kubeadm" Version="" Namespace="capi-kubeadm-control-plane-system"
Scaling down Provider="infrastructure-aws" Version="" Namespace="capa-system"
Deleting Provider="cluster-api" Version="" Namespace="capi-system"
Error: failed to upgrade management cluster providers: failed to apply providers upgrade: failed to list objects for the "infrastructure.cluster.x-k8s.io/v1beta1, Kind=AWSClusterControllerIdentity" GroupVersionKind: conversion webhook for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=AWSClusterControllerIdentity failed: Post "[https://capa-webhook-service.capa-system.svc:443/convert?timeout=30s](https://capa-webhook-service.capa-system.svc/convert?timeout=30s)": dial tcp 100.64.252.115:443: connect: connection refused
```

**What did you expect to happen:**
clusterctl to be resilient to temporary network problems.

**Anything else you would like to add:**
An example of retry look in clusterctl

https://github.com/kubernetes-sigs/cluster-api/blob/dcc22db766eb36c5548970fda3251efd2ebd595b/cmd/clusterctl/client/cluster/proxy.go#L237-L244

/kind bug

**Comment by ykakarap** [comment]
Other places in the upgrade flow that could also benefit from similar refactor to be more resilient to network problems:
* Deleting a resource: 
https://github.com/ykakarap/cluster-api/blob/5026786ee809c5def466049f5befd2a786fbcefa/cmd/clusterctl/client/cluster/components.go#L215-L222
This could be addressed immediately with the same kind of refactor. @fabriziopandini Can I make this part of the same PR #6262 ?
* repository `GetFile` function - This will need to be handled differently for different repositories (github might need retry - others probably not). It would be nice to have the `GetFile` functions itself resilient to network problems instead of wrapping it in a retry block everywhere we use it. Thoughts?

**Comment by fabriziopandini** [comment]
@ykakarap let's break down in separated PR, so we can decide for cherry-picking case by case

**Comment by sbueringer** [comment]
I wonder if this can be implemented more holistically. E.g. in other clients it's just possible to configure a retry count and then it will automatically retry whenever necessary.

I have no idea if that's directly possible with the client-go client or the underlying go http client.

**Comment by ykakarap** [comment]
PR for addressing the delete resource point in https://github.com/kubernetes-sigs/cluster-api/issues/6261#issuecomment-1060620932: https://github.com/kubernetes-sigs/cluster-api/pull/6266
