### ISSUE TITLE
CAPI vs cert-manager release cadence 

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#6442]
This is a follow up of the 20th of April office hours discussion

Cert Manager project is stabilizing on a [high-frequency release cadence](https://cert-manager.io/docs/installation/supported-releases/#support-policy), with each release being supported for a period of four months, and new release every two months.

In CAPI we depend on cert-manager but we have a less stable release calendar and so:
- we should consider how to keep up with cert-manager version, with the possible implications being
  - dealing with cert-version minimum Kubernetes version changes (thus impacting the minimum Kubernetes version for CAPI management Cluster
  - dealing with deprecated cert-manager features
- we should consider at which extent we want to do so, e.g. what about the cert-manager version used in older branches

Taking a step back, IMO this is a good opportunity for the project to aim for a more predictable release cadence, that could help not only in defining an answer to the above issue but also in providing better predictability for everyone building on top of Cluster API.

More specifically, a first step could be to move from the ~ two releases per year to 3, thus matching Kubernetes release cadence + eventually some gap. This comes with some implications, like e.g a more structured "discipline" in defining the roadmap/release payload, managing proposal etc.

@CecileRobertMichon  @vincepri @enxebre @sbueringer 
opinions?

**Comment by vincepri** [comment]
Action items / follow-up from community meeting:

- [ ] Figure out release cadence.
- [ ] Deprecation policy in contributing guide, figure out what's x in N-(x) supported versions.
- [ ] Continue evaluating improvements/automations for the release process.

**Comment by CecileRobertMichon** [comment]
Trying to summarize in writing what I said during office hours:

- I'm personally +1 to smaller, more frequent CAPI releases. More frequent, smaller releases are easier to adopt for providers, especially since CAPI feature velocity is still very high. For end-users, upgrading the CAPI version when the new "minor" release contains hundreds of commits is scary.  
- The downside to more frequent releases is more work/overhead for project maintainers to get releases out. However, we can mitigate this by making the release process as automated and as lightweight as possible. I believe we have made a lot of progress on automating the [release process ](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/developer/releasing.md) over the past year. Release notes, release artifacts upload, release draft creation, and image promotion are all automated now. A lot of the [remaining manual work](https://github.com/kubernetes-sigs/cluster-api/issues/5967) is around CI and prepping the branch/book. Excluding releases that bump the API version (these are a lot more work and should be less frequent), I believe we can reduce a lot of this work by relying on best practices of CI/CD, making our book, CI, and repo resilient to new minor releases so we can eliminate as many of these tasks as possible. For example, removing all hardcoded version references in the book and docs so we don't have to update them for every minor release. Everything we can't eliminate, we can try automating as much as possible by leveraging GitHub Actions.
- I'm a strong believer that releases should be time-based and not feature-driven. If we are transparent with users about our release schedule, it's easier for them to plan around it. It's also easier for contributors from various companies to plan work around deadlines for releases. Milestones are great for giving observers an idea of what work we're aiming to get done in the current release and to help prioritize work, but they should never be used to gate releases. It's one thing to block a release because of a bug or regression, but delaying releases for unfinished feature work should be avoided. Furthermore, the main branch should be releasable (meaning no half-done PR / feature should ever get merged). Of course, this works better if releases are fairly frequent. When releases are frequent, it doesn't matter if you miss a release because you can simply target the next one.
- On the topic of supporting previous releases (ie. backporting bug/security fixes and releasing patch versions), we have tried to keep the number of releases we support at any given time small to reduce the maintenance cost. So far, this has been 1 minor per API version. However, since we are past EOL for both v1alpha3 and v1alpha4 now, it makes sense to re-evaluate. Practically speaking, it's unreasonable to expect a user to upgrade to the new feature/minor release in order to receive bug fixes on day 1 of the new release. We should give users a grace period of at least a few months to upgrade. In practice, this might mean supporting the last 2 or 3 minor releases at any given time. For example, if we agree to release a CAPI minor release every quarter (once every 3 months), we could say each release is supported for 6 months, meaning we support 2 release branches at any given time. 
- Finally, I want to thank @fabriziopandini for starting the discussion. Evolving our release process and being transparent with our users is a big step in becoming a mature project. I also want to thank the cert-manager maintainers for setting a great example of documenting a release process, https://cert-manager.io/docs/installation/supported-releases/#support-policy makes it really easy to understand when to expect cert-manager releases and what the support policy is for existing releases.

**Comment by fabriziopandini** [comment]
Thanks for the great summary!
(hopefully) I can work on an updated version of our support policy document sometime after KubeCon; if someone wants to take a stab at this before I can get to it or pair in this effort, feel free to jump in

**Comment by sbueringer** [comment]
Regarding cert-manger: Looks like they are re-considering their release cadence: https://docs.google.com/document/d/1Tc5t6ylY9dhXAan1OjOoldeaoys1Yh4Ir710ATfBa5U/edit#heading=h.7h8rkitcxn99

> Action items
> Ash to propose a 3 month release cycle, delaying 1.9 by 1 month

**Comment by sbueringer** [comment]
@CecileRobertMichon Sounds very reasonable to me!

I think it makes sense to only support the last 2 or 3 releases. This implies that the support duration depends on the release cadence, which I think is fine.

If I saw correctly we now only have to cut down the release overhead and get consensus on the release cadence.


One question regarding:
> Furthermore, the main branch should be releasable at all times (meaning no half-done PR / feature should ever get merged)

I definitely agree with the main branch should be releasable at all times. But I'm not sure about the conclusion.

Let's assume we develop a feature behind a feature gate like ClusterClass or RuntimeSDK. The only alternative to merging those kind of features step-by-step is to develop on a feature branch for months and then merge them at once. But I think as long as those features are behind a feature gate and they don't break the current behavior of CAPI when the feature gate is enabled, it doesn't make the main branch unreleaseable. What do you think?

**Comment by CecileRobertMichon** [comment]
> But I think as long as those features are behind a feature gate and they don't break the current behavior of CAPI when the feature gate is enabled, it doesn't make the main branch unreleaseable. What do you think?

agreed.
