### ISSUE TITLE
Support idempotent clusterctl init usage

### ISSUE THREAD

**Issue by timoreimann** [kubernetes-sigs/cluster-api#6471]
**User Story**

As a developer/operator I would like to run `clusterctl init` with specific provider flags/versions in an idempotent way to simplify developer workflows.

**Detailed Description**

In my organization, developers use (a wrapped version of) `clusterctl` to bring up clusters for development and testing purposes. We want to enforce specific provider versions to ensure consistent behavior and avoid version drift.

`clusterctl init` already support specifying provider versions for this purpose, e.g.:

```
clusterctl init --core cluster-api:v0.4.8 --control-plane kubeadm:v0.4.8
```

This works well when a management cluster has not been brought up yet. However, if it has and the command is run again with the flags, an error is returned:

```
Error: installing provider "cluster-api" can lead to a non functioning management cluster: there is already an instance of the "cluster-api" provider installed in the "capi-system" namespace
```

We work around the issue by detecting if a given provider is already installed (by checking if the corresponding Deployment exists) and adjust the `clusterctl init` flags accordingly. This feels a bit tedious / cumbersome though -- ideally, `clusterctl` should only error out if any of the given versions diverge, thereby better serving gitops / idempotence needs.

(There might also be a potential to trigger an upgrade if the versions diverge, though that may be for a different feature request.)

Related Slack convo with @vincepri at https://kubernetes.slack.com/archives/C8TSNPY4T/p1651502359080819.

/kind feature

**Comment by vincepri** [comment]
cc @ykakarap 

/milestone v1.2
/area clusterctl

**Comment by ykakarap** [comment]
This sounds like a good addition and from the slack discussion referenced in the issue it looks like we have agreement on this.

I opened a #6474 to make `clusterctl init` idempotent. 

In the meantime another way to check if a provider is installed on the cluster could be to use `k get providers`. 
This lists the providers installed on the cluster (if the providers are installed with `clusterctl init`). 
This will have additional benefit of being able to quickly identify the type and version of the provider instead of having to do string manipulations if using deployment objects to fetch the same information.
```
$ k get providers -A
NAMESPACE                           NAME                    AGE   TYPE                   PROVIDER      VERSION
capi-kubeadm-bootstrap-system       bootstrap-kubeadm       54s   BootstrapProvider      kubeadm       v1.1.3
capi-kubeadm-control-plane-system   control-plane-kubeadm   52s   ControlPlaneProvider   kubeadm       v1.1.3
capi-system                         cluster-api             55s   CoreProvider           cluster-api   v1.1.3
```
