### ISSUE TITLE
Machine::IsBootstrapped will wait indefinitely if "kubeadm init" fails

### ISSUE THREAD

**Issue by isaacdorfman** [kubernetes-sigs/cluster-api#6476]
**What steps did you take and what happened:**
This does not cause the system to crash but many implementations get stuck because of this issue.
*Create a machine where "kubeadm init" fails.
*Wait for "/run/cluster-api/bootstrap-success.complete" to be created.
*Get stuck indefinetly.

**What did you expect to happen:**
If kubeadm fails then there is no way for an external control to know if it failed or didn't finish,
because currently the sentinelFileCommand is "echo success > /run/cluster-api/bootstrap-success.complete".
The sentinelFileCommand should either write failure to this file in case of failure or either create some kind of bootstrap-success.finished file to report that the command is done.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by killianmuldoon** [comment]
/area control-plane

I think it's a good idea to fix this - I'll take a look into it and see what the options are. @isaacdorfman what process do you think should watching the new sentinel file or report the bootstrap failure?

**Comment by fabriziopandini** [comment]
I'm personally -1 to write failure into "/run/cluster-api/bootstrap-success.complete" because IMO this could cause confusion unless we change the name of the file/the current contract about it, so tagging this as feature.
/remove-kind bug
/kind feature
/milestone v1.2

Q: How are you running "Wait for "/run/cluster-api/bootstrap-success.complete" to be created.", is that implemented using post kubeadm commands? AFAIK if you get to run post kubeadm commands and the "/run/cluster-api/bootstrap-success.complete" does not exist you can guess failure...

**Comment by fabriziopandini** [comment]
/triage accepted
pending for feedback...
