### ISSUE TITLE
Security Self Assessment: [STRIDE-DOS-2] Misuse of Infra Admin credentials to create unlimited number of clusters

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes-sigs/cluster-api#6516]
**User Story**

As an operator, I would like to apply soft/hard limits on maximum number of clusters so that I don't end up exhausting available capacity
As an operator, I would like to apply rate limits on clusterctl and underlying APIs on concurrent and successive requests to create new clusters so that I don't end up creating large number of clusters in short period of time exhausting available capacity

**Detailed Description**

Snippet from Cluster API security self-assessment: https://github.com/kubernetes/sig-security/pull/40

STRIDE-DOS-2 - Misuse of Infra Admin credentials to create unlimited number of clusters
Infra Admin credentials can be misused by someone who has access to it by accidentally or maliciously creating very large number of clusters to exhaust capacity or slow down the operations team or for financial damage caused due to surprise bills

STRIDE-DOS-2 Recommended Mitigations

- Create safe defaults (soft and hard) for the maximum number of clusters that can be created using a management cluster
- Apply rate limits on clusterctl and underlying APIs on concurrent and successive requests to create new clusters can be processed using the same Infra admin
- Implement threshold based alerts when a particular soft limit is exceeded for number of clusters

Alerting can be done by end users once these limits are set

/kind feature
/sig security
/area security

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/triage accepted
/help

Still a valid point to document some general best practices, but providing specific guidance for each cloud infrastructure should be addressed by cloud providers

I'm not sure that we can/we should apply rate limits on clusterctl and underlying APIs on concurrent and successive requests because technically complex; also it does not prevents to use of credentials in other ways so it doesn't solve the problem
IMO the only real solution to avoid this risk is to rely on infrastructure quota management

**Comment by fabriziopandini** [comment]
I'm collapsing this issue into https://github.com/kubernetes-sigs/cluster-api/issues/6152 to see if we can make some progess
/close
