### ISSUE TITLE
How to remove failure domains from cluster

### ISSUE THREAD

**Issue by vipamadi** [kubernetes-sigs/cluster-api#6536]
Hi!

We have some problems after deleting some control planes nodes at our TKG cluster.
Previously we tested failure domains so we created kind objects VSphereDeploymentZone and VSphereFailureDomain but we deleted them after some tests.
But now, every time we remove a control plane node the new control plane node is created with the old spec.failureDomain value at the machines.cluster.x-k8s.io object.

Please, how could we remove all the references to this removed failure domain.

This is our cluster status:

```
# kubectl get cluster -n guadix-workload-cluster -o yaml
apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  ...
  status:
	...
    controlPlaneReady: true
    failureDomains:
      failure-domain-a:
        controlPlane: true
      failure-domain-b:
        controlPlane: true
    ...
```

**Comment by killianmuldoon** [comment]
I think the way to do this is to update the ControlPlane object. I'm not familiar with the ins and outs of how TKG (Tanzu) handles this though - might be a better question to ask of them specifically - maybe over at https://github.com/vmware-tanzu/community-edition ?

**Comment by sbueringer** [comment]
Sounds like vSphere has an additional concept (VSphereDeploymentZone,VSphereFailureDomain). Maybe CAPV folks know more about it: cc @srm09 @aartij17

**Comment by fabriziopandini** [comment]
/triage accepted

Cluster.status.Failure domain should automatically align with what reported by the infrastructure provider

https://github.com/kubernetes-sigs/cluster-api/blob/e70fef893f068085b2ada4ae09f96948cb65b22c/internal/controllers/cluster/cluster_controller_phases.go#L191-L197

If we can confirm if the infrastructure provider used in this case was properly reporting the updated list, then we can investigate why the CAPI part is not working as expected; otherwise the problem is on the provider side

/help

**Comment by sbueringer** [comment]
I wonder if this was already solved in:
* https://github.com/kubernetes-sigs/cluster-api/pull/5479
* https://github.com/kubernetes-sigs/cluster-api/issues/6732

cc @srm09

**Comment by fabriziopandini** [comment]
/close

due to lack of feedback
