### ISSUE TITLE
scripts/ci-build.sh should fail if bazel fails

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes-sigs/cluster-api#660]
/kind feature

**Describe the solution you'd like**
If you use a really old version of bazel, `./scripts/ci-build.sh` will output errors about bazel failing but the makefile will continue running and finish with a successful exit code (luckily, `./scripts/ci-test.sh` actually fails, so we won't merge a PR that breaks bazel). 

I don't know which version of bazel is required for the build to work, but 0.15 failed and 0.21 passed, so it's somewhere in between those two. 

We should also fix the developer documentation (in the gitbook or CONTRIBUTING.md) to mention that installing bazel is required and note a minimum version. 

**Anything else you would like to add:**
It's also broken for `./scripts/ci-make.sh` and we should fix that as well. 

**Environment:**

- Cluster-api version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by nzoueidi** [comment]
Hey @roberthbailey, is this still needed? I PM'ed you in Slack but seems like you didn't notice my pm.

**Comment by roberthbailey** [comment]
@nzoueidi - I've been out of the office for a few days, so I haven't been keeping up on slack. 

@justinsb - In slack @nzoueidi said "As far as I know, that bazel is going to be deprecated, probably we gonna use nfpm instead of bazel." This is the first I've heard that we are going to deprecate bazel. Since you seem to be a big proponent of bazel, care to comment?

**Comment by vincepri** [comment]
AFAIK, Bazel is here to stay. 

This issue is still needed and you can assign it to yourself by using `/lifecycle active` command. There is a little more context here as well https://github.com/kubernetes-sigs/cluster-api/pull/676#issuecomment-453720530.

**Comment by ncdc** [comment]
Yes, bazel is not going anywhere. We are discussing using other tooling to build rpm/deb packages, and that's presumably what @nzoueidi was referring to.

**Comment by nzoueidi** [comment]
That's what I was referring to, thanks @ncdc. I might need to think twice before I write my sentences next time :)

**Comment by dpb587-pivotal** [comment]
Seems the issue is the use of `|| true`. The underlying `make gazelle` command always exits 0. Not sure the background of the current `|| true` behavior, but it appears to have been introduced in https://github.com/kubernetes-sigs/cluster-api/pull/631.

https://github.com/kubernetes-sigs/cluster-api/blob/a493ad0b33e5b215154404674e7861f2ebc710e8/Makefile#L43-L44

Is it preferable to assume/require `bazel` to be present and remove the `which`/`true` behaviors (like seems to be the case in [other](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/1aa10aafd7bb2b908a13bd7cc0af55d5cb3d2ab2/Makefile#L142) [repos](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/9d988a5a7025840b0842904a776f77dc91ae0066/Makefile#L161) using bazel)?

**Comment by ncdc** [comment]
@liztio I know you've been busy on other things - just wanted to check in & see if you'd made any progress here?
