### ISSUE TITLE
Add metrics for realtime investigation of disconnected wl scenarios

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api#7147]
**User Story**

As a developer running CAPI in far separated networks, id like kubeadm controlplane manager to give me a delta between healthy nodes thats easy to read, i.e. 

if i do a simple disconnect experiment on a WL cluster (w CP node w/ etcd on it), 

``` 
sudo iptables -i eth0 -A INPUT -s 10.180.83.152 -j DROP 
```

I can see that disconnect is logged easily... and i cant easily ascertain how many nodes are / arent making that etcd connection (and yes, in general, i understand there are higher level declarative constructs and that using logs for everythign are an antipattern, but... in the real world, being able to see etcd client statistics, in realtime, is much more useful to quickly hypothesize a failure mode).

So my suggestion would be i think some kind of 

```
failures := 0
for each etcd in my WL children:
   passed := check the etcd
   ip := etcd.ip 
   stats[ip] = passed 
   if !passed:
      failures += 1

log.Infof("etcd polling results: %v, failures %v", stats, failures)
```

in the logs ... 

# Desired output 

```
I0901 14:00:29.382055       1 round_trippers.go:553] GET https://10.180.81.244:6443/api?timeout=10s  in 10000 milliseconds
... 
E0901 14:00:29.384611       1 controller.go:317] controller/kubeadmcontrolplane "msg"="Reconciler error" "error"="[cannot get remote client... 
... 
I0911 14:00:29.382055       1 controller.go:553] etcd polling results 
[1.2.3.4: true, 
 1.2.3.5: false, 
 1.2.3.6: true
], 
 failures: 1 
```

# Current output

```
I0901 14:00:29.382055       1 round_trippers.go:553] GET https://10.180.81.244:6443/api?timeout=10s  in 10000 milliseconds
E0901 14:00:29.382397       1 controller.go:188] controller/kubeadmcontrolplane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/tkg-vc-antrea\": Get \"https://10.180.81.244:6443/api?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" "cluster"="tkg-vc-antrea" "name"="tkg-vc-antrea-control-plane" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane"
E0901 14:00:29.384611       1 controller.go:317] controller/kubeadmcontrolplane "msg"="Reconciler error" "error"="[cannot get remote client to workload cluster: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/tkg-vc-antrea\": Get \"https://10.180.81.244:6443/api?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), failed to create remote cluster client: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/tkg-vc-antrea\": Get \"https://10.180.81.244:6443/api?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]" "name"="tkg-vc-antrea-control-plane" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane"
I0901 14:00:29.385855       1 round_trippers.go:553] GET https://10.180.80.169:6443/?timeout=5s 200 OK in 3 milliseconds
I0901 14:00:29.388442       1 controller.go:251] controller/kubeadmcontrolplane "msg"="Reconcile KubeadmControlPlane" "cluster"="tkg-vc-antrea" "name"="tkg-vc-antrea-control-plane" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane"
``` 

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by killianmuldoon** [comment]
Would it be better to raise a metric for this instead? Using logs to capture metrics seems like a strange approach.

**Comment by fabriziopandini** [comment]
I understand that not small clusters don't have full-blown monitoring, but at the same time I don't we should build into our controllers/API a system to count failures across different reconcile because this comes with some immediate drawbacks
- it requires some persistent state to ensure counters survive controller restarts
- if we use existing API objects as API state, this will impact the system performance (a reconcile triggered in many controllers as soon as we increase the counters)
- if we use some other sort of persistent storage, it will impact how we deploy things/add more constraints

Accordingly, I'm +1 to address this using metrics

**Comment by sbueringer** [comment]
+1 Sounds reasonable.

Apparently there is an integration between grpc and Prometheus and etcd has an example on how to combine them: https://github.com/etcd-io/etcd/blob/main/tests/integration/clientv3/examples/example_metrics_test.go

**Comment by jayunit100** [comment]
it doesnt require persistent state really, its just a heuristic.  and a hashtable at that :).

**Comment by jayunit100** [comment]
.... Agree nothing beats a lavish grafana dashboard but in chaotic situations a "dumb" alternative is needed.

What's the workaround for people experiencing a netsplit from wL etcd ... running hundreds of clusters, and not enabling prometheus at the mgmt layer?

**Comment by jayunit100** [comment]
@fabriziopandini  prometheus histograms.... dont they  already give us this for free in memory ?  I don't see the persistent state corrallary.  But I agree this shouldn't be an overblown crd / api level thing. More like a logging point in time heuristic.

**Comment by sbueringer** [comment]
> running hundreds of clusters
> not enabling prometheus at the mgmt layer?

They don't need Prometheus specifically, but running Kubernetes clusters at that scale in production without monitoring doesn't sound sane to me.

>  prometheus histograms.... dont they already give us this for free in memory ?

Yup they should. I think Fabrizio meant if we build our own instead of just using metrics.

> it requires some persistent state to ensure counters survive controller restarts

If solved with normal metrics that's usually fine. For normal counters usually rates are used (e.g. error per minute vs absolute error count) and Prometheus handles it usually well if a counter starts from 0 after a restart. Not exactly sure how it works with histograms, but I don't expect problems there if we implement normal metrics.

> that don't require running extra tools to get a quick topology of etcd polling failures for large / edge like scenarios. Any thing come to mind ?

I think the first step should be to implement the regular metrics. 

Then we can think of how users could consume them if they don't want to use Prometheus / a regular metrics tool.
I could imagine folks could add a sidecar container which does a curl against the metrics endpoint regularly and prints the results. I'm not a big fan of it, but as that would be outside of the scope of Cluster API itself .... I'm fine with that.

**Comment by jayunit100** [comment]
The answer to any logging problem can be better metrics and alerting, but logs are just a batteries included solution that work anywhere.

And  w non traditional capi deployments is there is no monitoring infrastructure guarantee.

The advantage of some kind of log in here or other lightweight aggregation is that it makes the diagnosis immediate and transparent.

**Comment by fabriziopandini** [comment]
renamed since there is agreement on the first step, which is implementing metrics helping to investigate connection problems
/triage accepted

**Comment by sbueringer** [comment]
/close

in favor of #11272
