### ISSUE TITLE
Clarify that failureReason & failureMessage are terminal in provider's implementers docs

### ISSUE THREAD

**Issue by zhaodiaoer** [kubernetes-sigs/cluster-api#7191]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
If external object (like bootstrapConfig/infrastructureMachine) experienced some failure and exposed failureReason
or failureMessage in `status`, even if that external object recovered and failureReason or failureMessage is cleanup,
current object will not sync this cleanup ,the current object's phase will keep in failed.

**What did you expect to happen:**
Because external object CRD & Controller may be implemented by other developers, should we handing external object failure 
recovery scenarios?
I think we should accept that the current object is automatically recovered after the external object is recovered, and the external object may be recovered by manual intervention

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Thank for @sbueringer remind ,there are some documents point out failureReason & failureMessage is used for descript `fatal` error, but if `fatal` meaning `not recoverable` is not clear

https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html?highlight=failureReason#bootstrap-api-resource
https://cluster-api.sigs.k8s.io/developer/providers/cluster-infrastructure.html?highlight=failureReason#infracluster-resources
https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html?highlight=failureReason#data-types

**Environment:**

- Cluster-api version: any
- minikube/kind version: any
- Kubernetes version: (use `kubectl version`): any
- OS (e.g. from `/etc/os-release`): any

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
I'm not very sure if this is a `bug`, if we define failureReason and failureMessage to be used in case of unrecoverable errors,
a `/document` label may be more suitable label

**Comment by fabriziopandini** [comment]
I'm not sure this is a bug, given that AFAIK Failure Reason and Message are intended for surfacing terminal failures.

**Comment by zhaodiaoer** [comment]
If we decied that Failure Reason and Message are intended for surfacing terminal failures, I think there are some work to do:

1. Provide more clearer descriptions of `Failure Reason` and `Failure Message` fields in provider contracts guide documents and point out that once any failure field has been filled, the object which referenced to the provided object can not be recoveryed forever.
2. (optimisation)  Stop more earlier when reconciling objects whose .status.phase is failed

**Comment by dantiandb** [comment]
@fabriziopandini It seems a bit strange that there can be this inconsistent state where the infrastructure ref recovers yet phase stays failed for the CAPI resource. Having failure reason / failure message be terminal states seems like a footgun for many provider implementations if the onus is on them to only set these fields in those cases (I ran into this issue using both CAPA/CAPZ).

Wondering why we're against allowing these fields to be cleared in the case of recovery in subsequent reconciliation loops? Is there a specific reason that these fields should house terminal conditions only?

**Comment by fabriziopandini** [comment]
> Wondering why we're against allowing these fields to be cleared in the case of recovery in subsequent reconciliation loops?

Might be I'm wrong, but it doesn't seem to me there was any previous discussion about changing this behavior in this thread. 

The issue author asked to improve the documentation about the current behavior in https://github.com/kubernetes-sigs/cluster-api/issues/7191#issuecomment-1244992505, and I updated the issue accordingly because it seems to me something that makes sense and immediately actionable.

Since I forgot the last time I triaged, adding
/help

> Is there a specific reason that these fields should house terminal conditions only?

This is what I know

FailureMessage/FailureConditions is an API/Contract in CAPI that has been designed a long time ago (even before I joined the project), its behavior is coded since then, and it seems to me that it is consistent across all the CAPI controllers.

I have already shared my personal suggestion about dropping those fields in the past after we introduced conditions, but we did not reach a consensus / the task did not get traction (see https://github.com/kubernetes-sigs/cluster-api/issues/3692).

Might be I'm wrong again, but my perception is that we still don't have enough consensus on this specific change, and this is something we should consider because most probably we are talking about a breaking API change, it will require an API version/contract bump, and all the providers should be updated to whatever will be the new behavior. Overall this is a considerable amount of work and it needs a group of folks really committed to making it happen.

Considering all of this is a big deviation from the author's ask, If you want to trigger a discussion about a possible API change probably it is better to have it in a separate thread.

**Comment by dantiandb** [comment]
> Might be I'm wrong, but it doesn't seem to me there was any previous discussion about changing this behavior in this thread.

Ah sorry, I was just migrating over to this thread from the one here https://github.com/kubernetes-sigs/cluster-api/issues/7332 so accidentally brought over the context there to my response in this thread as well

> Considering all of this is a big deviation from the author's ask, If you want to trigger a discussion about a possible API change, feel free to do IT, but probably it is better to have it in a separate thread.

Yup, sounds good! Thanks for providing more context :)
