### ISSUE TITLE
Document how to use multiple providers in the same management cluster

### ISSUE THREAD

**Issue by KlavsKlavsen** [kubernetes-sigs/cluster-api#7234]
We would like to be able to manage clusters in both AWS, Hetzner hcloud and Azure AKS - the docs does not seem to show anything about how that can be done.. only how to handle a single provider, which seems to exclude adding multiple provider support - to a single cluster-api instance ?

**Comment by sbueringer** [comment]
> Please note that the second rule allows to execute clusterctl init more times: the first call actually initializes the management cluster, while the subsequent calls can be used to add more providers.
> https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html

In general it should work, we just don't have CI coverage for it.

**Comment by fabriziopandini** [comment]
/triage accepted
/kind documentation

CAPI supports working with many infrastructure providers/bootstrap providers/control plane providers out of the box, but probably we are not doing a great job in highlighting this in the doc; that's something I agree we should fix
(my only recommendation is to suggest users to rely on clusterctl in this case, because it helps in ensuring all the providers are compliant with the same contract supported by CAPI)
/help-wanted

Also, as pointed out we also don't have CI coverage, but only unit test coverage as of today; given how our CI works in prow, this is not easy to fix, unless we will manage to use CAPK (kubemark) to do some scale tests or autoscaler test in the main repo, but I will treat this as a separated item.
