### ISSUE TITLE
Document guidelines around CAPI cluster scalability

### ISSUE THREAD

**Issue by cunningr** [kubernetes-sigs/cluster-api#7308]
This is not a code issue specifically but we were wondering if there exists any data or guidelines around CAPI cluster scalability.  Thinking more specifically around;

 * Number of workload clusters
 * Number of active nodes (would this be provider specific?)
 * Number of healthchecks
 * other important params?

If ball park numbers don't exist today, do we know what parameters are important to track for CAPI cluster scalability and what behaviours we might expect to see as we start to stretch the capabilities?

And finally are there any guideline for scaling a CAPI cluster in terms of which resources can be scaled up/out?

**Comment by cunningr** [comment]
Thank you for accepting this issue.  Based on the above I filed https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1349 since we are specifically interested in CAPI + CAPO currently.

**Comment by nojnhuh** [comment]
If it's within the scope of this issue, including docs describing how to perform and interpret results from those at-scale tests would be valuable too. Since exact results will likely depend on the provider like @fabriziopandini mentioned, having a common set of tests and metrics documented in CAPI would make it easy for providers to provide this kind of data to their users.

**Comment by fabriziopandini** [comment]
other issues somehow related to this one https://github.com/kubernetes-sigs/cluster-api/issues/8052 and https://github.com/kubernetes-sigs/cluster-api/issues/8306

> having a common set of tests and metrics documented in CAPI would make it easy for providers to provide this kind of data to their users.

+1 I'm advocating for metrics adoption in CAPI since a long time now, work is tracked in https://github.com/kubernetes-sigs/cluster-api/issues/7158
This would be a great point to start if someone is interested in this work

**Comment by fabriziopandini** [comment]
We now have [dashboard](https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/observability/grafana/dashboards) and [tuning guidelines](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/tuning)

The missing part is about reference data, but I'm leaning towards closing this issue since there has been no progress in the last year.

**Comment by sbueringer** [comment]
Agree

/close
