### ISSUE TITLE
Avoid writing environment variables in Tiltfile

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7430]
Today we're writing to the os environment in our Tiltfile so that clusterctl can pick up the env vars when we use clusterctl to generate a cluster.

https://github.com/kubernetes-sigs/cluster-api/blob/835c58985bc59c430a71575e8a12042e71616abf/Tiltfile#L429-L432

This was necessary because Tilt didn't support passing in env variables into cmd_button: https://github.com/kubernetes-sigs/cluster-api/blob/835c58985bc59c430a71575e8a12042e71616abf/Tiltfile#L484-L490

This has been implemented now: https://github.com/tilt-dev/tilt/issues/5910#issuecomment-1279068596

Let's try to set the env of the cmd_button (and local_resource above) and stop writing to os.environment

Note: This also requires bumping the minimum supported Tilt version (probably to v0.30.8)

/kind feature

**Comment by fabriziopandini** [comment]
/help

I think we should wait a little bit to give some room to folks to pick up with the latest tilt version, but +1 to get this cleanup implemented

**Comment by chiukapoor** [comment]
Hello Team, I have gone through the PR https://github.com/tilt-dev/tilt/issues/5910#issuecomment-1279068596. May I work on this issue?

**Comment by sbueringer** [comment]
Sure

**Comment by chiukapoor** [comment]
Along with the below `cmd_button` function's `inputs` parameter

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L523-L535

Should I update the rest of the `cmd_button` function's `inputs` parameter with `env = substitutions`?

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L537-L546

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L488-L508

/assign

**Comment by chiukapoor** [comment]
> Along with the below `cmd_button` function's `inputs` parameter
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L523-L535
> 
> Should I update the rest of the `cmd_button` function's `inputs` parameter with `env = substitutions`? @sbueringer
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L537-L546
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L488-L508
> 
> /assign

@sbueringer @fabriziopandini May you please help me with this query

**Comment by sbueringer** [comment]
What do you mean with "update the rest of the cmd_button function's inputs parameter with env = substitutions?" ?

Adding env = substitutions to the cmd_button or something with the input parameter?

The idea would be to add `env = substitutions` to all buttons in deploy_cluster_template and deploy_clusterclass

**Comment by chiukapoor** [comment]
> The idea would be to add env = substitutions to all buttons in deploy_cluster_template and deploy_clusterclass

Thanks for the clarification will update the above functions.

I meant to ask if the `inputs` parameter needs to be removed and the `env` parameter needs to be added, as once the `env` variable provides the content of list `substitutions` as an environment variable we won't need to pass it using the `inputs` parameter

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L543-L545

Also, instead of using `$NAMESPACE`, an environment variable in below code snippets, we can directly use the `substitutions` list to get the `NAMESPACE` value

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L511-L512

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L476-L477

Doing the above will help us finally remove the below workaround as well

https://github.com/kubernetes-sigs/cluster-api/blob/dba1c7095422e1c94853811613b5224c5d759938/Tiltfile#L444-L446

I will like to know your views on it @sbueringer

**Comment by sbueringer** [comment]
Please keep inputs. With inputs users can set the fields in the Tilt UI. This is a feature we want to keep.

**Comment by chiukapoor** [comment]
@sbueringer, May you please me understand how may I successfully test the changes?

While doing my research I came across https://cluster-api.sigs.k8s.io/developer/tilt.html to set up the development environment.

**Comment by sbueringer** [comment]
Follow the documentation to setup the tilt environment (with CAPD). Then make your changes and verify that you can set the variables via substitutions. If that works, verify that you can also set them via the Tilt UI (the buttons will have an input form ~ like this: https://docs.tilt.dev/buttons.html).
