### ISSUE TITLE
Framework: Support starting controller version in clusterctl upgrade tests

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api#7603]
**User Story**

As a provider developer I would like to select the controller version to start from for clusterctl upgrade tests since the provider API version can differ from the CAPI contract.

**Detailed Description**

Currently the clusterctl upgrade test always starts from the latest version supporting the selected contract:
https://github.com/kubernetes-sigs/cluster-api/blob/6c6543448bee351430e48f39883265f409c44662/test/e2e/clusterctl_upgrade.go#L265
Providers such as CAPO can have different API versions even for the same contract version. For example, CAPO v0.5 and v0.6 are both compatible with CAPI v1beta1, but have different CAPO API versions (v1alpha4 and v1alpha5). This means that there is no way to select v0.5 as starting point if v0.6 is also in the e2e config.

It is possible to work around this limitation by crafting specific e2e configs for each situation, but it is hardly convenient.

**Anything else you would like to add:**

For reference, CAPO compatibility matrix: https://github.com/kubernetes-sigs/cluster-api-provider-openstack#compatibility-with-cluster-api-and-kubernetes-versions

/kind feature

**Comment by sbueringer** [comment]
/triage accepted

Sound reasonable to me.

Looking at: https://github.com/kubernetes-sigs/cluster-api/blob/e032bec7c04c45b42d92b7bb9bd4f16765218181/test/e2e/clusterctl_upgrade.go#L262-L267

I think the easiest way is to just add additional fields to `ClusterctlUpgradeSpecInput`. I would suggest:
```go
	InitWithCoreProvider              string
	InitWithBootstrapProviders        []string
	InitWithControlPlaneProviders     []string
	InitWithInfrastructureProviders   []string
	InitWithIPAMProviders             []string
	InitWithRuntimeExtensionProviders []string
```

If one of the fields is set we would use its value directly instead of calculating it via the contract. If I see correctly the format would be something like `aws:v0.5.0`.

**Comment by fabriziopandini** [comment]
I will comment on the issue as well, I'm only a bit concerned about the spreading of versions in the config file, but as soon as we sort this out, I'm +1 for changes making the E2E test framework easier to use for providers
