### ISSUE TITLE
Define CRD field validation policy

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7634]
As of today we have 95%+ of our field validation in webhook code. 

We did this mostly because:
* most of the validation is too complex to be handled in OpenAPI schema
* it's easier to test our webhook code with simple unit tests vs. OpenAPI validation with envtest 

This has the following downsides:
* our OpenAPI schema is less expressive, so users and tools can't validate field values based on our CRD schema

I think we need a clear policy going forward about where and how the validation should be done.

### Additional context

* [Kubernetes 1.25: CustomResourceDefinition Validation Rules Graduate to Beta](https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/): with this feature CRD validation became a lot more powerful
  * Disclaimer: CEL in CRDs is a Kubernetes-specific extension. Regular schema validation tools won't be able to run them.  

### Options

I see at least the following options:
1. All validation should be done in webhooks
  * with only very few exceptions like: optional/required, maybe enum
2. Single field validation should be done as much as possible in OpenAPI, everything else in webhooks
  * single field validation is validation which only validates a single field individually (e.g. min length, regex, ...) independent of values of other fields
3. Validation should be done as much as possible in OpenAPI, everything else in webhooks
  * This includes all validation of 2. plus validation which validates multiple fields together (if field A then field B, field A > field B ...)

### My opinion

I personally think 1. is the best option because:
* "OpenAPI schema is not a programming language" (easier to program validation in Go + easier to test)
* OpenAPI validation will always be incomplete, instead of relying on incomplete validation, tools should leverage dry-run to get the "full" validation from our webhooks

/kind documentation

**Comment by sbueringer** [comment]
cc @CecileRobertMichon @enxebre @fabriziopandini @vincepri 

cc @killianmuldoon @JoelSpeed

**Comment by killianmuldoon** [comment]
Related discussion at https://github.com/kubernetes-sigs/cluster-api/issues/6398 (Maybe should be closed in favor of this one?)

**Comment by sbueringer** [comment]
Hm damn. Forgot we had the other issue. I'll re-read the whole thing when I get to it

**Comment by JoelSpeed** [comment]
> "OpenAPI schema is not a programming language" (easier to program validation in Go + easier to test)

The testing side of this could use some expansion IMO. In other projects I work on we have managed to leverage envtest effectively to test validations of the OpenAPI schemas from a user perspective (ie from the YAML representation). We have also used it to test the validations from a Go perspective (because Go serialisation also matters). Yes with the webhooks we can write unit tests for the webhook code, but as this project already uses a lot of envtest for integration tests, I don't see the testing as a blocker for using openapi validations.

> OpenAPI validation will always be incomplete, instead of relying on incomplete validation, tools should leverage dry-run to get the "full" validation from our webhooks

Some examples here would be helpful, what validations are we making today that cannot be achieved using CEL now that it's been introduced.

A really good example of where CEL is a clear winner is in the case of a discriminated union. There's a KEP for implementing validation for this for CRDs but that's no implemented yet, in the mean time, the validation of a large discriminated union in Go is ugly (I've tried!), but in CEL, you need [one ternary per member field](https://github.com/openshift/api/blob/0dea1780a59946e3c5dfc1c5fabae949eceb221d/example/v1/types_stable.go#L84-L101) and you're away. The example I've linked is at the struct level because it validates multiple fields within the struct, so this shows how option 3 might look I guess

**Comment by fabriziopandini** [comment]
/triage accepted
@sbueringer when you have some time please check if we can dedup

**Comment by sbueringer** [comment]
It's on my list

**Comment by fabriziopandini** [comment]
closing in favour of https://github.com/kubernetes-sigs/cluster-api/issues/6398 which have much more discussions on the same topic
/close
