### ISSUE TITLE
How to delete cert-manager with "clusterctl delete" command

### ISSUE THREAD

**Issue by wpeng102** [kubernetes-sigs/cluster-api#7693]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1) 'clusterctl init -i metal3'  will deploy cert-manager component.
2) 'clusterctl delete -i metal3' or 'clusterclt delete --all' does not delete the  cert-manager component.

**Comment by fabriziopandini** [comment]
/triage accepted
/kind feature
/area clusterctl

That's an interesting discussion to have.
Originally it was decided to not delete cert-manager, because it might be used by other services in the cluster different than Cluster API itself; this is still true, but we now have a sort of a signal about if clusterctl owns cert-manager or not, so we can eventually make it possible to delete it  (TBD if opt-in or changing the default behavior, but in this case it will be a breaking change)

**Comment by sbueringer** [comment]
If we implement this, I would prefer doing it as an opt-in. I think the potential fallout of deleting cert-manager and all its CRs is to problematic for it to be default.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

The issue is not updated since 2022, and as far as I know no one else are expressing the same need.
/close
