### ISSUE TITLE
update `test/e2e/data/infrastructure-docker/README.md` with more details on test files setup

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api#7699]
**Detailed Description**

Update the readme with more details on :
- Why we need multiple version folders under a particular contract version, ex: `v1beta1`. 
- How these files should be maintained
- When a folder can be dropped.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind documentation
/area testing

**Comment by fabriziopandini** [comment]
/triage accepted
Thanks for opening the issue
@sbueringer @killianmuldoon who might have historical context on this

**Comment by sbueringer** [comment]
> 1. Why we need multiple version folders under a particular contract version, ex: v1beta1.

Text in the README:

> The templates in [v1alpha3](./v1alpha3), [v1alpha4](./v1alpha4) and [v1.2](./v1beta1/v1.2) are used for 
clusterctl upgrade tests. In those tests we first deploy an old version of Cluster API and then upgrade 
to the version from the current branch. **We can't use the same templates for `v1.2` and `main` as not all 
fields we use in `main` already existed in `v1.2`**.

> 2. When a folder can be dropped.

Text in the README:

> Note: The `v1.2` folder can be deleted once we start developing on v1.4.x. Depending on if we introduce and 
use new fields in v1.4.x we might have to introduce a `v1.3` folder then.

But we can expand on this, in my opinion we can drop a folder when we don't run the tests using it anymore. (and we can explain when we stop running the tests).

> 3. How these files should be maintained

Not sure what that is asking for specifically. In the past we usually modified those files when we needed to when changing test behavior. Otherwise afaik there is no reason to modify them.

**Comment by sbueringer** [comment]
I'll take this task. I saw that we added a v1.3 folder. I think we don't need that.

/assign
