### ISSUE TITLE
CI Failure: capi-e2e-release-1-0-1-22-1-23 is failing

### ISSUE THREAD

**Issue by aniruddha2000** [kubernetes-sigs/cluster-api#7811]
##### Error text:
```
 When upgrading a workload cluster and testing K8S conformance [Conformance] [K8s-Upgrade]
/home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/cluster_upgrade_test.go:25
  Should create and upgrade a workload cluster and run kubetest [It]
  /home/prow/go/src/sigs.k8s.io/cluster-api/test/e2e/cluster_upgrade.go:86
  Timed out after 1200.003s.
  Expected
      <bool>: false
  to be true
  /home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/daemonset_helpers.go:51 

```

### Similar Error
There is a similar failure on [capi-e2e-release-0-4-1-22-1-23](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-0.4#capi-e2e-release-0-4-1-22-1-23) ([1606673372098334720](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-22-1-23-release-0-4/1606673372098334720))

/kind failing-test

cc @kubernetes-sigs/cluster-api-release-team

**Comment by fabriziopandini** [comment]
/triage accepted

@sbueringer @chrischdi we should talk about dropping tests for releases out of support, what we are triaging is mostly failure in the surrounding environment (in this case registry I guess), not actual CAPI issues

**Comment by furkatgofurov7** [comment]
> @sbueringer @chrischdi we should talk about dropping tests for releases out of support, what we are triaging is mostly failure in the surrounding environment (in this case registry I guess), not actual CAPI issues

We had some discussions with @sbueringer  and @ykakarap, overall +1 to drop the tests for out-of-support releases.

**Comment by sbueringer** [comment]
Yup. Let's ignore this test failure (and the other one on v0.4) for now until we decided if we want to keep those tests.

**Comment by sbueringer** [comment]
Looked a bit into the test logs and code.

Based on the research done in https://github.com/kubernetes-sigs/cluster-api/issues/7833 I would conclude:
* capi-e2e-release-1-0-1-22-1-23 is failing because
  * the new kubeadm binaries are using `registry.k8s.io`, which means the kube-proxy DaemonSet is using `registry.k8s.io`
  * Everything works but our test fails as our test code is hard-coded checking for `k8s.gcr.io/...` ([link](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.0/test/framework/daemonset_helpers.go#L47-L50))
  * This was adjusted in later Cluster API versions were we support the new registry but not on older unsupported branches
* capi-e2e-release-0-4-1-22-1-23 is failing for the same reason
* The 1.22 => 1.23 upgrade is the one that is using the newest Kubernetes versions, which is why we don't have any failures for v1.23 => v1.24 in v0.4 and v1.0
* The tests with older versions (e.g. capi-e2e-release-1-0-1-21-1-22) are not failing because the v1.21 kubeadm binary is still using the `k8s.gcr.io` registry and during kubeadm join with the v1.22 binary the DaemonSet is not modified


So overall not a problematic issue in Cluster API itself it's just that our test code doesn't support the new registry.

So let's keep this issue on hold until we decided that we want to drop the old tests. I think this issue is a good indication that we shouldn't keep tests for unsupported versions running forever :)

cc @fabriziopandini

**Comment by sbueringer** [comment]
@furkatgofurov7 There are no guidelines yet. I would just bring it up in the office hours to be honest. We wanted to talk to some folks which are just now back from PTO before doing that however.

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 There are no guidelines yet. I would just bring it up in the office hours to be honest. We wanted to talk to some folks which are just now back from PTO before doing that however (we = Fabrizio & I).

Makes sense, no rush and hopefully we can have some guidelines around it (I was thinking of something similar to what we have for [Support and guarantees](https://cluster-api.sigs.k8s.io/contributing#support-and-guarantees)) to be documented so it is easier for everyone when  and how we can drop the tests in the future 🙂

**Comment by sbueringer** [comment]
@furkatgofurov7 Opened the issue here: https://github.com/kubernetes-sigs/cluster-api/issues/8039
Will bring it up in the office hours today

**Comment by sbueringer** [comment]
Jobs have been removed

/close
