### ISSUE TITLE
Add more info in Machine Status 

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#7887]
**User Story**

As a [developer/user/operator] I would like to see a more detailed status of the machine when draining and performing operations on the provider machine. During draining it should show which PODs are the controllers waiting to be evicted. And whenever any task is being performed on the provider machine, for example in the draining process when the provider machine is being deleted it should reflect that in the status that the provider machine is deleting instead of just showing deleting. This information is already available it needs to be presented in the status field as well.

**Detailed Description**

When a node is draining, the machine status should show the list of pods that are waiting to be evicted. Once pods are evicted draining status goes back to empty. It can be presented like this in Status.

```
Draining Status:
    Pods:
       Pod: pod-name1
       Status: WaitingToBeEvicted
       Pod: pod-name2
       Status: Evicted
```
Also, add another status we can name it "Operational Status" which will show the operation happening on the provider machines.
It will help in automation and ease of use as well. Automation tools cannot extract from pod logs what is failing/hanging and for how long. Draining sometimes takes hours and the machine status has no indication of what is going on or what is it waiting for.

/kind feature

**Comment by fabriziopandini** [comment]
/triage needs-information
I'm a little bit debated on this feature request (see below); it will be interesting to hear others' opinions.

On one side I like the idea of improving observability, from the other side I'm not sure we should surface the detailed list of pods (might be a counter could be enough, also what about volumes or other items, what about showing new info also when we are not deleting), I need to think about this thought. 

It would also be great to get some more details on what you mean with "Operational Status" showing the operation happening on the provider machines because being CAPI agnostic to providers this could be tricky (and also we already have conditions that serve to a similar goal).

self-notes: 
- the drainer gives us the list of deleted/evited pods; to get the list of pods yet to be evicted is required to query the workload cluster for pods (AFAIK that info is not available on node detail)

**Comment by sbueringer** [comment]
> This information is already available it needs to be presented in the status field as well.

Agree with Fabrizio. I think we don't have the information at the moment. We are using the drainHelper from k/k and it's logging certain information. But that doesn't mean that our code has access to that information. 

We might get more with either using different util funcs in the drain helper or by writing our own drainHelper.

Independent of that, what information exactly would we want to put into the Machine status?

**Comment by adilGhaffarDev** [comment]
> It would also be great to get some more details on what you mean with "Operational Status" showing the operation happening on the provider machines because being CAPI agnostic to providers this could be tricky (and also we already have conditions that serve to a similar goal).

I agree that CAPI is an agnostic provider, we don't want to show anything provider-specific information. We want to show the actions and waits performed by CAPI like draining status and waiting for provider machine deletion.



> Agree with Fabrizio. I think we don't have the information at the moment. We are using the drainHelper from k/k and it's logging certain information. But that doesn't mean that our code has access to that information.
> 
> We might get more with either using different util funcs in the drain helper or by writing our own drainHelper.

Understandable, so if we want to do that we will modify the OnPodDeletedOrEvicted callback(https://github.com/kubernetes-sigs/cluster-api/blob/9dc69be55dfec51c58838645a89075f379e1fc1f/internal/controllers/machine/machine_controller.go#L609) and add more functionality there?  We can check which pods are evicted and which are still remaining by querying, and then we can show this info in the machine Status. I might be missing something, correct me if I am wrong.

**Comment by fabriziopandini** [comment]
Sorry, I wasn't clear when writing my self-notes, but I think that the fact that drainer gives back only the list of deleted/evited pods and not the list of the remaining pods could be a potential blocker because it can lead to scalability issues.

But that wasn't my key point because I'm not sure we should surface the detailed list of pods in machine status. If you think about this, even the node doesn't surface this level of detail in its own API... 

But I'm also still trying to understand the other point about "Operational Status" and why conditions are not enough for this goal. We have PreDrainDeleteHookSucceededCondition, DrainingSucceededCondition, VolumeDetachSucceededCondition, PreTerminateDeleteHookSucceededCondition, and InfrastructureReadyCondition, what is missing/what can be improved there? If we can identify something actionable in this part this can be probably easier to achieve and a first step in the right direction

**Comment by adilGhaffarDev** [comment]
> Sorry, I wasn't clear when writing my self-notes, but I think that the fact that drainer gives back only the list of deleted/evited pods and not the list of the remaining pods could be a potential blocker because it can lead to scalability issues.
> 
> But that wasn't my key point because I'm not sure we should surface the detailed list of pods in machine status. If you think about this, even the node doesn't surface this level of detail in its own API

I understand that the drainer does not give that information, we need to change the drainer or implement it on the CAPI side. And I also agree that showing a list of pods going to be too much information. I would like to explain what we want to solve, sometimes while draining, if the pod or volume is stuck during the eviction, there is not much information on the status of the machine and why it is stuck at deleting. In controller logs that can be checked, but it would be much easier for the user to see which pod or volume is stuck in the status of the machine. Any suggestion on what information we can show regarding eviction in the status of the machine? 


> But I'm also still trying to understand the other point about "Operational Status" and why conditions are not enough for this goal. We have PreDrainDeleteHookSucceededCondition, DrainingSucceededCondition, VolumeDetachSucceededCondition, PreTerminateDeleteHookSucceededCondition, and InfrastructureReadyCondition, what is missing/what can be improved here? If we can identify something actionable in this part this can be probably easier to achieve and a first step in the right direction

I agree conditions are ok and they serve their purpose, but as explained above they don't give the full picture if some pod or volume is stuck in the eviction process. The purpose of "Operational Status" (we can name it something else too, maybe just draining status) was to show what task is being performed right now e.g, "evicting pod pod-name..", so if it gets stuck user knows on which step it is getting stuck.

**Comment by adilGhaffarDev** [comment]
@fabriziopandini kindly check this when you get time.

**Comment by fabriziopandini** [comment]
I'm leaning toward closing this issue and reconsidering when the drainer will provide more information about the ongoing process. When that information will be available we can try to surface them using conditions or additional status field.

**Comment by adilGhaffarDev** [comment]
Yes, we can close this one, I opened an issue for improvement of the drainer so it can provide more information (https://github.com/kubernetes/kubernetes/issues/116210). If they accept my suggestions and I am able to get it done, we can reopen a discussion in CAPI.
