### ISSUE TITLE
Add nameservers to IPAM integration proposal

### ISSUE THREAD

**Issue by flawedmatrix** [kubernetes-sigs/cluster-api#7909]
**User Story**

As a cluster operator I want to configure my IPAM Provider with nameservers that will automatically be used by any machine that claims IP addresses from my pool.

**Detailed Description**

Currently, the IPAM integration allows configuration of IP addresses without the use of DHCP. However, because DHCP also configures nameservers, DNS must be manually configured on machines that use IPAM.

We'd like to add an enhancement to the IPAM integration proposal to also allow configuration of DNS along with IP Addresses to remove the need for DHCP or manual configuration of nameservers.

We have a draft of some proposed changes here:
https://github.com/flawedmatrix/cluster-api/commit/a19bf76efd60080ba40bf8cfe1606cabd60c6678

/kind feature

**Comment by flawedmatrix** [comment]
@schrej I'd greatly appreciate your feedback on these changes.

cc @christianang @tylerschultz @adobley

**Comment by schrej** [comment]
I've thought about it when I started with the proposal, since metal3's IPAM also has DNS fields. I then decided against including DNS in the IPAddress object since it's not something that is machine specific, and therefore doesn't require the IPAM contract. It's also not as network-specific as the Gateway (which can be different for individual machines as well). So I came to the conclusion that it should be fine if DNS needs to be set as part of the MachineTemplate.

But if there is demand for it, I have nothing against adding a DNS field for convenience, as it does make it a little easier when different networks use different DNS servers.

Another argument against a DNS field was that it causes a lot of duplicate information, as the DNS servers are very likely to be the same for all nodes in a cluster (in contrast to the networks and gateways). But thinking about it further, if a cluster is geologically distributed (e.g. individual nodes on the edge), DNS servers could also vary between nodes, turning this into an argument in favour of adding the field.

**Comment by sbueringer** [comment]
cc @randomvariable @yastij

**Comment by flawedmatrix** [comment]
Yeah I can see the argument that DNS might not conceptually belong with IPAM, but I think I'm leaning heavily toward allowing DNS nameservers to be provided since DHCP has provided this information before.

I definitely agree that if we add the field it should be optional.

**Comment by sbueringer** [comment]
I think if we add the field (even as optional) we should have the feeling that it somewhat belongs there.

Adding fields to an API just because that API is a convenient place to communicate that information shouldn't be enough.


That being said, I'm personally still not sure if it fits "well enough". It just feels a bit off to have an IPAddress CRD which repreents and IP address and then it has a namserver (which seems orthogonal to me, but maybe it isn't as orthogonal as I think)

**Comment by sbueringer** [comment]
Question: Where is the value for the DNS server coming from? Would that be something that a user has to provide on some IPPool resource so the IPAM implementation can then set it on an IPAddress?

I would really rather expect that DNS server is something that I can configure either on the Machine or Cluster level.

**Comment by schrej** [comment]
The DNS server _can_ depend on the network in use. When using some external IPAM/DNS solution (e.g. Infoblox), it can be more convenient when that tool can also control which DNS server will be used.

In addition it makes it easier when using a lot of different networks. But this is basically just convenience.

For the in-cluster provider it would require setting the DNS servers on the pool resource though.

> I would really rather expect that DNS server is something that I can configure either on the Machine or Cluster level.

That's how it works now.

**Comment by randomvariable** [comment]
I think what you're looking for is some way to express common settings for a cluster within a namespace. It feels kind of wrong to shoehorn it into the IPAM controller to me, and rather instead pursue a Cluster Runtime Extension that can reference your own opionated config object and inject them into clusters, removing the toil of "having to know network stuff" for cluster consumers.

**Comment by lubronzhan** [comment]
>P.S. It would fit better if the CRD is called NetworkConfig or something
Yeah I agree it would be good to have some different CRD of it instead of injecting it to IPAM.

**Comment by christianang** [comment]
> I think what you're looking for is some way to express common settings for a cluster within a namespace. It feels kind of wrong to shoehorn it into the IPAM controller to me, and rather instead pursue a Cluster Runtime Extension that can reference your own opionated config object and inject them into clusters, removing the toil of "having to know network stuff" for cluster consumers.

I'd be interested in you expanding what this looks like. I will say that you can already set the nameservers on the Cluster machines right now, so if this is just about setting nameservers on clusters we can do that now.

I think I can agree that perhaps dns configuration should go onto a different CRD if it feels like we are shoehorning it onto IPAddress, but I think the IPAMProvider still should be the provider of DNS information. If this were to explode into a brand new orthogonal API for this singular field that seems less valuable to me i.e it seems like effort to value ratio would be too high to create a new controller and api for a single bit of info.

So I'm interested in hearing opinions if feels wrong to have it on the IPAddress CRD or on the IPAM API in general.

**Comment by flawedmatrix** [comment]
Closing due to lack of interest in implementing this proposal
