### ISSUE TITLE
Runtime-SDK upgrade test is flaky

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8486]
### Which jobs are flaking?

capi-e2e

### Which tests are flaking?

When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster

### Since when has it been flaking?

Months

### Reason for failure (if possible)

The message is:

```
hook BeforeClusterUpgrade call not recorded in configMap k8s-upgrade-with-runtimesdk-fdmsth/k8s-upgrade-with-runtimesdk-va0zcw-test-extension-hookresponses
```

In my limited testing so far I've found that the hook is being logged by the runtimeExtension - so there may be some issue in reading and writing the configmap.

### Label(s) to be applied

/kind flake
/area testing

**Comment by chrischdi** [comment]
For better triaging: do you think it makes sense to also fetch the configmaps and secrets of a namespace to the artifacts?

**Comment by killianmuldoon** [comment]
>For better triaging: do you think it makes sense to also fetch the configmaps and secrets of a namespace to the artifacts?

Yeah - I think the first step here is better logging (of the entire configmap at different points IMO) and retrieving the configmap. There's not enough info to really reproduce this locally, so hopefully those steps will help.

**Comment by chrischdi** [comment]
Link to find failed jobs: https://storage.googleapis.com/k8s-triage/index.html?text=BeforeClusterUpgrade&job=.*-cluster-api-.*&xjob=.*-provider-.*

**Comment by killianmuldoon** [comment]
Ohh - good idea. Maybe we should add this to the template for flaky jobs. Way more useful than just a single link to testgrid IMO

**Comment by chrischdi** [comment]
I'll try to reproduce this :-)

/assign

**Comment by chrischdi** [comment]
After reproduction: further tirage via the failures in [k8s-triage](https://storage.googleapis.com/k8s-triage/index.html?text=BeforeClusterUpgrade&job=.*-cluster-api-.*&xjob=.*-provider-.*):

* [13/04/2023, 08:11:35](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1646395113494024192) periodic-cluster-api-e2e-main capi-e2e [It] When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster
* [12/04/2023, 02:46:08](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-release-1-4/1645950790356963328) periodic-cluster-api-e2e-release-1-4 capi-e2e [It] When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster
* [11/04/2023, 22:04:08](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1645879822049611776) periodic-cluster-api-e2e-main capi-e2e [It] When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster
* [09/04/2023, 13:43:24](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1645029066757115904) periodic-cluster-api-e2e-main capi-e2e [It] When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster
* [09/04/2023, 11:43:21](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1644998867730567168) periodic-cluster-api-e2e-main capi-e2e [It] When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster

The first thing to take a look at for this issue seems to be the Cluster's status.

This groups these occurencies in 3 different groups:

* 3x `TopologyReconcileFailed` with `handler with name "generate-patches.k8s-upgrade-with-runtimesdk" has not been registered`
* 1x A case which looks okay from Cluster.Status perspective
* 1x `ControlPlaneUpgradePending` with `MachineDeployment(s) k8s-upgrade-with-runtimesdk-ij5bru-md-0-xg8mf are rolling out`

So further analysis for now for the `TopologyReconcileFailed`

# TopologyReconcileFailed

via [13/04/2023, 08:11:35](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1646395113494024192):

* The [failed condition](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1646395113494024192/artifacts/clusters/bootstrap/resources/k8s-upgrade-with-runtimesdk-zy9k0f/Cluster/k8s-upgrade-with-runtimesdk-q4ez7q.yaml) is from `lastTransitionTime: "2023-04-13T07:05:44Z"`
* [ExtensionConfig CR](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1646395113494024192/artifacts/clusters/bootstrap/resources/ExtensionConfig/k8s-upgrade-with-runtimesdk.yaml) is Discovered on `lastTransitionTime: "2023-04-13T07:01:36Z"`
* So from discovery perspective this seems to be okay
* The extension also [logs the topology](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1646395113494024192/artifacts/clusters/bootstrap/logs/test-extension-system/test-extension-manager/test-extension-manager-68dbd7544d-6x4wt/manager.log) mutate calls, but not any new ones after the `lastTransitionTime`.

CAPI-Manager logs provide the same information as the condition.

Next possible steps:
* try to reproduce locally and take a look into the capi manager via debugger
* dump more information about the state of the test extension (is it up and running?!)

To be continued...

**Comment by chrischdi** [comment]
Triage link: [5706ce82b01181bc509b](https://go.k8s.io/triage#5706ce82b01181bc509b)

(testing the search)

**Comment by chrischdi** [comment]
Currently it seems not possible to reproduce it locally.

**Comment by chrischdi** [comment]
So after today's session we identified that:

* We may start the upgrade, while there still are Machines which did not yet get ready
  * https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/cluster_upgrade_runtimesdk.go#L182
* This results in the `BeforeClusterUpgrade` hook not even getting called, because the CAPI code first checks if there is a rollout happening
  * https://github.com/chrischdi/cluster-api/blob/d9c4972d9900faf9ece3eaa03fb6b7dadc2523c4/internal/controllers/topology/cluster/desired_state.go#L430
  
Plan:
* We want to add a `PostMachinesProvisioned` variable/func to the [ApplyClusterTemplateAndWait](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/cluster_upgrade_runtimesdk.go#L152)
  * this should check if we are still rolling out things (e.g. MD)
* Also: we could try to further dig into this issue to see the real cause of taking longer than expected. This could e.g. be done by reusing the WIP MR #8486 .


Note: I'll try to add the  `PostMachinesProvisioned` thingy beginning mid next week.

**Comment by killianmuldoon** [comment]
![image](https://github.com/kubernetes-sigs/cluster-api/assets/47175296/b93afec3-05f1-4f93-b577-b6a3528c4fc4)
Here's the frequency of the flake as of this morning. Let's see how it compares in a ~week or so.

**Comment by chrischdi** [comment]
Looks like the fix works out great:

![image](https://github.com/kubernetes-sigs/cluster-api/assets/417870/af43b92a-058c-4c8a-a650-a3f6876662d1)

(the failure on 5/12 was before merging).

https://storage.googleapis.com/k8s-triage/index.html?date=2023-05-21&text=BeforeClusterUpgrade&job=.*-cluster-api-.*&xjob=.*-provider-.*

**Comment by chrischdi** [comment]
@killianmuldoon should we close this one?

**Comment by killianmuldoon** [comment]
>@killianmuldoon should we close this one?

Yup thanks for fixing this - CI is looking a lot better now :slightly_smiling_face: 

/close
