### ISSUE TITLE
Support other docker versions and other container runtimes

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes-sigs/cluster-api#86]
_From @rsdcastro on March 3, 2018 20:17_

Currently only docker 1.12 is supported. This issue is to track defining supported runtimes and having those implemented in the cluster API. This can be scoped this to a specific OS flavor (Debian-based OSs) which is currently supported.

https://github.com/kubernetes/kube-deploy/blob/dfcdb553268d9f9ffcf0cdb23205bd7063ddf4a8/cluster-api-gcp/cloud/google/machineactuator.go#L644

_Copied from original issue: kubernetes/kube-deploy#634_

**Comment by rsdcastro** [comment]
_From @roberthbailey on March 7, 2018 18:50_

Supporting only docker seems ok for the alpha release. Supporting multiple versions declaratively would be nice, but given the trend of having the version of docker installed by mechanisms on the host OS (e.g. ubuntu comes with it's version of docker and COS comes with it's version) I'm not sure how strongly I care about adding support for this for alpha.

**Comment by rsdcastro** [comment]
/assign @roberthbailey 

Please update this issue with current thoughts on container runtimes.

**Comment by kfox1111** [comment]
cri-o + kata-containers is interesting.

**Comment by roberthbailey** [comment]
After talking with @thockin last week it became apparent that container runtime should not be an "input variable" in the cluster API (e.g. a field that you can set and expect a controller to reconcile). Many base OSes are beginning to bundle a container runtime, and for folks that care about setting a specific one they can choose the proper host OS to get the container runtime that they care about. 

In the interest of keeping the API surface as narrow as possible, I'm proposing that we remove this field. If we find that it is necessary in the future, we can add it back but we won't be able to remove it once our API surface stabilizes. 

I'll add this topic to the breakout meeting agenda for tomorrow and send a PR to remove the fields if there is consensus.

**Comment by kfox1111** [comment]
I was going to comment, that there may be multiple runtime versions when cri-o + kata-containers is involved and that the field for runtime is a singleton I think? So there is that reason to maybe pull back from specifying it for now, so that part of the api can be thought through a little more. It maybe at minimum should be a list. But dropping it all together for now would be easier. It being in the api though long term still would be useful for dealing with upgrades?

**Comment by roberthbailey** [comment]
If the container runtime is coupled to the OS version than updating the OS would update the container runtime too. Maybe that's not fined grained enough in the limit but for now I think it's reasonable.

**Comment by kfox1111** [comment]
One other thought. Not sure it is relevant at all or not, as I haven't looked at the api too closely. What about allowing the specification of repos instead of runtimes?

I currently use cobbler to sync particular repo sets down and update each host to point to a particular saved set of repos/updates. Then I know when I do a yum upgrade that the upgrade will be uniform. Either a node will get no updates as it was pointing to the old repo, or it will get just the exact updates I want/tested as it is pointing at the new repo. In a way, I'm treating the repo (or repo set) as an image.

**Comment by roberthbailey** [comment]
That's definitely something that you could easily support in the `providerConfig` but I don't think it's something we'd want to promote to the top level API unless it was common behavior across many providers.
