### ISSUE TITLE
Test failing with "old version instances remain" for machinepools in Runtime SDK test

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#8718]
### Which jobs are flaking?

Over the period of [last 14 days](https://storage.googleapis.com/k8s-triage/index.html?date=2023-05-22&job=.*-cluster-api-.*&xjob=.*-provider-.*#be5d8d6e6e9e3ae69ce4):

* 8x `periodic-cluster-api-e2e-release-1-4`
* 6x `periodic-cluster-api-e2e-main`
* 4x `periodic-cluster-api-e2e-mink8s-release-1-4`
* 4x `periodic-cluster-api-e2e-mink8s-main`
* 2x `periodic-cluster-api-e2e-dualstack-ipv6-main`
* 1x `periodic-cluster-api-e2e-workload-upgrade-1-21-1-22-release-1-4`
* 1x `periodic-cluster-api-e2e-workload-upgrade-1-26-1-27-release-1-4`

### Which tests are flaking?

Over the period of [last 14 days](https://storage.googleapis.com/k8s-triage/index.html?date=2023-05-22&job=.*-cluster-api-.*&xjob=.*-provider-.*#be5d8d6e6e9e3ae69ce4):

* 24x `capi-e2e [It] When upgrading a workload cluster using ClusterClass with RuntimeSDK [PR-Informing] [ClusterClass] Should create, upgrade and delete a workload cluster`
* 2x `capi-e2e [It] When upgrading a workload cluster using ClusterClass and testing K8S conformance [Conformance] [K8s-Upgrade] [ClusterClass] Should create and upgrade a workload cluster and eventually run kubetest`

### Since when has it been flaking?

Looks to be already longer than [since the beginning of year 2023](https://storage.googleapis.com/k8s-triage/index.html?date=2023-01-01&text=waiting%20for%20all%20MachinePool%7Cold%20version%20instances%20remain&job=.*-cluster-api-.*&xjob=.*-provider-.*)

### Reason for failure (if possible)

To be analysed.

### Anything else we need to know?

Link to triage to see if it is fixed: [link](https://storage.googleapis.com/k8s-triage/index.html?text=waiting%20for%20all%20MachinePool%7Cold%20version%20instances%20remain&job=.*-cluster-api-.*&xjob=.*-provider-.*)

### Label(s) to be applied

/kind flake

**Comment by killianmuldoon** [comment]
There have been a couple of changes in the MachinePool controller as of late - I wonder if any of those made an upgrade take longer and increased the occurrence of this flake.

**Comment by chrischdi** [comment]
As stated above, the issue seems to already exist since > 5 months. So must be non-recent changes. (in the triage link above you can go back in time :-) )

**Comment by killianmuldoon** [comment]
This is looking good over the last couple of days and backported to 1.3 / 1.4 today. Let's see how it performs over the weekend.

One outstanding issue that we have is in our 0.4 and 1.0 upgrade tests (also in 1.2 but that's due to be removed soon). We still get this flake on those tests as (obviously) we haven't backported this fix. Let's see how often those flakes occur but possibly discuss introducing a fix like this if they're disruptive to the signal.

I think this probably isn't much of a problem as the 0.4 and 1.2 upgrade tests will be removed soon - both during the next release cycle so August or September. That would leave just the 1.0 job suffering from this issue, but that job will probably stick around for a long time to ensure API compatibility.

**Comment by killianmuldoon** [comment]
Looking good :slightly_smiling_face: 

/close
