### ISSUE TITLE
Test flaking with Timed out waiting for 1 nodes to be created for MachineDeployment

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes-sigs/cluster-api#8786]
### Which jobs are flaking?

e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1665614080297144320

### Which tests are flaking?

periodic-cluster-api-e2e-main
periodic-cluster-api-e2e-ipv6-main
periodic-cluster-api-e2e-dualstack-ipv6-main
periodic-cluster-api-e2e-dualstack-ipv6-main
periodic-cluster-api-e2e-ipv6-main

All failing at Should create a workload cluster

### Since when has it been flaking?

01-06-2023
https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#295d4f44852a6339ba54

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main

### Reason for failure (if possible)

To be analyzed.

### Label(s) to be applied

/kind flake

**Comment by killianmuldoon** [comment]
/triage accepted

Thanks for opening this @adilGhaffarDev!

**Comment by killianmuldoon** [comment]
@ykakarap  - you might be able to help out on this one. Could it possibly be related to changes in the MachineSet controller? It appears to be recently introduced.

**Comment by sbueringer** [comment]
Please add a link to the concrete job instance that failed under "Which jobs are flaking?".

**Comment by ykakarap** [comment]
I will take a look.

**Comment by ykakarap** [comment]
Initial analysis for the failure:
* MachineDeployment fails to get all the worker nodes because MachineSet is not scaling up
* MachineSet is not scaling up because it is waiting for the ControlPlane to finish provisioning (`ControlPlaneIsStable` preflight)
* ControlPlane is not considered provisioned by the MachineSet even though in reality it is provisioned because the KCP controller fails to update the KCP object's status (MS looks at KCP status to determine if the CP is provisioned)
* KCP status update fails because it failed while [creating a remote cluster client](https://github.com/ykakarap/cluster-api/blob/60b1426955b1b832467eb6dd2fffacb5a8d1d972/controlplane/kubeadm/internal/controllers/status.go#L98) (KCP needs it to calculate readyReplicas)
* Creating remote cluster client fails because the client is being rate-limited (this part of the code goes into controller-runtime).
   * Relevant log message from KCP logs:
```
failed to create remote cluster client: failed to create cluster accessor: error adding index for field "spec.providerID" to cache for remote cluster "quick-start-yafvln/quick-start-9qh7w5": failed to get API group resources: unable to retrieve the complete list of server APIs: v1: client rate limiter Wait returned an error: context deadline exceeded - error from a previous attempt: EOF
```

So I would say the problem is not actually the preflight checks but something different but the preflight checks now surfaced this problem. Of course the problem still needs to be fixed.


@sbueringer Any recommendations on how to address the rate-limiting issue?

**Comment by sbueringer** [comment]
I'm not sure if the problem is the rate limiter or the late limiter just reports the error it had a few seconds before which seems to be : "error from a previous attempt: EOF". How is the requeue behavior of that error case?

**Comment by sbueringer** [comment]
In my opinion the issue is the following:
* The worker machine is not created because CP is not stable (preflight check blocks)
* The CP is not stable because KCP.status.version is not set
* KCP.status.version is not set because there is no Machine with  APIServerPodHealthy = true

There are two possible root causes:
1. apiserver never gets ready
2. apiserver gets ready but KCP doesn't see it because it doesn't reconcile after the apiserver got ready

I'll open a PR to also dump kube-system Pods at the end of tests. This should help us to figure out if it's 1. or 2.

Independent of that the ClusterCacheTracker log is not ideal, but I think it's not our issue here.

Some data:
Job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1665917119549673472

KCP logs:
![image](https://github.com/kubernetes-sigs/cluster-api/assets/4662360/82ce043e-6b1a-4096-99a9-a61f59102f19)

The apiserver pod starts up around 03:14:19 ([link](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1665917119549673472/artifacts/clusters/clusterctl-upgrade-ylqn0d/machines/clusterctl-upgrade-ylqn0d-6bprc-57pv4/pods/kube-system_kube-apiserver-clusterctl-upgrade-ylqn0d-6bprc-57pv4_58ec6b990e8f2f4999e90955a9ecc500/kube-apiserver/0.log))

So it could be that the Pod gets ready after KCP did its last reconcile before deletion at 2023-06-06T05:13:50.925+02:00

**Comment by sbueringer** [comment]
We had a new occurence now.

Following results:
* Job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1666583266548781056
* kube-apiserver pod is ready since 2023-06-08T00:14:41Z (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1666583266548781056/artifacts/clusters/clusterclass-changes-qgapy7/resources/kube-system/Pod/kube-apiserver-clusterclass-changes-qgapy7-czmt7-kv8ms.yaml)
* The KCP Machine still shows APIServerPodHealthy=false (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1666583266548781056/artifacts/clusters/bootstrap/resources/clusterclass-changes-6rkonn/Machine/clusterclass-changes-qgapy7-czmt7-kv8ms.yaml)
* Based on logs the KCP object was reconciled after the apiserver Pod became ready:
  * original_ts=2023-06-08T02:14:48.714+02:00 msg=Reconcile KubeadmControlPlane
  * original_ts=2023-06-08T02:14:49.043+02:00 msg=Reconcile KubeadmControlPlane
  * original_ts=2023-06-08T02:14:51.53+02:00 msg=Reconcile KubeadmControlPlane
* The Pod object is not cached in KCP, so:
  * KCP should have seen that the apiserver pod is ready
  * then flagged APIServerPodHealthy as true on the Machine
  * and then eventually it should have written KCP.status.version
  * This then would unblock the MS preflight check and thus the Machine creation

It's unclear to me at this point why KCP didn't see that the apiserver Pod was ready.

I think we can further triage this by collecting more data, e.g. by adding logs to KCP to surface the Pod object it is seeing.

A potential solution would be to requeue more often in KCP if KCP is not entirely healthy, but it would be good to first figure out what exactly is going on first. 


@adilGhaffarDev If you have time to work on this, feel free to go ahead. I unfortunately won't have time to work on this the next few weeks.

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev If you have time to work on this, feel free to go ahead. I unfortunately won't have time to work on this the next few weeks.

Yes I can take a look.

**Comment by sbueringer** [comment]
@adilGhaffarDev Did you have time to investigate the issue?

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev Did you have time to investigate the issue?

Sorry I didn't get time to look into it. I will not be able to work on it  soon as I am on vacations right now. If someone has time please check it.

**Comment by chrischdi** [comment]
> We had a new occurence now.
> 
> Following results:
> 
> * Job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1666583266548781056
> * kube-apiserver pod is ready since 2023-06-08T00:14:41Z (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1666583266548781056/artifacts/clusters/clusterclass-changes-qgapy7/resources/kube-system/Pod/kube-apiserver-clusterclass-changes-qgapy7-czmt7-kv8ms.yaml)
> * The KCP Machine still shows APIServerPodHealthy=false (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1666583266548781056/artifacts/clusters/bootstrap/resources/clusterclass-changes-6rkonn/Machine/clusterclass-changes-qgapy7-czmt7-kv8ms.yaml)
> * Based on logs the KCP object was reconciled after the apiserver Pod became ready:
>   
>   * original_ts=2023-06-08T02:14:48.714+02:00 msg=Reconcile KubeadmControlPlane
>   * original_ts=2023-06-08T02:14:49.043+02:00 msg=Reconcile KubeadmControlPlane
>   * original_ts=2023-06-08T02:14:51.53+02:00 msg=Reconcile KubeadmControlPlane
> * The Pod object is not cached in KCP, so:
>   
>   * KCP should have seen that the apiserver pod is ready
>   * then flagged APIServerPodHealthy as true on the Machine
>   * and then eventually it should have written KCP.status.version
>   * This then would unblock the MS preflight check and thus the Machine creation
> 
> It's unclear to me at this point why KCP didn't see that the apiserver Pod was ready.
> 
> I think we can further triage this by collecting more data, e.g. by adding logs to KCP to surface the Pod object it is seeing.
> 
> A potential solution would be to requeue more often in KCP if KCP is not entirely healthy, but it would be good to first figure out what exactly is going on.
> 
> @adilGhaffarDev If you have time to work on this, feel free to go ahead. I unfortunately won't have time to work on this the next few weeks.

Taking another look at the above:

| Timestamp   | Object             | What                                                | Time Source       |
|-------------|--------------------|-----------------------------------------------------|-------------------|
| `00:14:07Z` | 👷‍♀️ Test         | Test starts waits for ControlPlane Node to exist    | Build Log         |
| `00:14:32Z` | 🛳️ APIServer Pod  | Pod got created                                     | CreationTimestamp |
| `00:14:37Z` | 👷‍♀️ Test         | Test starts waits for ControlPlane Node to be ready | Build Log         |
| `00:14:41Z` | 🛳️ APIServer Pod  | Pod's got ready                                     | Status.Conditions |
| `00:14:48Z` | 🎮 CAPK controller | Entering `reconcile()` for the KCP                  | CAPK logs         |
| `00:14:49Z` | 🎮 CAPK controller | Entering `reconcile()` for the KCP                  | CAPK logs         |
| `02:14:51Z` | 🎮 CAPK controller | Entering `reconcile()` for the KCP                  | CAPK logs         |
| `00:14:52Z` | 🛳️ APIServer Pod  | Pod's status got updated                            | ManagedFields     |
| `00:14:57Z` | 👷‍♀️ Test         | Test waits for workload nodes                       | Build Log         |
| `00:19:57Z` | 👷‍♀️ Test         | Test exits / failed                                 | Build Log         |


From reading the objects again and some trial and error:

* The information that the kube-apiserver pod got ready according `.status.conditions` was patched to the Pod object **after** the last reconcile of CAPK controller.
* At the state of CAPK reconciling the KCP object: it could have a no-op and `return ctrl.Result{}, nil`, while still having `ControlPlaneComponentsUnhealthy ` set to false in `.status.condition`.

The only sources for reconciliations for the KCP object are:
* Changes to the KCP object itself
* Changes to the Cluster object (via watch)
* syncperiod

For this edge case I could see some variants to get to a solution:
* Do a requeue if the `ControlPlaneComponentsUnhealthy` condition is set to false, to ensure it gets reconciled again (similar to what @sbueringer proposed above)
* The direct alternative to this would be a watch on Machines

cc @sbueringer / @killianmuldoon

**Comment by chrischdi** [comment]
We also have a similar case where we already do a requeue:

https://github.com/kubernetes-sigs/cluster-api/blob/ddbf9cf51fb65377c4484423581dffae8f2627dc/controlplane/kubeadm/internal/controllers/controller.go#L225-L232

But in this new case, `kcp.Status.Ready` is true.

I'll go forward and create a PR which would requeue in this new case too.

**Comment by killianmuldoon** [comment]
> The direct alternative to this would be a watch on Machines

The KCP controller also watches Machines AFAIU through the `Owns` function in it's builder. KCP is reconciled in response to changes on Machines. I wonder why this reconcile is being missed in this case :thinking:

**Comment by killianmuldoon** [comment]
> // TODO: remove this as soon as we have a proper remote cluster cache in place. 

Not sure replicating this would be non-controversial - sounds like it shouldn't be needed now that there is a `proper remote cluster cache`

**Comment by chrischdi** [comment]
> > The direct alternative to this would be a watch on Machines
> 
> The KCP controller also watches Machines AFAIU through the `Owns` function in it's builder. KCP is reconciled in response to changes on Machines. I wonder why this reconcile is being missed in this case 🤔

Ah right. The point is not a Machine watch, but a watch to the Pods inside the workload cluster instead.

**Comment by killianmuldoon** [comment]
>The point is not a Machine watch, but a watch to the Pods inside the workload cluster instead.

I don't think this is a good idea - we'd end up caching too many pods. I'm fine with adding something like:

```
 		res = ctrl.Result{RequeueAfter: 20 * time.Second} 
```

But we should comment clearly that it's to avoid a watch on the pods, and maybe reassess the case in https://github.com/kubernetes-sigs/cluster-api/issues/8786#issuecomment-1645445587 to see if it's actually needed anymore and update the comment to reflect the current state.

Thanks for taking a look at this one!

**Comment by chrischdi** [comment]
I totally agree 👍. Created #9032 as proposal to solve this case.

**Comment by sbueringer** [comment]
I think a requeue is probably the less-risky option. We could have a metadata-only watch for Pods. So we wouldn't have a memory problem. But I'm more than just a bit concerned about the amount of Pod events we would get (even if we filter down on only the most important pods) and then the corresponding reconciles.

**Comment by sbueringer** [comment]
/reopen

to wait for confirmation via CI?

**Comment by chrischdi** [comment]
More flexible triage link to confirm later on:

https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20waiting%20for%201%20nodes%20to%20be%20created%20for%20MachineDeployment&job=.*-cluster-api-.*&xjob=.*-provider-.*

**Comment by chrischdi** [comment]
That looks pretty good since merging :-)
![image](https://github.com/kubernetes-sigs/cluster-api/assets/417870/a3db92bc-e340-4230-ba75-538faa4cf409)

**Comment by chrischdi** [comment]
This is fixed :-)

/close

**Comment by killianmuldoon** [comment]
>This is fixed :-)

Awesome work!

**Comment by sbueringer** [comment]
Nice work on a tricky issue.

I especialy like the k8s-triage links :D !!
