### ISSUE TITLE
Add cli flag to supply namespace for capi controller to watch for Objects

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#912]
/kind feature
Add cli flag to supply namespace for capi controller to watch for Objects

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by detiber** [comment]
Currently we hard code the lister to watch for updates in all Namespaces, We should expose the ability to set a specific namespace using the manager command line arguments that is passed to the lister to limit to a specific namespace.

**Comment by vikaschoudhary16** [comment]
@detiber can you please assign this to me, if anyone is not working already.

**Comment by vikaschoudhary16** [comment]
https://github.com/kubernetes-sigs/controller-runtime/pull/405/files

**Comment by detiber** [comment]
@vikaschoudhary16 I've assigned it to myself (since it doesn't appear that you are a member of the kubernetes-sigs org), and marked it as active.

If you are already a member of the kubernetes org, you can request to be added to the kubernetes-sigs org as well. If not, I'm also happy to sponsor you for membership in kubernetes-sigs.

**Comment by detiber** [comment]
@vikaschoudhary16 this shouldn't require any changes to controller-runtime. Here is how we added the support to cluster-api-provider-aws: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/607 and https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/615
