### ISSUE TITLE
MachineDeployment status does not show the number of ReadyReplicas in a Management cluster

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api#930]
Create a MachineDeployment in ManagementCluster with n Replica
n nodes are created.
Check status of MachineDeployment, the ReadyReplica wont be set to n.

**Comment by vincepri** [comment]
/kind bug

This issue is related to the AWS provider not setting the NodeRef field when running in a Management cluster. The nodeRef was being set before, but the logic was revisited in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/744 because Cluster API wouldn't properly delete the cluster in a management scenario.

Going to close this one here, given it's specific to the AWS provider.
/close

**Comment by detiber** [comment]
@vincepri This would also affect other providers that do not set NodeRef when run in a management cluster (which I believe is all)

/reopen

**Comment by liztio** [comment]
Reproduction steps:

1. Create a new management cluster
2. Use the example yaml and `generate.sh` scripts as per capa [setup instructions](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/getting-started.md#generating-cluster-manifests-and-example-cluster)
3. Wait for machines to run
4. Observe lack of ReadyRequests: 
```console
$ kubectl get machinedeployments   -o=jsonpath='{.items[0].status}'
map[observedGeneration:2 replicas:1 unavailableReplicas:1 updatedReplicas:1]%
```

**Comment by liztio** [comment]
I'm curious how we can make this work in the general case. The only status information reported by the machine is provider-specific:

```console
$ kubectl get machine brew-69b776f86c-8s2tl -o json | jq '.status'
{
  "providerStatus": {
    "instanceID": "i-0d833b1e56938a3bb",
    "instanceState": "running",
    "metadata": {
      "creationTimestamp": null
    }
  }
}
```
If we look at [the structure itself](https://godoc.org/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1#MachineStatus), we see that there's [a `Phase` field](https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L204), currently underpopulated. But it's a free-form text field, not an enum. 

There's the Conditions field, vwhich includes a [ready status](https://godoc.org/k8s.io/api/core/v1#NodeConditionType). This is also not currently not populated by CAPA, I don't know if other things do populated it.

I think perhaps the issue here is that the MachineSet doesn't get updated with ReadyReplicas either. If it did, it'd be trivial to propagate that up to MachineDeployment

**Comment by ncdc** [comment]
@liztio FYI @vincepri is working on a POC to handle setting remote node references. If that is approved, this should be achievable as a follow-up.
