### ISSUE TITLE
Setting doctoc as part of CI

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#934]
/kind bug

This issue is based on discussion at https://github.com/kubernetes-sigs/cluster-api/pull/932#discussion_r281036985

With `doctoc`, it can help generate toc for the markdown file automatically.

/cc @neolit123 @vincepri @detiber

**Comment by dongwangdw** [comment]
How can I help when I can not assign this issue to myself?

**Comment by gyliu513** [comment]
@dongwangdw you can claim that you will work for this in this issue and go ahead to propose PR.

**Comment by dongwangdw** [comment]
@gyliu513 thanks. 

I will work on this issue then.

**Comment by dongwangdw** [comment]
I would like to implement it like this.
Any changes to docs will be detected with pre-commit, then error will be raised and ask the commiter to update the docs with doctoc and commit that too. Then the update shell will reside in hack if the script is necessary. because this update only refers to a line of command. 

Any comments will be appreciated.

**Comment by dongwangdw** [comment]
/assign

Due to this has been merged, I think we can close this one.
