### ISSUE TITLE
How to update existing diagrams in cluster api?

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#935]
If I want to update the svg image like `docs/book/common_code/architecture.svg` etc, how to update it? @vvishal1 can you help? Thanks.

**Comment by detiber** [comment]
@gyliu513 [Inkscape](https://inkscape.org/) is a FOSS tool that is capable of modifying SVG images.

**Comment by gyliu513** [comment]
Thanks @detiber , will check. But here I have more comments for this, how about put all of the RAW images used in cluster-api to a google driver which can be accessed by all cluster-api members? This can make sure everyone can modify the diagrams with ease. 

Istio community is hosting all diagrams in google driver and every Istio member can update the diagram based on their requirement, perhaps cluster-api can follow same way?

**Comment by davidewatson** [comment]
I agree that image editing could be easier. I am not sure that using Google Drive would be better:

- Google Drive and GitHub history are separate. Since the GitBook is stored in GitHub, this means the Cluster API documentation must be kept in sync with the images using an external mechanism.
- Google Drive may not be accessible everywhere.

We should probably document how to edit the images. If there is a better way than installing Inkscape (or Adobe Illustrator, et al.) a proposal comparing the pros and cons of might help. Note that we will be migrating to Netlify this week and this should at least simply the review process.

**Comment by detiber** [comment]
In addition to the potential issues that @davidewatson raises, I am also concerned about the management overhead of using Google Drive, since we would then also need to manage the ACLs for the drive.

**Comment by gyliu513** [comment]
Alright, thanks all for the comments here, I will leave this issue for further discussion and will check Inkscape first to edit.

**Comment by davidewatson** [comment]
@gyliu513: Can you create an issue for this under [sig-contribx](https://github.com/kubernetes/community/tree/master/sig-contributor-experience). Since SVGs are an open format, determining a tool which works for all developers is outside of the scope of the Cluster API project.

/close
