### ISSUE TITLE
Improve and clarify release-notes tool usage

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9556]
Part of Improvement tasks for v1.6 release cycle https://github.com/kubernetes-sigs/cluster-api/issues/9104

> Update documentation to build release notes tool from main before generating notes. We don't want to use go run anymore. Setup make target and ensuring the same binary is run on each release branch.

waiting for a bit more clarity/context from @g-gaston then will begin work here

/area release

**Comment by g-gaston** [comment]
I believe the original intent was to document how to build the release notes tool to a binary so, when doing multiple patch releases on the same day, we always used the same version of the tool (the one from `main`) for all of them. This is because generating the notes requires switching branches so, if the tool is run with `go run`, it will use the version of the code checkout in the current branch. If this branch is a release branch, it might not be up to date.

TBH I think this is already documented [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#create-pr-for-release-notes).

Maybe we can add a make target and replace that `go build` in the docs :)

Opinions?

**Comment by furkatgofurov7** [comment]
As I already guessed in https://github.com/kubernetes-sigs/cluster-api/issues/9104#issuecomment-1761292279, it makes sense to use the tool built from the main branch for all releases we are cutting the same day. 

> Maybe we can add a make target and replace that go build in the docs :)

Fine with me to have one more Makefile target.

**Comment by cahillsf** [comment]
cool, yeah that makes sense to me!

**Comment by cahillsf** [comment]
one clarification here @g-gaston, is the root problem that we don't want to cherry-pick all changes to the release notes tool to the release branches? that is why the tool should be built from `main`?

asking because it looks like there is already [a make target](https://github.com/kubernetes-sigs/cluster-api/blob/ef2a1df06e00934d82c3140445e9634201f7a9a1/Makefile#L1100-L1106) that has some logic for retrieving the envvars that are being manually set in the current doc

**Comment by g-gaston** [comment]
> one clarification here @g-gaston, is the root problem that we don't want to cherry-pick all changes to the release notes tool to the release branches? that is why the tool should be built from `main`?

Yes, you are 100% correct, @cahillsf. We iterate quite frequently on this tool and we wanted to avoid the churn of having to backport it to two release branches every time we make a change.

> asking because it looks like there is already [a make target](https://github.com/kubernetes-sigs/cluster-api/blob/ef2a1df06e00934d82c3140445e9634201f7a9a1/Makefile#L1100-L1106) that has some logic for retrieving the envvars that are being manually set in the current doc

I'll leave it up to you, but given that we don't currently use that target (and in fact we don't recommend it), I would take this as an opportunity to clean it up :)
