### ISSUE TITLE
Expose generate-yaml.sh functionality

### ISSUE THREAD

**Issue by clyang82** [kubernetes-sigs/cluster-api#959]
In order to use `generate-yaml.sh` to generate the `machines.yaml` and `cluster.yaml` from the `template`. the user has to download the source code to accomplish it. This is not a user friendly way.

Suggest to expose `generate-yaml.sh` functionality to `clusterctl generate`. and the end user just pulls the `clusterctl` image can accomplish.

WDYT?

/cc @gyliu513 @jichenjc

**Comment by gyliu513** [comment]
@detiber @vincepri comments?

**Comment by jichenjc** [comment]
I think we want to include the generate-yaml.sh into the clusterctl docker image and use that ?
first  the generate-yaml.sh is provider specific? they might have different options for different vendor?
and you still need download code in order to complete the generation? for example,

something like:
kubectl kustomize $PWD/../../../../config > $PWD/$OUTPUT/provider-components.yaml
you still need download the code in order to have those files

**Comment by clyang82** [comment]
In my understand, yes, the generate-yaml.sh is provider-specific and clusterctl is also provider-specific. Please correct me If I am wrong. Can we consider to bundle the generate-yaml.sh with templates together into clusterctl? That is one way. I am open for other great ideas. I just think download source code is not a good way for client enablement.

**Comment by chenzhiwei** [comment]
Using a single configuration file can achieve same result: https://github.com/kubernetes-sigs/cluster-api/issues/971

**Comment by timothysc** [comment]
Closing this issue in favor of clusterctl v2 design.
