### ISSUE TITLE
Ensure we have user documentation on how to consume nightly / beta / RC releases with clusterctl and test framework.

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9604]
Part of Improvement tasks for v1.6 release cycle https://github.com/kubernetes-sigs/cluster-api/issues/9104

- Ensure we have documentation on how to consume beta / RC releases (for users)
- Document how to consume nightly Cluster API releases with clusterctl and with the test framework.

Need to understand the requirements before moving forward with the improvement.  cc @g-gaston when you have a chance to expand on this a bit

/area release

**Comment by killianmuldoon** [comment]
/triage accepted

This will be great for providers - thanks for working on it!

**Comment by g-gaston** [comment]
TBH, I lack a bit of context here, this precedes me :(

I believe this is to help providers consume the artifacts (so they can do their testing) we produce for beta and RC releases, since these might not be consumable in the same way as "official" releases are. Example: how to use clusterctl from a beta release and make sure it pulls the manifests from that beta release...

@killianmuldoon @sbueringer 
sorry for the ping but maybe y'all can give a few more examples of instructions that could be useful for provider maintainers? Or maybe I got this completely wrong

**Comment by sbueringer** [comment]
My idea was to have general documentation on how to use CAPI beta / RC / nightly releases with clusterctl. We produce all of these but probably almost nobody knows how to deploy CAPI with a RC or nightly release.

**Comment by furkatgofurov7** [comment]
> My idea was to have general documentation on how to use CAPI beta / RC / nightly releases with clusterctl. We produce all of these but probably almost nobody knows how to deploy CAPI with a RC or nightly release.

While checking #9104 I noticed we have another very similar task listed there:

`Document how to consume nightly Cluster API releases with clusterctl and with the test framework.`

which is the same thing, but includes `nightly` to release to beta/ rc releases and testing with not only clusterctl but also `test framework`. 

@cahillsf I will probably merge these 2 tasks into one if there is no objection from your side since they are very similar😄 (btw, we need to update the issue title + description if the merge happens)

**Comment by cahillsf** [comment]
Yep all good with me as discussed during the release today @furkatgofurov7 - going to be OOO next week but will try and make time to dig into this when I return

**Comment by furkatgofurov7** [comment]
/retitle Ensure we have user documentation on how to consume nightly / beta / RC releases with clusterctl and test framework.

**Comment by sbueringer** [comment]
@cahillsf Sorry for the late response. We are publishing the nightly manifests to google cloud storage and they can be referenced like this: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/720b586403edb0517f9c818778421900e4b671a8/test/e2e/data/e2e_eks_conf.yaml#L74

(a more recent URL: https://storage.googleapis.com/artifacts.k8s-staging-cluster-api.appspot.com/components/nightly_main_20231122/core-components.yaml)

**Comment by cahillsf** [comment]
@sbueringer np thanks for taking a look.  reviewed your suggestions and you are right, this piece currently is not supported:
> I'm not sure if it's possible to also consume those manifests with clusterctl. The nice thing is that those manifests are actually the nightly ones and contain the right nightly images (while only overwriting the images doesn't give you the right manifests)

Specifying the google storage URL as an override for the provider repo kicks back the following:
`Error: failed to get provider components for the "cluster-api" provider: failed to get repository client for the CoreProvider with name cluster-api: invalid provider url. Only GitHub and GitLab are supported for "https" schema`

Here's the line in the source code where this is thrown: https://github.com/kubernetes-sigs/cluster-api/blob/2d58e1c6f5efc509f185544a455e5125374215df/cmd/clusterctl/client/repository/client.go#L197

If I'm understanding correctly, I believe the solution is to implement a `repository_googlestorage.go` (or something like that) here: https://github.com/kubernetes-sigs/cluster-api/tree/main/cmd/clusterctl/client/repository and then accept URLs like: `https://storage.googleapis`.  

Does that sound right to you?

**Comment by sbueringer** [comment]
Sounds correct but I'm not an expert on all things clusterctl 😃

(@fabriziopandini )

**Comment by cahillsf** [comment]
👋 @fabriziopandini when you have a chance, can you confirm if this is the correct approach? https://github.com/kubernetes-sigs/cluster-api/issues/9604#issuecomment-1859213714 

(TLDR trying to allow clusterctl to consume the nightly release manifests from URLs like: https://storage.googleapis.com/artifacts.k8s-staging-cluster-api.appspot.com/components/nightly_main_20231122/core-components.yaml)
