### ISSUE TITLE
Request for `PodDisruptionBudget` and `PriorityClass` for CAPI components

### ISSUE THREAD

**Issue by esierra-stratio** [kubernetes-sigs/cluster-api#9704]
### What would you like to be added (User Story)?

As a user, I am submitting a request for the implementation of PodDisruptionBudget and PriorityClass for CAPI components.

### Detailed Description

It would be nice to configure the components of CAPI with a `PriorityClass` and a `PodDisruptionBudget`. In my opinion, this addition is crucial considering the significance of these components in cluster administration. 
The `PriorityClass` would help emphasize their importance over other pods, while the `PodDisruptionBudget` would contribute to ensuring the high availability, stability, and resilience of these core components.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by killianmuldoon** [comment]
I think these sorts of configurations may be beyond the scope of CAPI's default configuration as it makes a lot of assumptions about the Clusters on which CAPI will be deployed. Have you considered using local configurations for the CAPI components to add these fields to the deployment specs?

**Comment by killianmuldoon** [comment]
Thinking about this again, adding a `PodDisruptionBudget` with 1 replica in the Cluster deployments is definitely not something we'd want to do by default as it makes deleting pods trickier in a way that's not very visible to users.

Adding a priority class is less harmful, but it's meaningless to do pick a default value for the class without knowing how the rest of the management cluster is configured. 

I think these PDB and PriorityClass need to be set by management cluster operators when and how they require.

**Comment by esierra-stratio** [comment]
Yes, to enable `PodDisruptionBudget`, a deployment with two replicas would be necessary. 

Certainly, I can understand your approach. Perhaps, in the future, adding this type of configuration as optional and integrated could be a new feature.

**Comment by sbueringer** [comment]
I'm not sure how far we want to go with clusterctl and modifications to the provider YAMLs.

In any case it might be something interesting for the cluster-api-operator

**Comment by sbueringer** [comment]
^^ cc @vincepri regarding consistency / standardization across providers

**Comment by jackfrancis** [comment]
@esierra-stratio would it help if there were a configurable replica count environment variable to pass in to clusterctl when initializing a management cluster? For example:

```sh
$ CAPI_CONTROLLER_MANAGER_REPLICAS=3 clusterctl init...
```

With the above configuration you'd be able to more easily create a mgmt cluster w/ your desired replica requirements from the very beginning. You could then add your own PDB and PriorityClass requirements as a follow-up gesture, re-using the standard `control-plane: controller-manager` labels that CAPI ships.

Of course, you can also manually update the capi-controller-manager replicas, but perhaps this is the additional convenience you're looking for?

**Comment by esierra-stratio** [comment]
Actually, that's what we're doing currently (manually scaling the replicas)... anyway, it could be good to have that environment variable :)

**Comment by jackfrancis** [comment]
@sbueringer @chrischdi how would we feel about making capi-controller-manager replicas configurable via env (default to 1, so no user-affecting change for everyone else)

**Comment by sbueringer** [comment]
I wonder where we start and finish with making every possible field in our components.yamls a configurable env var :)

In general this doesn't seem like a scalable concept.

**Comment by chrischdi** [comment]
I think its fair to have that var for replicas. We want users to use `clusterctl` for the lifecycle due to some things which are implemented in it with having a default of 1 so for normal use cases nothing changes.

We recommend using `clusterctl` and running more than 1 replica seems to be a valid use case (for being able to have a good HA setup due to e.g. PodDisruptionBudget).

Besides that:
I also agree with -1 for adding actual `PodDisruptionBudget` and `PriorityClass` objects. These are highly opinionated on the environment.

For other changes: may be worth as a user to have a `kustomization.yaml` and use kustomize / `kubectl kustomize` to render a file for a local clusterctl repository having all required changes (while referring the upstream yaml). This way a custom `PodDisruptionBudget` and/or `PriorityClass` could also get added.

**Comment by fabriziopandini** [comment]
/close

It seems there is an agreement that we should not add PodDisruptionBudget, and that PriorityClass default is tricky to define without knowing what else runs in the cluster.

We can eventually open a follow-up issue for allowing configuration of the number of replicas for controllers
NOTE: for the sake of simplicity, IMO it would be great to have one variable that applies to all the CAP* controllers, instead of having one for CAPI, CABPK, KCP etc
