### ISSUE TITLE
clusterctl move should be able to handle multiple clusters being in the same namespace

### ISSUE THREAD

**Issue by christophercorn** [kubernetes-sigs/cluster-api#9705]
### What would you like to be added (User Story)?

As a user I would like clusterctl move to be able to handle migrations when there are multiple clusters in the same namespace. As there are many design patterns, some users like myself have ended on having all clusters in the same namespace. This makes using clusterctl move not applicable and are required to create our own solution.

### Detailed Description

clusterctl move should be able to handle many clusters being in the same kubernetes namespace.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
Please note

> clusterctl move has been designed and developed around the bootstrap use case described below, and currently this is the only use case verified by Cluster API E2E tests.
> https://cluster-api.sigs.k8s.io/clusterctl/commands/move

What happens if you try to move multiple clusters? Or is this issue not about a concrete error but instead to expand the supported/tested use cases of clusterctl move beyond the bootstrap use case?

**Comment by christophercorn** [comment]
> Please note
> 
> > clusterctl move has been designed and developed around the bootstrap use case described below, and currently this is the only use case verified by Cluster API E2E tests.
> > https://cluster-api.sigs.k8s.io/clusterctl/commands/move
> 
> What happens if you try to move multiple clusters? Or is this issue not about a concrete error but instead about expanding the supported/tested use cases of clusterctl move beyond the bootstrap use case?

hi. This is a request to move beyond the current supported use case.

**Comment by fabriziopandini** [comment]
Even if not covered by dedicated tests, and thus not recommended/officially supported, clusterctl should be able to move multiple clusters in a single namespace. Is this the use case are you trying to address? Are you having issues?

If instead you are trying to move a single cluster away from a namespace where there are many, this is not supported now. The reason is that there could be things shared across clusters: Cluster Class, IP pools, ClusterResourceSets, eventually Templates etc. 
The existence of resources shared across clusters makes moving a single cluster very complex e.g we cannot move IP pools away from the namespace, otherwise clusters in this namespace will break; from the other side we cannot duplicate IP pools in the target cluster, because it will lead to duplicate ip assignements etc.

Ultimately the complexity is not really in clusterctl move, but in the fact that some things in Cluster API where not designed with this use case in mind. Figuring out what those things are, how they can work in this scenario, identify and implement required fix etc. etc. most likely requires a strong commitment.

Unfortunately, when I proposed a similar [discussion](https://github.com/kubernetes-sigs/cluster-api/issues/3354) some time ago, the issue did not gained traction and got closed after one year of inactivity 😞

**Comment by fabriziopandini** [comment]
note: if this issue is about moving one cluster from a namespace where there are many, this issue is a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/7061 and we should dedup

**Comment by christophercorn** [comment]
> If instead you are trying to move a single cluster away from a namespace where there are many, this is not supported now.

Hi @fabriziopandini
Yes this is exactly what I'm trying to do. This would be very helpful.

**Comment by fabriziopandini** [comment]
> note: if this issue is about moving one cluster from a namespace where there are many, this issue is a duplicate of https://github.com/kubernetes-sigs/cluster-api/issues/7061 and we should dedup

/triage  duplicate
/close
