### ISSUE TITLE
Remove example from --runtime-extension flag in clusterctl

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9796]
The `clusterctl` help text for the `--runtime-extension` options provides [an example](https://github.com/cahillsf/cluster-api/blob/aacbbc780a42363b28c232cccc87bfecd816df0b/cmd/clusterctl/cmd/init.go#L106C2-L106C2):
`Runtime extension providers and versions (e.g. test:v0.0.1) to add to the management cluster.`

Applying this option and example param results in the following error:
`Error: failed to get configuration for the RuntimeExtensionProvider with name test. Please check the provider name and/or add configuration for new providers using the .clusterctl config`

**Comment by sbueringer** [comment]
Sounds good!

/triage accepted

**Comment by fabriziopandini** [comment]
I don't think we should expose test extensions without some docs about what they are and how to use them.

Frankly speaking, I would simply remove the example from the flag description, plus eventually add a note that clusterctl doesn't include any default runtime extensions.

`Runtime extension providers and versions to add to the management cluster; please note that clusterctl doesn't include any default runtime extensions and thus it is required to use custom configuration files to register runtime extensions.`

**Comment by sbueringer** [comment]
I'm fine either way. The reason I wrote sounds good because I thought it is similar to CAPD>

**Comment by fabriziopandini** [comment]
> The reason I wrote sounds good is because I thought it is similar to CAPD.

They are the kind the same, but for CAPD we have a quick start doc that tells users when and how to use CAPD (while we don't have an equivalent for test extensions).
Also, test extensions were mostly implemented to exercise some code path or as a code example, we never really focused on things like user experience or simulating use cases that could make sense for a final user, and thus I fear they might be confusing for people approaching it just because a flag uses it as an example value.

**Comment by cahillsf** [comment]
sounds good, ill close out the existing PR and cut a new one with the doc/help text update suggested
