### ISSUE TITLE
Extend the integration of Kubespray with the bootstrap and control plane of ClusterAPI.

### ISSUE THREAD

**Issue by Goend** [kubernetes-sigs/cluster-api#9859]
### What would you like to be added (User Story)?

- 1.Can have more configurations for the system in ansible task.
- 2.Better support for bare metal.
- 3.Less system adaptation image.
- 4.More custom parameters.
Currently, it's just an idea, and I hope the community can provide some suggestions regarding the feasibility, necessity, and potential impact on Cluster API itself.I would appreciate any suggestions you may have. Thank you!

### Detailed Description

nothing

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

/area bootstrap
```[tasklist]
### Tasks
```

**Comment by Goend** [comment]
area/bootstrap

**Comment by fabriziopandini** [comment]
I'm leaning toward closing this issue because I'm not sure if folks working on this project have the necessary context to discuss how KubeSpray integrates with CAPI, I think this should be discussed in the Kubespray community first and eventually come back to this team in the form of a proposal/set of requirements to address.

opinions?
