### ISSUE TITLE
Add support for consuming nightly release manifests in clusterctl

### ISSUE THREAD

**Issue by cahillsf** [kubernetes-sigs/cluster-api#9999]
Related to https://github.com/kubernetes-sigs/cluster-api/pull/9797, clusterctl current does not support retrieving the nightly image manifests published to `https://storage.googleapis.com/artifacts.k8s-staging-cluster-api.appspot.com/components/...`

Specifying the google storage URL as an [override](https://cluster-api.sigs.k8s.io/clusterctl/configuration#provider-repositories) for the provider repo kicks back the following:
`Error: failed to get provider components for the "cluster-api" provider: failed to get repository client for the CoreProvider with name cluster-api: invalid provider url. Only GitHub and GitLab are supported for "https" schema`

Here's the line in the source code where this is thrown:

[cluster-api/cmd/clusterctl/client/repository/client.go](https://github.com/kubernetes-sigs/cluster-api/blob/2d58e1c6f5efc509f185544a455e5125374215df/cmd/clusterctl/client/repository/client.go#L197)

If I'm understanding correctly, I believe the solution is to implement a `repository_googlestorage.go` (or something like that) here: https://github.com/kubernetes-sigs/cluster-api/tree/main/cmd/clusterctl/client/repository and then accept URLs like: https://storage.googleapis.

**Comment by fabriziopandini** [comment]
What is the use case for using nightly images?

I'm asking this because the tricky part here is the fact that a repository for clusterctl not only contains components.yaml files, but it also must contains metadata.yaml and something that provides a notion of "versions".

Adding those notions to a google storage bucket will probably require to first reconsider how we store nightly releases in google cloud, including the notion of version and the upgrade of metadata files, and I would prefer to avoid such complexity if we can. Most important, IMO this will be hardly reusable for any other google storage bucket.

As alternative, if this use case is not frequent or it is automated like our CI, I think it is okay to use options like creating a local repository (or clusterctl overrides). 

Might be we can even make it simple to create a local repository with nightly release manifests by doing relatively small changes to https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/hack/create-local-repository.py

But it really depends on which use case we are aiming to address....

**Comment by cahillsf** [comment]
> @cahillsf Do you still have the doc that you initially wrote for it? (and can you post it here)

i think i lost it in my last commit, but my original workaround was using [image overrides](https://cluster-api.sigs.k8s.io/clusterctl/configuration#image-overrides) to override the image tag and pull the nightly images.  

will take a look at the local-repository python tool to see if this can help use the full nightly manifests rather than just overriding the images

**Comment by sbueringer** [comment]
Recovered via GitHub UI :)


```
<h1> Deploying nightly release images </h1>

Cluster API publishes nightly versions of the project's images from the `main` branch to a `staging` registry that can be deployed in a management cluster using [clusterctl image overrides](../configuration.md#image-overrides).

The tagging convention for the nightly images is `nightly_main_$(shell date +'%Y%m%d')`.  

For example, to deploy the image versions `nightly_main_20231201` from the Cluster API staging repository, add the following `images` override entry to your [clusterctl config file](../configuration.md#clusterctl-configuration-file):

```yaml
images:
  all:
    tag: nightly_main_20231201
    repository: gcr.io/k8s-staging-cluster-api
```
</aside>
```

I was just hoping overall that there is an easier way with clusterctl to just use a different manifest, then having to replace the images

**Comment by fabriziopandini** [comment]
I can look into the https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/hack/create-local-repository.py to see if this can be sorted out easily

**Comment by sbueringer** [comment]
Thx. I'm fine either way. As mentioned above. If nobody is actually looking for this, we can probably avoid the effort of making this work, documenting and then maintaining it.

**Comment by fabriziopandini** [comment]
ACK, I will give it a try, if it is only one or two hours of effort, it will be nice to have

**Comment by fabriziopandini** [comment]
/assign
sending a quick solution for this issue; we can eventually iterate if there is need
